### ISSUE TITLE
Bug: clearState not working when lambda throws error

### ISSUE THREAD

**Issue by Crafoord** [aws-powertools/powertools-lambda-typescript#1027]
## Bug description

When using `addPersistentLogAttributes` :
```ts
logger.addPersistentLogAttributes({ memberId: 'test'  });
```

and using the middy to clearState:
```ts
export const handler = middy(lambdaHandler).use(
  injectLambdaContext(logger, { clearState: true })
);
```

and then exiting the lambda by throwing an error, the next invocation will still have the persistentLogAttributes present. My guess is that the middleware never runs because of the error.

### Expected Behavior

When lambda crashes the middleware should still `clearState`.

### Current Behavior

When lambda crashes the middleware does not `clearState`.

### Possible Solution

I guess there could be a way of handling this by not using middleware but there is no documentation of how to `clearState` without it.

### Steps to Reproduce

1. create handler like:
```ts
import { Handler } from 'aws-lambda';
import middy from '@middy/core';
import { injectLambdaContext, Logger } from '@aws-lambda-powertools/logger';

const logger = new Logger();

const lambdaHandler: Handler = async (event) => {
  logger.info('Before adding memberId');
  logger.addPersistentLogAttributes({ memberId: 'test'  });
  logger.info('After adding memberId');

  throw new Error();
};

export const handler = middy(lambdaHandler).use(
  injectLambdaContext(logger, { clearState: true })
);

```
2. invoce lambda
3. check logs, `Before adding memberId` will not have memberId property, `After adding memberId` will have memberId: test
4. invoce lambda again
5. check logs `Before adding memberId` will have memberId: test (which is not supposed to be there).

### Environment

"@aws-lambda-powertools/logger": "^1.0.2",
"@middy/core": "^3.1.0"

Lambda runtime: nodejs16.x

**Comment by dreamorosi** [comment]
Hey @Crafoord thank you for reporting this and providing a reproduction example.

Please give us some time to look into it, we'll get back to you as soon as we can.

**Comment by saragerion** [comment]
Thanks again for reporting this bug @Crafoord.
I was able to reproduce this issue as well.

Source code:
https://github.com/saragerion/serverless-typescript-demo/blob/1027-bug-logger-clearstate-not-working-when-lambda-throws-error/src/api/get-products.ts#L20

CloudWatch Logs Insights query: 
```
fields message, memberId, function_request_id, @timestamp
| filter service = 'serverless-typescript-demo'
| filter function_name LIKE /GetProducts/
| sort @timestamp desc
| limit 20
```

Logs output: 
<img width="1224" alt="Screenshot 2022-07-28 at 11 01 24" src="https://user-images.githubusercontent.com/47529391/181466459-e663b206-060f-41c7-a521-58aa2b9f56a0.png">

We will start working on a fix right away and adding this scenario to our E2E tests.

**Comment by saragerion** [comment]
This will be part of the next release. I am going to add the scenario in our E2E tests in a future PR (it requires some refactoring).
