### ISSUE TITLE
Feature request: redact sensitive data from logs

### ISSUE THREAD

**Issue by damianesteban** [aws-powertools/powertools-lambda-typescript#1032]
## Description of the feature request

**Problem statement**

I want to redact potential PII and/or PHI in my serverless logs.
**Summary of the feature**

This may not be a "feature" necessarily, it might be possible with the current middleware. But the idea is I want to pass in an array of keys that would display as redacted in the logs. 

**Code examples**

Example log:

```
  const user = {
    firstName: 'Bob',
    lastName: 'Smith',
  }
  logger.info('new user registered: ' + user);
```

Logs in Cloudwatch:

```
'new user registered: { firstName: [REDACTED], lastName: [REDACTED] }`
```

**Benefits for you and the wider AWS community**

Being able to redact sensitive information from logs is essential.

**Describe alternatives you've considered**

Another logging library. But I like this one.

**Additional context**

**Comment by dreamorosi** [comment]
Hi @damianesteban thank you for taking the time to open this feature request.

I think it's an interesting idea and we have had a very similar feature request that is being discussed here #728

May I suggest that you take a look at that issue and then consider one of these two options:
- If your thoughts align with the existing issue (#728): add your +1 as well as any additional thoughts, then closing this issue in favour the original one 
- If your the feature you had in mind differs significantly from (#728): share additional details around how the API you have in mind would look like and how would it differ from the one described in #728

Thank you again for your interest in Powertools for TypeScript!

**Comment by damianesteban** [comment]
Thank you, I will review. I'd like us to adopt this library as our default logger/tracer for AWS lambda.
