### ISSUE TITLE
Maintenance: integrate into CI/CD package measurement

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1036]
## Description of the feature request

**Problem statement**
Before merging new code into `main` we are running a workflow that measures the impact of the changes on the final package size. The new utility should be part of this workflow.

**Summary of the feature**
This issue tracks the work needed to integrate the new utility as part of the workflow mentioned above. The output report that is generated should then include the parameters util.

**Code examples**
N/A

**Benefits for you and the wider AWS community**
This will help the maintainers to make data driven decisions when it comes to package size.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### Related issues, RFCs

#846

**Comment by am29d** [comment]
Worked on the issue.
