### ISSUE TITLE
Feature request: Increase maximum number of metrics dimension from 10 to 30

### ISSUE THREAD

**Issue by ijemmy** [aws-powertools/powertools-lambda-typescript#1044]
## Summary
Increase maximum number of metrics dimension from 10 to 30

## Bug description
CloudWatch Metrics has increase maximum number of dimensions from 10 to 30 [ref](https://aws.amazon.com/about-aws/whats-new/2022/08/amazon-cloudwatch-metrics-increases-throughput/).  

Currently, `metrics` utility throws an error when user try to add more than 10 dimension. This should be updated to 30. 

Note: Powertools for Python is having the same change in [this issue](https://github.com/awslabs/aws-lambda-powertools-python/issues/1413).  Note that we **DO NOT** consider this as breaking change. (See that issue discussion on this)

### Expected Behavior
Clients should be able to add up to 30 dimensions before throwing an error.

### Current Behavior
Adding more than 10 dimensions will throw an error.

### Possible Solution
You can find the relevant code to update in this [search](https://github.com/awslabs/aws-lambda-powertools-typescript/search?q=MAX_DIMENSION_COUNT).  

Required changes are:
1. Update `MAX_DIMENSION_COUNT` variable from `9` to `29`
2. Update related unit tests 

### Steps to Reproduce
Call `metrics.addDimension()` more then 10 times. See [this test case](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/014c5bd7d5c807064af8f04c16d297a8fe3bc0d9/packages/metrics/tests/unit/Metrics.test.ts#L83) for example.

### Environment

* **Powertools version used**: all
* **Packaging format (Layers, npm)**: npm
* **AWS Lambda function runtime:** all runtimes
* **Debugging logs:** n/a

### Related issues, RFCs
* [Issue with the same change in Python](https://github.com/awslabs/aws-lambda-powertools-python/issues/1413)

**Comment by sthuber90** [comment]
Happy to take over this task

**Comment by dreamorosi** [comment]
Hi @sthuber90 thanks for commenting under the issue. 

Based on the description above the change should involve both the `Metric` class & unit tests, not sure yet about integration tests. Do you need any additional info/support in defining the scope of the feature?

I'll assign the issue to you and I'll be happy to help with reviewing the PR once it's opened.

**Comment by sthuber90** [comment]
Thank you very much. I will try to work out a minimal PR and look into whether integration tests make sense for this feature. All in all, it really seems like a good first issue and easy to start with :)
