### ISSUE TITLE
Feature request: Tracer disable response capturing on a per-method basis

### ISSUE THREAD

**Issue by misterjoshua** [aws-powertools/powertools-lambda-typescript#1064]
## Description of the feature request

I'd like `tracer.captureMethod()` to allow customers to disable capturing the response as metadata on a per-method basis.

**Problem statement**

I find when capturing a method that returns a boatload of data, the subsegment may fail to send because the subsegment exceeds [X-Ray's 64KB segment document size limit](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html).

![image](https://user-images.githubusercontent.com/644092/185450916-646773fc-0b6a-4420-b214-0e90c7dba6bf.png)

In my project, I'm finding it useful to capture the response by default. But, in this particular case, there's just this one method with an oversized method response. I'd want to disable response capture on a per-method basis rather than globally, so the [POWERTOOLS_TRACER_CAPTURE_RESPONSE env](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#environment-variables) doesn't fit my need.

**Summary of the feature**

I think that AWS Lambda Powertools for TypeScript should implement the [Python version's decorator option](https://awslabs.github.io/aws-lambda-powertools-python/latest/core/tracer/#disabling-response-auto-capture).

**Code examples**

```ts
const tracer = new Tracer();

class MyThing {
  @tracer.captureMethod({ captureResponse: false })
  getBigResponse() { ... }
}
```

**Benefits for you and the wider AWS community**

Allowing customers to disable response capturing on a per-method basis would allow them to observe these subsegments in their trace timelines where they would otherwise fail to send.

**Describe alternatives you've considered**

I considered `POWERTOOLS_TRACER_CAPTURE_RESPONSE`, but I don't want to disable response capturing across my entire app.

**Additional context**

None

### Related issues, RFCs
None

**Comment by dreamorosi** [comment]
Thank you @misterjoshua for opening this feature request.

Please give us some time to prioritise the request and fit it in our roadmap. As soon as we have an implementer either from the community or from the maintainers team we'll assign the issue and change the status to "In Progress".
