### ISSUE TITLE
Docs: Add new Discord invite

### ISSUE THREAD

**Issue by sthuber90** [aws-powertools/powertools-lambda-typescript#1073]
## Description of the improvement

**Summary of the proposal**

The community is moving away from Slack and towards Discord. Naturally, we should replace all invitation links to Slack with the Discord counterpart (https://discord.gg/B8zZKbbyET).

**How, where did you look for information**

**Missing or unclear documentation**

**Improvement**

Update links in Readme and documentation (https://github.com/awslabs/aws-lambda-powertools-typescript/search?q=slack&type=code)

**Comment by dreamorosi** [comment]
Hi @sthuber90 thank you for opening the issue, it's indeed an action that we should perform soon.

I'll put this in the backlog of issues to be worked on and add the `good-first-issue` label.

If anyone is interested in making this update please leave a comment below before opening a PR so we can confirm all the occurrences where the change is needed.

**Comment by sthuber90** [comment]
You can assign  it to me if you want, as I already did the same in the python repository but I'm happy to leave it to another first time contributor 😄

**Comment by dreamorosi** [comment]
No no, it's great if you want to do it. I just didn't want to assume you would.

I'll assign it to you then!

**Comment by dreamorosi** [comment]
https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/README.md?plain=1#L6
