### ISSUE TITLE
Feature request: Allow users to specify segment names for captured methods

### ISSUE THREAD

**Issue by misterjoshua** [aws-powertools/powertools-lambda-typescript#1084]
## Description of the feature request

**Problem statement**

Tracer's capture decorators currently try to determine the name of the segment from the function it decorates. While this is fine for a small project, for a larger app, auto-generated names like `### render` are not descriptive enough to identify which part of the code is represented by the segment.

**Summary of the feature**

I'd like the ability to specify the segment name when I capture methods.

**Code examples**

```ts
const tracer = new Tracer(); // aws lambda powertools

interface MyInterface {
   render(): Promise<string>;
}

class ImplA implements MyInterface {
  @tracer.captureMethod({ segmentName: '### ImplA.render' })
  async render() { ... }
}

class ImplB implements MyInterface {
  @tracer.captureMethod({ segmentName: '### ImplB.render' })
  async render() { ... }
}
```

**Benefits for you and the wider AWS community**

Allows developers to more clearly identify the sources of segments in larger codebases. This would make navigating a trace in the X-Ray console easier.

**Describe alternatives you've considered**

I've been putting metadata in the segments to help identify the source code associated with a segment, but this requires a lot of clicking in the X-Ray console to find what I'm looking for.

**Additional context**

In my example above, I named my segments to reference the corresponding concrete class names. In an ideal world, I'd want the automatic naming to replicate this. But I was unsure of two things:

- Whether TypeScript can identify the class name; and
- Whether we should consider changing the segment naming scheme a breaking change.

### Related issues, RFCs
None

**Comment by saragerion** [comment]
Thanks for opening this issue. I agree with you about the benefits highlighted and this is certainly a feature we could consider adding in the future. 
Please allow us some time to discuss this and come back to you.

**Comment by misterjoshua** [comment]
Just as an aside, here's another interesting edge case where specifying `subSegmentName` will be useful.

![image](https://user-images.githubusercontent.com/644092/191129775-d379cc81-289c-4799-a42c-eb3135b514d0.png)

In this case, the tracer tries to derive the name of the segment from the anonymous function returned by the `@Retryable` decorator - but the anonymous function will not have a name, so we get an empty segment name as shown in the trace.

![image](https://user-images.githubusercontent.com/644092/191129676-0f071952-3294-4f84-98e3-fa6e101e70fb.png)
