### ISSUE TITLE
Bug: throws on empty metrics even if told not to in middy middleware

### ISSUE THREAD

**Issue by kiesel** [aws-powertools/powertools-lambda-typescript#1088]
## Bug description

When constructing the middleware like:

```ts
middy(handler).use(logMetrics(metrics, { throwOnEmptyMetrics: false }));
```

... I would expect it to *not* throw an exception, but it does. It just doesn't on the value `undefined`. It is slightly confusing...

### Expected Behavior

Not throw exception.

### Current Behavior

Throws exception

### Possible Solution

Explicitly test for `undefined` and `false`.

### Steps to Reproduce

1. Setup via `middy(handler).use(logMetrics(metrics, { throwOnEmptyMetrics: false }));`
2. Do not emit metric
3. Run handler

### Environment

* **Powertools version used**: 1.2.1
* **Packaging format (Layers, npm)**: npm
* **AWS Lambda function runtime:** nodejs.16x
* **Debugging logs:**

**Comment by flochaz** [comment]
Thanks for reporting this. A fix is on his way !
