### ISSUE TITLE
Maintenance: integrate utility with CI/CD merge process

### ISSUE THREAD

**Issue by ijemmy** [aws-powertools/powertools-lambda-typescript#1097]
## Description of the feature request

**Problem statement**
Every time a PR is merged a number of checks and actions are run on the utilities to make sure that the changes introduced are compatible with the existing code.

Additionally, the workflow that runs on merge also builds the documentation and API docs and publishes it.

**Summary of the feature**
This unit of work tracks the activities and changes needed for the new utility to be part of the merge workflow.

**Code examples**
N/A

**Benefits for you and the wider AWS community**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### Check list

* [ ] Publish doc & api doc **(blocked until the feature is completed)**
* [ ] Release **(blocked until the feature is completed)**
  * Sort out the versioning when we publish with lerna the idempotency utility. Right now we are at > 1.x tag for the core utilities but that cannot be the case for idempotency when we will publish it the first time

### Out of scope
* Adding a similar build & test steps to all (handled in #1100 
* Changing e2e tests workflow to run tests of this utility (handled in #1098)

### Related issues, RFCs
#447

**Comment by ijemmy** [comment]
Put this on-hold. Waiting for the implementation to be completed first.

**Comment by dreamorosi** [comment]
Since [this commit](https://github.com/awslabs/aws-lambda-powertools-typescript/commit/34ef180604d2df53694b416e8350fb579038227a), testing and linting for the existing tests of this utility are being run when a PR is merged.

Closing the issue as completed.
