### ISSUE TITLE
Maintenance: e2e tests failing due to version mismatch

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1114]
## Bug description

Before releasing a new version I was running e2e tests. The integration tests for all Node.js versions are failing due to what appears to be a version mismatch between the version in the layer and the one expected:
```text
{\"level\":\"ERROR\",\"message\":\"Package version mismatch: ${packageJSON.version} != ${process.env.POWERTOOLS_PACKAGE_VERSION}\",\"service\":\"e2e-tests-layer-consumer\",\"timestamp\":\"2022-10-11T12:34:47.567Z\",\"xray_trace_id\":\"1-634562e7-4fdd82be20abfd125ce2ea64\"}
```
From [here](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/3226855354/jobs/5280894390#step:11:47).

Looking at the tested code, the error seems to be thrown [from here](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/layer-publisher/tests/e2e/happy-case.test.lambda.ts#L32-L36).

At the same time, looking at the code that creates the test, the expected version is [declared here](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/layer-publisher/tests/e2e/happy-case.test.ts#L19).

### Expected Behavior

E2e tests should pass successfully.

### Current Behavior

Tests are failing.

### Possible Solution

Review version expected vs actual.

### Steps to Reproduce

Run e2e tests.

### Environment

* **Powertools version used**: latest
* **Packaging format (Layers, npm)**: Layers
* **AWS Lambda function runtime:** all
* **Debugging logs:** See above.

### Related issues, RFCs

N/A

**Comment by flochaz** [comment]
fixed by #1116 
Proof against main after merge: https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/3241270853
