### ISSUE TITLE
[Support Lambda Powertools]: Hashnode

### ISSUE THREAD

**Issue by AlessandroVol23** [aws-powertools/powertools-lambda-typescript#1130]
### Organization Name

Hashnode

### Your Name

Sandro Volpicella

### Your current position

Fullstack Developer

### (Optional) Company logo

https://drive.google.com/file/d/1UnN7rTXBrFYfG0HxnMxqKZP6Gg0-riYf/view?usp=sharing

### (Optional) Use case

We use Lambda Powertools mainly for logging at the moment.
The logger package allows us to inject the context via middy of the lambda function and add additional correlation IDs such as user or post IDs.

### Also using other Lambda Powertools languages?

- [ ] Python
- [ ] Java
- [ ] .NET

**Comment by dreamorosi** [comment]
Thank you @AlessandroVol23, appreciate you opening the issue!

**Comment by dreamorosi** [comment]
The reference was added to the docs and to all the README files that are published on npm.

The docs are [currently staged](https://awslabs.github.io/aws-lambda-powertools-typescript/stage/#how-to-support-aws-lambda-powertools-for-typescript) and will be published before the next release.

Thank you for supporting the project!
