### ISSUE TITLE
[I Made This]: Lambda Powertools - great defaults for batteries that aren't quite (but should be) included

### ISSUE THREAD

**Issue by mikebroberts** [aws-powertools/powertools-lambda-typescript#1131]
### Link to your material

https://blog.symphonia.io/posts/2022-10-24_lambda-powertools

### Description

Article describing why I think Powertools is a good choice for teams that don't already have other mature solutions to solve the problems Powertools addresses. Also covers some tradeoffs / concerns.

### Preferred contact

mailto:mike@symphonia.io

### (Optional) Social Network

https://twitter.com/mikebroberts

### Acknowledgment

- [X] I understand this content may be removed from Powertools documentation if it doesn't conform with the [Code of Conduct](https://aws.github.io/code-of-conduct)

**Comment by dreamorosi** [comment]
Thank you @mikebroberts for writing the post and also for sharing it here.

I appreciate nuanced point of views like this one.

We'll leave a comment here as soon as it's added to the website.

**Comment by dreamorosi** [comment]
The content was linked in a new page of the docs called "We Made This (Community)".

The docs are [currently staged](https://awslabs.github.io/aws-lambda-powertools-typescript/stage/we_made_this/#lambda-powertools-great-defaults-for-batteries-that-arent-quite-but-should-be-included) and will be published before the next release.

Thank you for supporting the project!
