### ISSUE TITLE
[Support Lambda Powertools]: Sennder

### ISSUE THREAD

**Issue by gornovah** [aws-powertools/powertools-lambda-typescript#1134]
### Organization Name

Sennder

### Your Name

Domingo Espinosa Medina

### Your current position

Software Engineer

### (Optional) Company logo

https://drive.google.com/file/d/1vXpRZKF4fScZtehx4OkhLGHRcSCHqqNv/view?usp=sharing

### (Optional) Use case

We use Lambda Powertools mainly for logging and trace at the moment. We use different levels of logs per environment, we use middy.

### Also using other Lambda Powertools languages?

- [ ] Python
- [ ] Java
- [ ] .NET

**Comment by dreamorosi** [comment]
Thank you @gornovah for opening the issue and supporting the project!

We'll leave a comment here as soon as the logo/name are added to the website.

**Comment by dreamorosi** [comment]
The reference was added to the docs and to all the README files that are published on npm.

The docs are [currently staged](https://awslabs.github.io/aws-lambda-powertools-typescript/stage/#how-to-support-aws-lambda-powertools-for-typescript) and will be published before the next release.

Thank you for supporting the project!
