### ISSUE TITLE
[I Made This]: Test Drive AWS Lambda Powertools for Typescript

### ISSUE THREAD

**Issue by mlewis7127** [aws-powertools/powertools-lambda-typescript#1138]
### Link to your material

https://dev.to/aws-heroes/test-drive-aws-lambda-powertools-for-typescript-h3p

### Description

This article takes an existing application, and adds in Logging, Tracing and Metrics from AWS Lambda Powertools for Typescript to show the value it provides

### Preferred contact

https://twitter.com/m_lewis

### Acknowledgment

- [X] I understand this content may be removed from Powertools documentation if it doesn't conform with the [Code of Conduct](https://aws.github.io/code-of-conduct)

**Comment by dreamorosi** [comment]
Thank you @mlewis7127 for writing the post and also for sharing it here.

We'll leave a comment here as soon as it's added to the website.

**Comment by dreamorosi** [comment]
The content was linked in a new page of the docs called "We Made This (Community)".

The docs are [currently staged](https://awslabs.github.io/aws-lambda-powertools-typescript/stage/we_made_this/#lambda-powertools-great-defaults-for-batteries-that-arent-quite-but-should-be-included) and will be published before the next release.

Thank you for supporting the project!
