### ISSUE TITLE
Bug: Unhandled exception not throwed if metrics middleware is present

### ISSUE THREAD

**Issue by jjavierrg** [aws-powertools/powertools-lambda-typescript#1139]
### Expected Behaviour

In a lamda used in a step function, if an exception is throwed by lamda, must fail the lamda to be catch by step function

### Current Behaviour

If MetricsMiddleware is used, exception is handled, a lamda always return a success response

### Code snippet

```JavaScript
const { Metrics, logMetrics } = require('@aws-lambda-powertools/metrics');
const middy = require('@middy/core');

const metrics = new Metrics({
  namespace: 'namespace',
  serviceName: 'service'
});


const perform = async (event) => {
  throw new Error("error");
};

const middlewares = [
  logMetrics(metrics)
];

const performExport = middy(perform).use(middlewares);
module.exports = {
  perform: performExport
};
```

### Possible Solution

Add a call for next middleware on "OnError" function

`
onError: async (request, next) => {
......
next(request);
}
`

### Steps to Reproduce

Run lamda. Returns success response insteadof error

### AWS Lambda Powertools for TypeScript version

latest

### AWS Lambda function runtime

16.x

### Packaging format used

Npm

**Comment by dreamorosi** [comment]
Hi @Jjavierrg, thanks for opening this issue.

I have tried reproducing your issue and I was not able to do so. 

I have created [this repo with the code I have used](https://github.com/dreamorosi/1139-repro-issue), when executing the function this is the error I get:
![image](https://user-images.githubusercontent.com/7353869/199501214-6029f390-dfb7-4626-b461-08664b1a2a65.png)

If you look at the [current implementation of the middleware](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/metrics/src/middleware/middy.ts#L34), you'll see that the `onError` hook is implemented so we shouldn't be catching your error.

Could you please give us more info and/or try the sample in the repo I have shared to see if you see the same issue?

**Comment by Jjavierrg** [comment]
Hi @dreamorosi 

Thanks for your response.

It was my fault! I was using an outdated version of middy (version 1.XX) wich required that produces this bug. Updating the middy version solves my problem.

Thank you!
