### ISSUE TITLE
Maintenance: Refresh SAM examples

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1140]
### Summary

The repo contains SAM examples of how to use the libraries. These examples are one of the most visited pages in the repository and since they were released the project and its documentation has evolved. The examples should be updated to reflect that.

### Why is this needed?

The SAM samples were first created several months ago and in the meantime several updates have happened, so it's time to refresh them.

### Which area does this relate to?

Other

### Solution

Below a list of changes in no particular order:

### Updates to README

- [ ] Change the section that reads "You will need to have a valid AWS Account in order to deploy these resources" to a "Note" with GitHub specific markdown ([see here](https://github.com/community/community/discussions/16925)), so that it's better highlighted.
- [x] Link documentation about Layers in [Layers section](https://github.com/awslabs/aws-lambda-powertools-typescript/tree/main/examples/sam#switch-to-lambda-layer) of the README
- [ ] Modify [X-Ray section](https://github.com/awslabs/aws-lambda-powertools-typescript/tree/main/examples/sam#aws-x-ray) of docs to point to CloudWatch Traces section instead
- [x] Remove the section that talks/lists all IDEs (see image in details below)

<details>
![Screenshot 2022-11-03 at 11 26 03](https://user-images.githubusercontent.com/7353869/199697804-a53d6c01-fbbf-4b42-96f3-c4df42f82c35.png)
</details>

### Maintenance
- [x] Update Powertools dependencies to latest available at time of PR
- [x] Update all `devDependencies` to latest available & test that everything works
- [x] Move back code to `examples/lambda-functions` (where it was originally) & symlink (how it was originally)

### Code 
- [x] Update one Lambda function to use Middy middleware usage (see docs)
- [x] Update second Lambda to use Class-based/decorators usage (see docs)
- [x] Update third Lambda (manual usage - like it is now) and make sure all features are represented (see docs)
- [x] Move Powertools instances creation in shared file & import it throughout other files ([see example here](https://github.com/saragerion/serverless-voting-app/blob/main/src/backend/common/powertools.ts))
- [x] Make sure all functions are minified, have source maps, use `NODE_OPTIONS: --enable-source-maps' ([here](https://docs.aws.amazon.com/lambda/latest/dg/typescript-exceptions.html)), and use `AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1` ([here](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html))
- [x] Move DynamoDB client instantiation in separate shared file, reuse across functions ([see example here](https://github.com/saragerion/serverless-voting-app/blob/main/src/backend/common/dynamodb-client.ts)) & apply tracing to it
- [x] Move from `aws-sdk` (v2) to `@aws-sdk/client-dynamodb` (v3 - [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/index.html)) - keep DocumentClient
- [ ] Add an example of HTTP call (i.e. fake retrieve data at some point) in each function at the beginning, use [phin](https://www.npmjs.com/package/phin) to make requests, make a request to https://httpbin.org/#/Dynamic_data/get_uuid and add the returned uuid to logs ([with this](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/logger/#appending-persistent-additional-log-keys-and-values)), to main segment as annotation ([see docs](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/tracer/#annotations-metadata)), and as metadata to metrics (using [`addMetadata`](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/metrics/#adding-metadata)).
- [x] All functions should log the incoming event: middleware/decorator via parameter, manual via a `logger.info(...)`

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/)

**Comment by bpauwels** [comment]
@dreamorosi as discussed you can assign this to me, I will start working on this

**Comment by bpauwels** [comment]
@dreamorosi I have just created a PR covering the mentioned changes
