### ISSUE TITLE
Documentation Improvement: inconsistency Tracer.ts example code - Tracer Website Docs

### ISSUE THREAD

**Issue by niko-achilles** [aws-powertools/powertools-lambda-typescript#1142]
### Expected Behaviour

consistency of  generated Docs for `Tracer` -> `Lambda Handler` -> `Manual` 
Links: 
- https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/tracer/#lambda-handler
- https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/tracer.md

with

`Tracer.ts` code example snippet  in IDE editor
Link:  https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/tracer/src/Tracer.ts#L80

### Current Behaviour

Using my IDE and reading the documentation on how to use the Tracer i read 
that i should additionally `import { Segment } from 'aws-xray-sdk-core';`
See line: https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/tracer/src/Tracer.ts#L80

This is inconsistent with the docs generated on the Website:
See `Tracer` -> `Lambda Handler` -> `Manual` 

Links:
- https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/tracer/#lambda-handler
- https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/tracer.md

### Code snippet

```JavaScript
see expected and current behavior description
```

### Possible Solution

see expected behavior

### Steps to Reproduce

import Tracer in IDE and follow the example without switching to online Docs of Powertools.

### AWS Lambda Powertools for TypeScript version

latest

### AWS Lambda function runtime

16.x

### Packaging format used

Lambda Layers

**Comment by dreamorosi** [comment]
Hi, thank you for opening this issue. We'll be checking the documentation and the docstrings to make sure they match and any update will land in the next release.

However this is not an issue that affects runtime behavior so I've removed the bug categorization and marked this as documentation improvement.

**Comment by niko-achilles** [comment]
ok, i saw that you will look at things for maintenance and found the time to write about this issue, so that the website docs and code example with IDE support is the same.

**Comment by dreamorosi** [comment]
I have reviewed the examples and opened a PR #1144, if you check the PR and notice any other issue I have missed please leave a comment in the PR.

I'll report back once it's merged.

**Comment by dreamorosi** [comment]
Improvements to the docs released in `v1.4.1`.
