### ISSUE TITLE
[Support Lambda Powertools]: Bailey Nelson

### ISSUE THREAD

**Issue by buggy** [aws-powertools/powertools-lambda-typescript#1143]
### Organization Name

Bailey Nelson

### Your Name

Richa Buggy

### Your current position

Engineering Manager

### (Optional) Use case

We're currently using Lambda Power to provide structured logging but are eagerly awaiting support for parameters and features.

### Also using other Lambda Powertools languages?

- [ ] Python
- [ ] Java
- [ ] .NET

**Comment by dreamorosi** [comment]
Hi @buggy thank you so much for supporting the project!

I'll report back here once the page with the references is up 😄

**Comment by dreamorosi** [comment]
The reference was added to the docs and to all the README files that are published on npm.

The docs are [currently staged](https://awslabs.github.io/aws-lambda-powertools-typescript/stage/#how-to-support-aws-lambda-powertools-for-typescript) and will be published before the next release.

Thank you for supporting the project!
