### ISSUE TITLE
Docs: improve the "Contributing" section documentation

### ISSUE THREAD

**Issue by saragerion** [aws-powertools/powertools-lambda-typescript#115]
## Description of the improvement

**Summary of the proposal**

Right now the contributing docs are very bare. 
To make it inclusive and accessible for contributors from different seniority, background and experience, this area should be be more detailed to make sure that ambiguity is reduced and most importantly, in case of PR's, expectations are communicated early on in the PR progress.

**How, where did you look for information**

In the current Contributing doc.

**Missing or unclear documentation**

Contributions may be related to:
- Design (UX, accessibility)
- Research to scope requirements or understand priorities 
- Improve the documentation
- Add or improve examples
- Writing tutorials
- Implementation of new features via Pull Requests's
- Bux fixes
- Share ideas & proposals
- Organising Github issues, labels, projects
- Review code and Pull Requests

**Improvement**

Rather than 1 single cluttered `CONTRIBUITING.md` file, a folder with organized files/sections might be easier to read and browse.

### Related existing documentation

[Contributing file](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/e210bbdec20c47e1bbe23dac238778cdc5b8fad7/CONTRIBUTING.md)

### Related issues, RFCs

#426 
#422

**Comment by michaelbrewer** [comment]
I do like how python powertools has a simple `Makefile` 

ie: 
- `make dev` - sets up and installs all of the dev dependencies and pre-commit hooks
- `make pr` - does all of the tasks recommended before submitting a PR and includes
   - `make test` - all unit tests including performance tests
   - `make lint` - does all of the linting and security checks
   - `make format` - does all of the code formatting
 - `make docs-local` - for the docs and does not need any docker stuff :P

**Comment by saragerion** [comment]
Another aspect that we should add in our contributing section: avoiding creating PR's that include code changes that are not related to the specific issue they are trying to address.
Housekeeping shows good intentions, but it does not help us maintainers keeping track of the changes that are released and it's better to create a separated issue/PR for changes unrelated to the original scope.

**Comment by ijemmy** [comment]
Should we put contributing section in the doc?
It's easier to locate and search. But the drawback is that the content has to be in the `docs` folder.

**Comment by michaelbrewer** [comment]
normally it is in the root dir

**Comment by flochaz** [comment]
> Should we put contributing section in the doc? It's easier to locate and search. But the drawback is that the content has to be in the `docs` folder.

I personally would prefer to be just a link to CONTRIBUTING.md from doc. Dev will first look at this file at root folder of repo.

**Comment by michaelbrewer** [comment]
I did one for the python project too, makes it super easy to contribute

CodeSpaces config: 
- https://github.com/aws/aws-cdk/blob/master/.devcontainer.json

GitPod config:
- https://github.com/aws/aws-cdk/blob/master/.gitpod.yml

**Comment by dreamorosi** [comment]
Did a quick test with `devcontainer` in  VSCode, leaving this here for future reference:

`.devcontainer/Dockerfile`

```dockerfile
ARG VARIANT="16"
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}

RUN mkdir ~/.npm-global && \
  npm config set prefix '~/.npm-global' && \
  echo "export PATH=~/.npm-global/bin:$PATH" >> ~/.profile

ARG EXTRA_NODE_VERSION=16.5.0
RUN su node -c "source /usr/local/share/nvm/nvm.sh && nvm install ${EXTRA_NODE_VERSION}"
```

`.devcontainer/devcontainer.json`

```json
{
  "name": "Node.js",
  "build": {
    "dockerfile": "Dockerfile"
  },
  "extensions": [
    "dbaeumer.vscode-eslint",
    "esbenp.prettier-vscode",
    "visualstudioexptteam.vscodeintellicode",
    "amazonwebservices.aws-toolkit-vscode",
    "github.copilot",
    "firsttris.vscode-jest-runner"
  ],
  "postCreateCommand": "npm install && npm run lerna-bootstrap && npm run lerna-test"
}
```

**Comment by michaelbrewer** [comment]
I would not mind adding a PR for gitpod / CodeSpaces support. To help onboard contributors.

**Comment by saragerion** [comment]
Just FYI, I created a separate ticket for the scope of "local development" (new contributors onboarding)

#426

**Comment by michaelbrewer** [comment]
There is still typos, python references and aws cdk project references.

**Comment by michaelbrewer** [comment]
Example of referencing `tests/e2e` which does not exist in the repo

<img width="1056" alt="Screen Shot 2022-01-25 at 10 23 54 AM" src="https://user-images.githubusercontent.com/5442469/151037438-30ca1ace-a6a7-49ae-9c9d-66aafaf0232d.png">

Python references, for which there still needs to be a Typescript version of this.

<img width="904" alt="Screen Shot 2022-01-25 at 10 32 53 AM" src="https://user-images.githubusercontent.com/5442469/151037657-48f6532c-7ce5-450f-a354-7c8aaa3d3111.png">

**Comment by ijemmy** [comment]
Most of the items are addressed. Any other future improvement will be their own issue.
