### ISSUE TITLE
Feature request: Return the same result when called with the same payload (FR3)

### ISSUE THREAD

**Issue by ijemmy** [aws-powertools/powertools-lambda-typescript#1157]
## Description of the feature request

**Problem statement**
If the request has already been received before, return the saved result from previous execution.

Check [the design spec]( https://github.com/awslabs/aws-lambda-powertools-typescript/issues/447#issuecomment-1217966844)  for details.

**Summary of the feature**
* Save the result in the persistence layer when it completes. 
* If the Lambda handler receive the request with same payload, it should return a cached result from persistence result
  * In the case that there is an existing record but there is no result (the status is still `IN_PROGRESS`), throw `IdempotencyItemAlreadyExists`
* Edge case(s) 
  * The record may be expired. Check with Python version on how they handle this case. We should aim for the same behavior.

**Code examples**
See [the design spec](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/447#issuecomment-1217966844)

### Story Checklist (for tracking progress)
TBD

### Definition of done
* Include unit tests with 100% code coverage
* Code documentation (TS doc) on classes and public methods

### Related issues, RFCs
#447 

### Solution/User Experience

See #447 

### Alternative solutions

```Markdown
N/A
```

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/)

**Comment by saragerion** [comment]
Closing this issue as we will break down the unit of work different ones.
