### ISSUE TITLE
Feature request: Lambda Layer support for new regions `eu-central-2` & `eu-south-2`

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1169]
### Use case

Over the past days AWS has launched two new regions: `eu-central-2` ([link](https://aws.amazon.com/blogs/aws/a-new-aws-region-opens-in-switzerland/)) and `eu-south-2` ([link](https://aws.amazon.com/blogs/aws/now-open-aws-region-in-spain/)).

Both regions are opt-in but they both launched with AWS Lambda support, which means Layers should be available.

### Solution/User Experience

Over the next releases we should make an effort to publish Powertools Layers in those new regions similar to what we do currently in all other commercial ones.

**Before start working on this, we should agree on the version strategy.** For example, Powertools for Python keeps versions aligned also on newer regions, [they have developed a script](https://github.com/awslabs/aws-lambda-powertools-python/tree/develop/layer/scripts/layer-balancer) that does that automatically and that we could leverage.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/)

**Comment by caioquirino** [comment]
Hi @dreamorosi, how do you generate the layers listed in https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/index.md ?

I see they are all pointed to arn:aws:lambda:<region>:094274105915:layer:AWSLambdaPowertoolsTypeScript:6, so I am interested in knowing how the version (last token) is published, if it's possible to extract for example from github actions.

Thanks!

**Comment by dreamorosi** [comment]
Hi @caioquirino the layers are published with [this workflows](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/workflows/publish_layer.yaml), which uses a CDK app to do the job.

However at the moment the we manually update the version number in the docs after each release. We have an open issue to automate this (#1124) but we haven't gotten around implementing it yet.

From your question I'm assuming you'd like to get the latest version available in a programmatic way, is that the case? I would love to hear more about your use case/need and see if there's something that we can do to help you onboard the layers.

**Comment by dreamorosi** [comment]
@am29d offered to tackle this one.

As part of this item we should include also:
- any other region that was launched since the issue creation (i.e. `ap-southeast-4`)
- making sure the the layer version in the new regions is aligned with the existing ones
