### ISSUE TITLE
Maintenance: Revisit return types of `BaseProvider`

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1172]
### Summary

`BaseProvider` was the first base class implemented for the new Parameters utility.

At the time, it was not yet known what each AWS SDK provider would return. For instance `DynamoDBProvider` might return different types than `SSMProvider`, so the types in `BaseProvider` have been intentionally left generic.

This issue serves to track the task that will have to be carried out after all providers have been implemented.

### Why is this needed?

To enforce strong typing to the values returned by the utility, whenever possible.

### Which area does this relate to?

Parameters

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/)

**Comment by shdq** [comment]
`AppConfig` API returns `Uint8Array`, and the python implementation of the AppConfig provider implicitly converts it to a string. I did [the same](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/1200/files#diff-67776e521a5379e61f3fe11a4d0756663d9701eed5e480060d08dbc986f4cd8fR76-R78) for now, but we have the `transformValue` function in the `BaseProvider`, which I think should do that. Correct me if I'm wrong – the result for the end user is to get raw data (binary) or transformed value to the end type, which is `json` for `AppConfig`.

**Comment by dreamorosi** [comment]
My understanding is that, whenever the user specifies a `transform` when calling `get`, we should apply that transform and return the corresponding type. If no transform is specified, we can return as-is. If a transform has to be applied, then yes, it should be handled by the `transformValue` method from the `BaseProvider`, this applies to all providers.

I don't have 100% confidence on this, but I think your assessment is correct, and the return type on the Python's function might be wrong. Looking at the [docs section for this method](https://awslabs.github.io/aws-lambda-powertools-python/2.5.0/utilities/parameters/#appconfigprovider), the type annotation seems to be `bytes`:
```py
# Retrieve a single secret
value: bytes = appconf_provider.get("my_conf")
```

I think it's worth opening an issue on the Python's repo so that it can be looked at be fixed. If instead we both understood it wrong, then they can clarify what's the expected behavior :)

**Comment by dreamorosi** [comment]
The PR linked above addresses some of the first changes needed to support `DynamoDBProvider`, `SSMProvider`, and `SecretsProvider`.

I have reopened this issue after merging them PR as there might be some additional refactoring needed after the discussion and implementation of `AppConfigProvider` has settled.
