### ISSUE TITLE
Feature request: implement `SSMProvider`

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1176]
### Summary

The Parameters utility should allow customers to retrieve one or more parameters stored in AWS Systems Manager.

This work includes the following tasks:
- [x] Write provider + types
- [x] Unit tests (100% coverage)

### Why is this needed?

1/ So that customers are able to retrieve parameters from SSM, 2/ to reach feature parity with Powertools for Python.

### Which area does this relate to?

Parameters

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/)

**Comment by buggy** [comment]
If it's not actively being worked on by someone else then I'd love to have a go at implementing.

**Comment by flochaz** [comment]
Hi @buggy, thanks for your interest. I think @dreamorosi is already working on it. Let's wait for his answer before investing time in it (he is at re:invent at the moment so his answer might come late).

**Comment by dreamorosi** [comment]
Hi @buggy thanks for offering to contribute to our project.

As Florian mentioned the PR for `SSMProvider` should be up for review early next week (Monday/Tuesday). Perhaps you could be one of the reviewers for the PR and then take up the implementation of [any of the other providers](https://github.com/awslabs/aws-lambda-powertools-typescript/milestone/8) for Parameters. This way we can have a first provider merged and use it as an example for the others.

What do you think?

**Comment by buggy** [comment]
@dreamorosi I'm happy to help.

**Comment by shdq** [comment]
Hey there! I would like to join too and then implement `AppConfigProvider` #1177 with a bit of @dreamorosi's guidance 😉

**Comment by dreamorosi** [comment]
Hi folks, I have opened a draft PR (#1187) with the main features for SSMProvider.

The PR is still a draft because there are some additional features from Python that I still need to implement, however the base `SSMProvider` class as well as the `getParameter` and `getParameters` functions are there. 

This should be enough to get started with the other providers given that they only implement these or a subset of these patterns.

If you're still interested in contributing I would suggest starting with a proposal under the respective issue of each provider.
