### ISSUE TITLE
Maintenance: Docs workflow is failing

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1182]
### Summary

The workflow that builds and publishes the docs on GitHub Pages is currently failing due to a missing step that is supposed to install/build the packages in case of a cache miss of the dependencies.

### Why is this needed?

In order to push the docs on GitHub pages.

### Which area does this relate to?

Automation

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/)

**Comment by heitorlessa** [comment]
https://github.com/actions/deploy-pages/issues/81

**Comment by dreamorosi** [comment]
Thank you Heitor, in our case it was a missing step in our workflow (my bad). It's been fixed in #1183
