### ISSUE TITLE
[Support Lambda Powertools]: globaldatanet

### ISSUE THREAD

**Issue by sthuber90** [aws-powertools/powertools-lambda-typescript#1189]
### Organization Name

globaldatanet

### Your Name

Stephan Huber

### Your current position

AWS Cloud Developer

### (Optional) Company logo

https://raw.githubusercontent.com/globaldatanet/.github/main/profile/logo.png

### Also using other Lambda Powertools languages?

- [X] Python
- [ ] Java
- [ ] .NET

**Comment by dreamorosi** [comment]
Hi @sthuber90 thank you so much for supporting the project!

I'll report back here once the page with the references is up 😄

**Comment by dreamorosi** [comment]
The reference was added to the docs and to all the README files that are published on npm.

The docs are [currently staged](https://awslabs.github.io/aws-lambda-powertools-typescript/stage/#how-to-support-aws-lambda-powertools-for-typescript) and will be published before the next release.

Thank you for supporting the project!
