### ISSUE TITLE
Feature request: support providing aws sdk v3 client

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1222]
### Use case

The upcoming Parameters utility should allow customers to pass their own AWS SDK v3 client to a given provider.

This is useful for those cases in which a client is already available, for tracing the requests made by the client, or for testing (injection).

The feature is supported by the Python's version and already present in the documentation, however the implementation was left out initially.

### Solution/User Experience

> **Note**
> The example below shows the `SSMProvider`, but the feature should be supported by all other providers that use clients

```ts
import { SSMProvider } from '@aws-lambda-powertools/parameters/ssm';
import { SSMClient } from '@aws-sdk/client-ssm';

// construct your clients with any custom configuration
const ssmClient = new SSMClient({ region: 'us-east-1' });
// pass the client to the provider
const parametersProvider = new SSMProvider({ awsSdkV3Client: ssmClient });

export const handler = async (): Promise<void> => {
  // Retrieve a single parameter
  const parameter = await parametersProvider.get('/my/parameter');
  console.log(parameter);
};
```

### Alternative solutions

```Markdown
N/A
```

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/)

**Comment by shdq** [comment]
Hey, @dreamorosi! Let's implement this.

The plan is to use a client that was passed to the provider constructor in `awsSdkV3Client`, but first, check if it is an instance of `ProviderClient`. If it is not, there are two options: throw an error or initialize a new valid client. I'm for throwing the error because initializing a new client wouldn't be what the user may expect. What do you think?

If there aren't any other things to consider, I can start working on the PR.

**Comment by dreamorosi** [comment]
Hey Sergei, sure let's do it.

I actually initially didn't think of making any checks, but it's a good point. Let's do a simple check on whether the client passed is an instance of the class that we expect, and if not, we throw an error like you suggested.

We should also modify the interface/type of the constructor options object to make either `clientConfig` or `awsSdkV3Client` mutually exclusive.

Other than that, at the moment I can't think of anything else!

Happy for you to work on this :)
