### ISSUE TITLE
Maintenance: integration tests for `SecretsProvider`

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1241]
### Summary

As part of #1039, we need to implement integration tests for the `SecretsProvider` which is part of the upcoming Parameters utility.

This issue is used to breakdown the larger epic and track progress in a more granular way.

### Why is this needed?

To increase confidence around the utility behavior by testing it in a real AWS Lambda execution environment. And also to provide a baseline against potential future regressions.

### Which area does this relate to?

Tests, Parameters

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/)

**Comment by am29d** [comment]
Working on the issue.
