### ISSUE TITLE
Docs: broken link to Powertools for Java

### ISSUE THREAD

**Issue by niko-achilles** [aws-powertools/powertools-lambda-typescript#1246]
### What were you searching in the docs?

I clicked on the link for navigating to Powertools for Java. 
The link to JAVA in the Docs point to: https://awslabs.github.io/aws-lambda-powertools-java/latest/

by having the version `latest` in the URL path.

Please note the other Languages `Python` and `.NET` do not have have a dependency of version  introduced in the URL Path.
  

### Is this related to an existing documentation section?

https://awslabs.github.io/aws-lambda-powertools-typescript

### How can we improve?

```Markdown
The link to JAVA Powertools should be independent from version .  

AS IS:
- https://awslabs.github.io/aws-lambda-powertools-java/latest/

AS it should be:
- https://awslabs.github.io/aws-lambda-powertools-java
```

### Got a suggestion in mind?

See `How can we improve section` . 

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by dreamorosi** [comment]
Good catch, a PR would be welcome.
