### ISSUE TITLE
Maintenance: apply linting to `docs/snippets` code snippets

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1252]
### Summary

As part of the efforts described in #729 we are extracting the code snippets present in the docs in their own files, so that we can apply linting as part of our CI.

Once all the code has been extracted, and #1251 has been merged, we should apply the same linting that the rest of the project has to these files.

### Why is this needed?

So that we can automate checking the correctness of the code snippets that are part of the docs, leading to a better DX.

### Which area does this relate to?

Automation

### Solution

The steps needed to close the issue would be:
- add two new npm scripts to the `docs/snippets/package.json` file:
  - `"lint": "eslint --ext .ts --no-error-on-unmatched-pattern logger tracer metrics parameters",` - [example](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/tracer/package.json#L22)
  - `"lint-fix": "eslint --fix --ext .ts --no-error-on-unmatched-pattern logger tracer metrics parameters",` - [example](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/tracer/package.json#L23)
- verify that the linting rules applied are the one in the main `eslintrc.js` file at the root of the project
- run `npm run lint -w docs/snippets` and fix all the linting issues that show up

#### Notes
- in many cases the signature of the `handler` function contains the `any` type. I would recommend to type them as `unknown` for the time being
- as far as I can tell, there's no missing dependency. If there's any, install them like this `npm i -D dependency-name -w docs/snippets`

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/)

**Comment by niko-achilles** [comment]
@dreamorosi  i can take this as task for Friday. 
I read your notes , point `handler function about any type` . I will test with the existing eslint rules as given and see waht i get in the console , OK ?

**Comment by dreamorosi** [comment]
Sure, that works. I expect the current linting to give errors about `any` specifically - but happy to discuss this while working on it.
