### ISSUE TITLE
Docs: Custom Log Formatter Example disappeared from documentation

### ISSUE THREAD

**Issue by ValeryShvyndzikau** [aws-powertools/powertools-lambda-typescript#1253]
### What were you searching in the docs?

Hi AWS Lambda Powertools Team

It looks like Custom Log Formatter Example was accidentally removed in the scope of migration to separate files
Here is a link to the corresponding PR https://github.com/awslabs/aws-lambda-powertools-typescript/pull/1230/files#diff-e42af4aee30a146e6e51be432c4a80c93e50d552f7b70403fa301ecf11d355c4

![logger_documentation_003](https://user-images.githubusercontent.com/1850133/212868899-fa94d3d9-4937-41e1-9c3e-98e3489534ef.jpg)
![logger_documentation_002](https://user-images.githubusercontent.com/1850133/212868907-28ff1c2c-6eb3-44ec-90db-c40d0415357d.jpg)
![logger_documentation_001](https://user-images.githubusercontent.com/1850133/212868909-3b7d9cce-ca22-4625-82df-0966f313e252.jpg)

![logger_documentation_004](https://user-images.githubusercontent.com/1850133/212870314-336a9c6c-cfc3-40f3-9f24-9a16c6bf815c.jpg)

### How can we improve?

```Markdown
Get back Custom Formatter Example
```

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by dreamorosi** [comment]
Hi @ValeryShvyndzikau, thanks for reporting this!

You're right, there must have been a copy/paste issue and indeed the code snippet got removed (although it's still in the git history).

Would you be interested in contributing a PR to bring it back? If yes I'd be happy to help you get it merged quickly. If not, that's alright and we'll put it in the backlog for someone else to pick it up.

**Comment by niko-achilles** [comment]
@dreamorosi  i could take it if needed. It is a copy paste thing. 

I would apply the following in `bringYourOwnFormatterClass.ts` code snippet that is extracted in `docs/snippets/logger` .

```typescript
import { LogFormatter } from "@aws-lambda-powertools/logger";
import {
  LogAttributes,
  UnformattedAttributes,
} from "@aws-lambda-powertools/logger/lib/types";

// Replace this line with your own type
type MyCompanyLog = LogAttributes;

class MyCompanyLogFormatter extends LogFormatter {
  public formatAttributes(attributes: UnformattedAttributes): MyCompanyLog {
    return {
      message: attributes.message,
      service: attributes.serviceName,
      environment: attributes.environment,
      awsRegion: attributes.awsRegion,
      correlationIds: {
        awsRequestId: attributes.lambdaContext?.awsRequestId,
        xRayTraceId: attributes.xRayTraceId,
      },
      lambdaFunction: {
        name: attributes.lambdaContext?.functionName,
        arn: attributes.lambdaContext?.invokedFunctionArn,
        memoryLimitInMB: attributes.lambdaContext?.memoryLimitInMB,
        version: attributes.lambdaContext?.functionVersion,
        coldStart: attributes.lambdaContext?.coldStart,
      },
      logLevel: attributes.logLevel,
      timestamp: this.formatTimestamp(attributes.timestamp), // You can extend this function
      logger: {
        sampleRateValue: attributes.sampleRateValue,
      },
    };
  }
}

export { MyCompanyLogFormatter };

```

**Comment by dreamorosi** [comment]
Great, thank you Niko, that would be the fix.

**Comment by niko-achilles** [comment]
@dreamorosi PR for fixing this issue: #1254 . I was around in the repo looking at things , and i saw this issue raised by @ValeryShvyndzikau  . That's why i took the action to fix quickly.
Nice catch by @ValeryShvyndzikau  .

**Comment by ValeryShvyndzikau** [comment]
Hi @niko-achilles, no problem, thank you very much for your support and quick fix
