### ISSUE TITLE
Bug: TS Compilation error when passing injectLambdaContext as a middy middleware

### ISSUE THREAD

**Issue by varqasim** [aws-powertools/powertools-lambda-typescript#1258]
### Expected Behaviour

The project would compile successfully 

### Current Behaviour

Using @middy/core v1.5.1 & just updated @aws-lambda-powertools/logger to v1.5.1 and I believe that adding the middy interface https://github.com/awslabs/aws-lambda-powertools-typescript/pull/1225 is causing a TS compilation error in my project. I was able to get rid of it by downgrading to v1.5.0. 

The following compilation error I am presented with is
```
Argument of type 'MiddlewareLikeObj<unknown, unknown, Error, Context>' is not assignable to parameter of type 'MiddlewareObject<APIGatewayProxyEvent, { statusCode: number; body: string; }, Context> | MiddlewareObject<APIGatewayProxyEvent, { ...; }, Context>[]'.
  Type 'MiddlewareLikeObj<unknown, unknown, Error, Context>' is not assignable to type 'MiddlewareObject<APIGatewayProxyEvent, { statusCode: number; body: string; }, Context>'.
    Types of property 'before' are incompatible.
      Type 'MiddlewareFn<unknown, unknown, Error, Context>' is not assignable to type 'MiddlewareFunction<APIGatewayProxyEvent, { statusCode: number; body: string; }, Context>'.
        Types of parameters 'request' and 'handler' are incompatible.
          Property 'internal' is missing in type 'HandlerLambda<APIGatewayProxyEvent, { statusCode: number; body: string; }, Context>' but required in type 'Request<unknown, unknown, Error, Context>'.ts(2345)
middy.d.ts(14, 5): 'internal' is declared here.
```

I came to this conclusion by looking at the last line `middy.d.ts(14, 5): 'internal' is declared here.` which was introduced in this PR introduced https://github.com/awslabs/aws-lambda-powertools-typescript/pull/1225. 

### Code snippet

```Typescript
import { APIGatewayEvent } from 'aws-lambda';
import { Logger, injectLambdaContext } from '@aws-lambda-powertools/logger';
import middy from '@middy/core'

const lambdaHandler = async (event: APIGatewayEvent) => {
  const { sub: userId } = event.requestContext.authorizer!.claims;
}

export const handler = middy(lambdaHandler)
  .use(injectLambdaContext(logger, { logEvent: true }));
```

### Steps to Reproduce

Install @middy/core v1.5.1 & and set @aws-lambda-powertools/logger to v1.5.1

### AWS Lambda Powertools for TypeScript version

1.51

### AWS Lambda function runtime

14.x

### Packaging format used

Npm

**Comment by dreamorosi** [comment]
Hi, we don't support `@middy/core@1.5.1`, could you please try with `@middy/core@3.6.2`?

If you still have issues also with that version, could you also share an example of how you're bundling your code and your configs, so that we can investigate further?

**Comment by varqasim** [comment]
@dreamorosi Thank you, then this bug doesn't make sense because it actually works with the v3.6.2 version.
