### ISSUE TITLE
Bug: LogFormatter not forwarded to child loggers

### ISSUE THREAD

**Issue by ghdoergeloh** [aws-powertools/powertools-lambda-typescript#1264]
### Use case

I found out, that I need to pass the LogFormatter to every child. It would be nice to forward the parents LogFormatter as the default to a child logger (via createChild) if no other LogFormatter was provided in that method.

### Solution/User Experience

So if logger.createChild({}) is called without logFormatter it could just get the same instance, the parent is using.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/)

**Comment by shdq** [comment]
Hello @ghdoergeloh, thank you for opening the issue.

I think it is a bug since the child should have all the parent's attributes, except you overwrite them with `options` in `createChild`.

I made a quick fix, but I want to revisit other attributes that may be also missed for children. Then I open a PR.

@dreamorosi assign me, please. This is also part of #483.

**Comment by saragerion** [comment]
While I see the validity of the arguments presented, I'd like us to evaluate first if this would be a breaking change and the potential impact for developers by changing this behaviour now in their production environments. Let us look into it first.

**Comment by shdq** [comment]
@saragerion sure! For context, we changed the implementation of child logger in #1178 last year

**Comment by dreamorosi** [comment]
So, I have been thinking about this and after reading the documentation & docstrings of the method (`createChild`), I think this is a bug.

On a high level, and without context, when we create a child logger we want to create a new instance of this logger that is exactly the same as its parent, except for any override that is explicitly set during creation.

The [docstring for the method](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/45d1078eccf671f589f2cf75dcbabe05dd18a7f2/packages/logger/src/Logger.ts#L199-L200) reads this (emphasis mine):
> It creates a separate Logger instance, **identical to the current one**. It's possible to overwrite the new instance options by passing them.

The [docs](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/logger/#advanced) instead, state this (emphasis mine):
> Logger supports quick **instance cloning** via the createChild method

The wording of both pieces of documentation suggests that the parent and child should be exactly the same, except for any explicit override.

With the above in mind, I would expect the `LogFormatter` in children to be the same as the parent and I think it's safe to consider this a bug and not a breaking change as there's no wording nor indication that the formatter nor any other setting/option should not be persisted.

**Comment by dreamorosi** [comment]
A fix was released as part of the latest [v1.6.0 release](https://github.com/awslabs/aws-lambda-powertools-typescript/releases/tag/v1.6.0).
