### ISSUE TITLE
Feature request: Allow changing log level at runtime

### ISSUE THREAD

**Issue by Aaronius** [aws-powertools/powertools-lambda-typescript#1265]
### Use case

If I have an issue in production, I want to set the debug log level to DEBUG right away. The fastest way for me to do that is through the AWS console. However, if I set the environment variable in the AWS console, the new log level doesn't seem to get picked up in existing execution environments, so the logger doesn't log any subsequent debug logs.

### Solution/User Experience

I'm not sure if changing the environment variable in the AWS console updates environment variables within existing execution environments. If it does, then perhaps the logger could poll the environment variable every minute or so to make sure it's logging at the most recently configured level. Maybe there's a better way to handle this that I'm not considering.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/)

**Comment by saragerion** [comment]
> However, if I set the environment variable in the AWS console, the new log level doesn't seem to get picked up in existing execution environments, so the logger doesn't log any subsequent debug logs.

This is not the expected behaviour and I'd like us to investigate about that's happening here. Can you please share with us the code you use to reproduce this issue?

**Comment by saragerion** [comment]
Note: potentially a bug, needs investigation.

**Comment by Aaronius** [comment]
Nothing special:

```
export default new PowertoolsLogger({
  serviceName: 'ciam',
  sampleRateValue: 0.3,
});
```

and then calling `logger.debug` with messages throughout our app.

FWIW, I'm not really sure how/when AWS gets updated environment variables into the runtime. If changing the log level at runtime is intended to be working as it is, I can play around with it more and see if I find anything new.

**Comment by am29d** [comment]
I tried to reproduce the issue with a simple sam app template:
- create sam-app with powertools ts (log level set to `INFO`)
- invoke the http API
- the log output in CW is `INFO`, log level set to `INFO`
- change the env var in lambda console `LOG_LEVEL` to `DEBUG` 
- invoke the http API
- the log output in CW is `INFO` and `DEBUG`, log level set to `DEBUG`. 

It seems like you create and export your own wrapper around the logger, can you provide more details how you define and use it?

**Comment by codyfrisch** [comment]
> I'm going to leave the feature request open to give a chance to discover other use cases and hear other customers as well.
> 
> From [this discussion](https://github.com/awslabs/aws-lambda-powertools-typescript/discussions/1268#discussion-4818347) it appears that there might be other use cases in which changing the log level at runtime might be useful.

I have another use case for this: dynamically setting the logging level based on a value in the event or context in a multi-tenant environment. Lambda authorizer may set a "debug" level that appears in the event.requestContext.authorizer.lambda.logLevel (for example). I can then "set" the log level for the execution based on that. This way if a specific user is having an issue I can increase logging to troubleshoot just that user without capturing data from all users (who havent authorized us to capture data in logs for example)
