### ISSUE TITLE
[Support Lambda Powertools]: Perfect Post

### ISSUE THREAD

**Issue by jeromeheissler** [aws-powertools/powertools-lambda-typescript#1271]
### Organization Name

Perfect Post

### Your Name

Jérôme Heissler

### Your current position

CEO

### (Optional) Company logo

https://drive.google.com/file/d/120-RL5CPllZ6aOYx_aXW-dugtt-FtXKa/view

### Also using other Lambda Powertools languages?

- [ ] Python
- [ ] Java
- [ ] .NET

**Comment by dreamorosi** [comment]
Hi @jeromeheissler thank you so much for supporting the project!

I'll report back here once the page with the references is up 😄

**Comment by dreamorosi** [comment]
The reference was added to the docs and to all the README files that are published on npm.

The docs are [currently staged](https://awslabs.github.io/aws-lambda-powertools-typescript/stage/#how-to-support-aws-lambda-powertools-for-typescript) and will be published before the next release.
