### ISSUE TITLE
Maintenance: Gitpod definition - deprecated tslint plugin 

### ISSUE THREAD

**Issue by niko-achilles** [aws-powertools/powertools-lambda-typescript#1276]
### Summary

Nowadays, as online resources tend to be unlimited and available, programmers may write code using services like `gitpod`. Contributing to powertools by using gitpod is a use case.  

By looking at the definition of powertools for gitpod , i see the tslint plugin as required extension. 
However the TSLint [has been deprecated](https://medium.com/palantir/tslint-in-2019-1a144c2317a9) in favor of ESLint and the extension has also been deprecated in favor of ESLint's tooling.   

- ms-vscode.vscode-typescript-tslint-plugin

https://github.com/awslabs/aws-lambda-powertools-typescript/blob/61080da2b881353cb3cc84b075559dca07c67c87/.gitpod.yml#L21

### Why is this needed?

Contribute to powertools project using gitpod and minimizing error fatigue . 
By definition gitpod uses the extension tslint when writing code for powertools project. 
Can be switched off manually , however for improvement a deprecated plugin should be removed.  

### Which area does this relate to?

Other

### Solution

The extension tslint in gitpod.yml definition should be removed.

https://github.com/awslabs/aws-lambda-powertools-typescript/blob/61080da2b881353cb3cc84b075559dca07c67c87/.gitpod.yml#L21

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/)

**Comment by dreamorosi** [comment]
Hi Niko, thank you for reporting this.

I'm okay with removing the extension from the configuration. While we do that, we should also remove it from [this other config file](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.devcontainer/devcontainer.json), which is used by GitHub CodeSpaces.

I'll mark this issue as valid and open for contribution.

Note that, while important, there are other more high priority PRs being worked on at the moment, so allow us some light delay in the review of a PR.
