### ISSUE TITLE
Maintenance: Update official SAM CLI template for Powertools

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1278]
### Summary

Issue to track work to add a new template in SAM CLI init command, so customers can choose a hello world example that includes Powertools Tracer, Logger, and Metrics.

This will be part of the official SAM CLI init experience which is now referenced in the AWS Lambda Developer Guide.

For this work package we will:
- Update Powertools version to current latest
- Add support for `nodejs18.x` runtime which is currently missing

### Why is this needed?

We're working with the Lambda team to update the official docs to recommend Powertools on Tracing and Logging sections.

### Which area does this relate to?

Other

### Solution

- Python: https://github.com/aws/aws-sam-cli-app-templates/pull/334
- Java: https://github.com/aws/aws-sam-cli-app-templates/pull/338
- .NET: aws/aws-sam-cli-app-templates#336

Linked to aws/aws-sam-cli-app-templates#339

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/)

**Comment by shdq** [comment]
I'm about to open a PR for this [issue](https://github.com/aws/aws-sam-cli-app-templates/issues/339).

**Comment by dreamorosi** [comment]
The PR on the AWS SAM templates repo was merged, thanks to Sergei's work.

Closing this issue as complete.
