### ISSUE TITLE
Feature request: provide custom functions for JMESPath expressions

### ISSUE THREAD

**Issue by saragerion** [aws-powertools/powertools-lambda-typescript#1298]
### Use case

When making their functions idempotent, users can apply JMESPath selectors that will be used to filter the event payload and/or perform validations. 

In Powertools for Python, the Idempotency utility features some helper functions that allow to extend the JMESPath spec and apply transformations to the result of a selection:

![image](https://user-images.githubusercontent.com/7353869/226218497-9b99b734-c8f0-443e-b4ac-b125c6092c5f.png)

The functions are [defined here](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/utilities/jmespath_utils/__init__.py#L16-L30) and used in the search [here](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/utilities/idempotency/persistence/base.py#L180). Powertools for Python also exposes a [number of common payload expressions](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/utilities/jmespath_utils/envelopes.py) which require the functions and are related to AWS Lambda events. 

### Solution/User Experience

N/A

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/)

**Comment by dreamorosi** [comment]
The module used to implement JMESPath functions introduced in #1376 ([`jmespath`](https://www.npmjs.com/package/jmespath)) doesn't support passing options / using custom functions:
jmespath/jmespath.js#30
jmespath/jmespath.js#25

There is however another package called [`@metrichor/jmespath`](https://www.npmjs.com/package/@metrichor/jmespath) that appears to be a spec-compliant rewrite of the project made in TS and that supports custom functions. This version appears to be more similar to the Python implementation as it also allows to precompile expressions for later usage.

We should evaluate how important this feature is and consider potentially this alternative library.

**Comment by dreamorosi** [comment]
While addressing this issue, consider testing different inputs for the `isMissingIdempotencyKey` function that is part of the `BasePersistenceLayer`. This function tests the output of a JMESPath search and we should make sure that it works correctly.

**Comment by gabrielleandro0801** [comment]
Hi!

As I mentioned in [#2029](https://github.com/aws-powertools/powertools-lambda-typescript/discussions/2029), I'm also interested in this feature. It would be very useful to have these custom helper functions in Typescript so that we could customize our idempotency validations.

Thanks!
