### ISSUE TITLE
Feature request: Custom Config - Max number of items to store in local cache

### ISSUE THREAD

**Issue by saragerion** [aws-powertools/powertools-lambda-typescript#1300]
### Use case

Content TBD.

### Solution/User Experience

Content TBD.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/)

**Comment by dreamorosi** [comment]
Closing in favor of #1299
