### ISSUE TITLE
Docs: fix cleanup command in cdk example

### ISSUE THREAD

**Issue by niko-achilles** [aws-powertools/powertools-lambda-typescript#1311]
### What were you searching in the docs?

Example with cdk, sample application .
Location: https://github.com/awslabs/aws-lambda-powertools-typescript/tree/main/examples/cdk

### Is this related to an existing documentation section?

https://github.com/awslabs/aws-lambda-powertools-typescript/blob/fa236b94b6532685588edd2f440c911dc6de56ab/examples/cdk/README.md?plain=1#L75

### How can we improve?

```Markdown
The instruction on how to delete the sample application is described as follows:  
To delete the sample application that you created, run the command below while in the `examples/sam` directory:

cdk delete

Thoughts:
- The location to run the command is accidently wrong (`examples/sam`) 
- The command to delete is accidently wrong (`cdk delete`)
```

### Got a suggestion in mind?

The proposed update is to correct where (location) to run the command for deleting sample cdk app and the command that should be used deleting (how). 
E.g: in cdk the word `destroy` is used, `cdk destroy`, `npx cdk --destroy`  
    

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by dreamorosi** [comment]
Hi Niko, thank you for opening this issue.

We should fix the issue and fix the file. If anyone is interested in opening a PR to do so, please leave a comment below.

**Comment by PatriciaHeimfarth** [comment]
Can I work on that?

**Comment by dreamorosi** [comment]
Hey, yes definitely!

I'll assign the issue to you. If you have any question about setting up the repo or other processes, let me know.
