### ISSUE TITLE
Maintenance: revisit automation for Issues and PR's

### ISSUE THREAD

**Issue by saragerion** [aws-powertools/powertools-lambda-typescript#133]
Note, the body of this issue was edited to reflect the new scope:

- [x] If possible, when a new issue is created we should add it to [the GitHub project](https://github.com/orgs/awslabs/projects/76) (note, this is not a Project (classic) in GH nomenclature)
- [x] Review & make sure that when a new PR is opened, [this job runs](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/workflows/on_opened_pr.yml#L25-L36) and if the PR body doesn't contain a string that matches [this regex](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/scripts/label_missing_related_issue.js#L20), which should be `Issue number: #digits`, the proper labels and comments are added to the PR.
- [x] Review & make sure that when [this workflow runs](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/scripts/label_related_issue.js) and labels an issue as `status/pending-release`, it also removes the current `status/*` label as well as `help-wanted` (if present).
- [x] If possible, implement [this workflow](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/workflows/release.yml#L137-L155) in this repo, with the difference that in our case it: 1/ queries all issues marked as `status/pending-release` (which should be all closed), 2/ removes the label, 3/ adds a label `status/completed`, 4/ leaves a comment that says the thing has been released (this last point is optional & not a must)
- [x] If possible, extend [this workflow](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/scripts/label_pr_based_on_title.js) to label PRs with the correct areas based on title suffix and with the areas being the utilities only (i.e. `area/logger`, `area/parameters`, etc. - [full list here](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/MAINTAINERS.md#labels))
- [x] If possible, implement a boring cyborg workflow [that does this](https://github.com/awslabs/aws-lambda-powertools-python/issues/1798#issuecomment-1366132114) for Issues and [this](https://github.com/awslabs/aws-lambda-powertools-python/pull/1956#issuecomment-1445260695) for PRs.
- [x] Consider renaming [this workflow](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/workflows/reusable_update_layer_arn_docs.yml) to remove `V2` notation

Older issue body below, hidden for clarify/brevity and to reflect the new focus.

<details>

## Description of the feature request

**Problem statement**

To keep up with our collaboration, for clarity, and make sure our efforts are tracked, there are 2 Github projects:
https://github.com/awslabs/aws-lambda-powertools-typescript/projects
1) AWS Lambda Powertools Typescript - Issues https://github.com/awslabs/aws-lambda-powertools-typescript/projects/2
2) AWS Lambda Powertools Typescript - Pull Requests https://github.com/awslabs/aws-lambda-powertools-typescript/projects/3
All explanations of each column are added in the boards. 
While this structure is helpful, there is margin of improvement for how we can limit the manual effort to keep things tidy so that we understand what's going on.

**Summary of the feature**

Github related automation so that:
- Newly created issues SHOULD be added to the [Issues board](https://github.com/awslabs/aws-lambda-powertools-typescript/projects/2);
-  Newly created issues / Issues that are in the "Needs clarification" column SHOULD NOT have assignees (because assignees = responsible to implement it);
- Newly created issues SHOULD be created with the relevant labels, no assignees, correct projects assigned;
- Issues that are in done done state should be automatically added in form of excerpt and references to the Changelog file and releases descriptions;

This can be achieved through relevant files/setup/configuration via Github actions or files in the `.github` folder.

**Code examples**

TBD.

**Benefits for you and the wider AWS community**

Automation of these tasks will allow maintainers and contributors to focus on the implementation of features rather than administration of tasks. Additionally, shifting the effort from human intervention to automation will reduce the rate of human errors.

**Describe alternatives you've considered**

Not at the moment.

**Additional context**

N/A.

### Related issues, RFCs

</details>

**Comment by saragerion** [comment]
As pointed out by @DanyC97, there is an opportunity for us to explore the new beta projects that are set at a github org level.

**Comment by dreamorosi** [comment]
I have updated the body of the original post to reflect the current scope, after which we can consider the issue complete.

cc @am29d
