### ISSUE TITLE
Maintenance: add disclaimer to PR template to clarify that PRs need to be linked to a triaged issue

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1350]
### Summary

According to the contributing guidelines, each PR should correspond to an issue that has been previously triaged by one of the maintainers. Triaging an issue means acknowledging its importance, defining a scope, and setting a priority. All these are ingredients for a successful PR as oftentimes a mismatch on one of these points can cause friction between maintainers and contributors.

This issue serves to track the action item of adding to the pull request template a disclaimer that clarifies this point.

### Why is this needed?

To properly manage expectations with contributors around the fact that PRs that are not linked to a triaged PR and that have not been agreed upon with a maintainer might not get attention from the maintainers.

### Solution

Add a line at the end of the PR body that reads:
> **Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

This is also the same wording that [the Python repository has](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L40).

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by heitorlessa** [comment]
👏
