### ISSUE TITLE
Maintenance: remove tests folder from the commons dist package

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#1354]
### Summary

> [!important]
> Please refer to [this comment](https://github.com/aws-powertools/powertools-lambda-typescript/issues/1354#issuecomment-1743510844) down below for the latest updates on the scope & tasks for this issue.

In our commons package [we export ](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/commons/src/index.ts#L4-L5) sample resources, which are bundled in our distribution package. We should remove these resources from the distribution package. 

### Why is this needed?

These sample resources are unnecessary for the production build. 

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
Do we treat this as a breaking change?

I agree that they could/should be removed, but we don't know if anyone is depending on them already.

**Comment by am29d** [comment]
Yes, since the code was available to customers. We use the code only in our tests across most packages. Moving the code to commons/tests would require import additional exports. Alternatively we can create a dedicated testing package to move these kind of utilities and e2e related code.

**Comment by dreamorosi** [comment]
> Alternatively we can create a dedicated testing package to move these kind of utilities and e2e related code.  

I think that's the way to go, we should create a new package in the workspace and extract those things not needed at runtime there. Also I don't think we should publish this pkg to npm for now.

---

About the breaking change part, this means we'll have to wait till 2.0

**Comment by dreamorosi** [comment]
@am29d, do you think we should create a separate issue to create, in due time, a the new unpublished package & move over all the internal references to it while also marking the published one as deprecated?

In this issue we could:
- Add a new package to the workspaces `packages/testUtils`, this package will not be published to npm for the time being
- Move all the e2e related utilities, plus the content of the tests (context & events) from `commons` to `testUtils`
- Change all the references in our codebase to point to `testUtils`
- Add a [`@deprecated` annotation](https://typedoc.org/tags/deprecated/) to the things we'll want to drop informing that they'll be removed in the next major version

This way we can avoid adding more things inside `commons` that don't belong there, ease the migration for customers, and also make our life easier when v2 approaches.

Obviously this wouldn't be a priority issue, but I think we could approach it before v2 discussions.

**Comment by dreamorosi** [comment]
As it stands, the only actions left for this issue are:

1. Take `helloworldContext` ([here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/packages/commons/src/samples/resources/contexts/hello-world.ts#L3)) and rename it to `dummyContext`. Then move it under `packages/testing` and export it. This way it can be continued to be used in the unit tests of other utilities.

2. Remove the folder in `packages/commons/src/samples` ([here](https://github.com/aws-powertools/powertools-lambda-typescript/tree/main/packages/commons/src/samples)) and all its contents, as well as all its mentions (i.e. in tests) & exports.

---

If you are interested in working on this issue, please leave a comment below so we can assign it to you. If you have any additional question before claiming the issue, feel free to ask either here on in our [Discord server](https://discord.gg/B8zZKbbyET) under the `#typescript` channel.

**Comment by dreamorosi** [comment]
This is available in preview starting from the `2.0.0-alpha.0` release. You can install this version using the `next` tag, i.e. `npm i @aws-lambda-powertools/logger@next`.
