### ISSUE TITLE
Feature request: `AppConfigProvider` to return the last valid value when the API returns empty value on subsequent calls

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1363]
### Use case

When retrieving a configuration profile from AppConfig, customers need to be mindful of the poll interval and to the fact that AppConfig returns empty responses for every subsequent call made after a successful retrieval **and** before the remote config has changed.

To provide a better DX, and to align with the implementation made in Powertools for Python, we should store the last valid configuration and return it instead of returning a response if users call the API again and the main cache was expired.

### Solution/User Experience

Whenever a valid configuration profile is retrieve, store the value in the provider. Then, if the API is polled before the configuration has been refreshed (which would return an empty response), return the stored value instead of the empty response.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by brnkrygs** [comment]
Started a fork to work on this, will PR as soon as I can!

**Comment by brnkrygs** [comment]
More testing is showing that Subsequent calls are pulling the (empty) value from cache at the right time, and falling back to AppConfig at the right time.

Investigating strategies for an internal secondary cache inside the `AppConfigProvider`. Curious how the python team is handling this... do they leave it up to clients to force a refresh if the value is empty?

**Comment by dreamorosi** [comment]
After the discussion in the PR we have agreed to repurpose the issue to correct the clobbering behavior. I was wrong in my previous message and the expected behavior should be to store a valid value & return it instead.
