### ISSUE TITLE
Docs: API reference  => 404

### ISSUE THREAD

**Issue by maour** [aws-powertools/powertools-lambda-typescript#1366]
### What were you searching in the docs?

I clicked on API reference link on the sidebar but getting 404

https://awslabs.github.io/aws-lambda-powertools-typescript/latest/api/

### Is this related to an existing documentation section?

https://awslabs.github.io/aws-lambda-powertools-typescript/latest/

### How can we improve?

```Markdown
Fix this link

https://awslabs.github.io/aws-lambda-powertools-typescript/latest/api/
```

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by dreamorosi** [comment]
Hi @maour thank you for reporting this, we'll try to fix this as soon as possible.

In the meanwhile you can use this temporary link to access the docs:
https://dev.d3u1bwbtmwjex2.amplifyapp.com/modules.html

Sorry for the inconvenience.

**Comment by am29d** [comment]
It seem we have have removed the [API docs build step](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/63a3909063637ca2306a718a10e35e54881f570e/.github/workflows/reusable-publish-docs.yml#LL116C7-L119C38) during the latest workflow update, so [we try to publish API docs ](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/4367033241/jobs/7637818249#step:12:68)which we did not build before.
