### ISSUE TITLE
Feature request: Export LogLevel Type

### ISSUE THREAD

**Issue by jdoherty** [aws-powertools/powertools-lambda-typescript#1367]
### Use case

Hi there, 

As discussed with Andrea we pull in a logging level from an external config file. 

I'd like to be able to set the logging level based on a string from this file.  According to the current code I need to set a LogLevel.  I cannot do that as this is not an exported type I can use.  

### Solution/User Experience

Please export the type so others can set the logging level themselves.  Ideally provide a utility method or easy way to pass in a string (INFO, DEBUG, ERROR) that returns a logging level.  

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
Hi there, thank you for reporting this.

We recently made the typing for the `logLevel` stricter and having this feature would help.

I'll add this to the backlog.

**Comment by dreamorosi** [comment]
Hi @jdoherty, after reviewing the current exports, you can already use the `LogLevel` and all other types available to Logger via `@aws-lambda-powertools/logger/lib/types`, like so:
```ts
import type { LogLevel } from '@aws-lambda-powertools/logger/lib/types';
```

I'm going to close the issue for the time being and I have already taken note to improve these exports to something more ergonomic like `@aws-lambda-powertools/logger/types` [in the discussion for v2](https://github.com/awslabs/aws-lambda-powertools-typescript/discussions/1269#discussioncomment-5269021).
