### ISSUE TITLE
Feature request: `arm64` support for Lambda Layers

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1374]
### Use case

Currently our public Lambda Layers are tested and confirmed to work on Lambda `x86_64` architecture. Given the performance benefits that Graviton 2 can bring in some use cases, it would be great to explore compatibility with the `arm64` architecture and then eventually deploy the Layers in the regions that support it.

### Solution/User Experience

Customers using `arm64` should be able to use the Layers. Not sure at this stage if we need a dedicated build for that architecture or the same/current layer build would work also on ARM.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by codyfrisch** [comment]
This is blocking for me using the layers, unless I wanted to switch away from `arm64`.

**Comment by dreamorosi** [comment]
Hi @codyfrisch at the moment we don't list `arm64` as compatible runtime mainly because we haven't put in place the infrastructure to run integration tests with functions using that architecture.

With that said however I can confirm that at the time of writing none of the utilities we publish uses any binaries nor architecture specific dependency. 

This means that in principle it should be possible to use our Lambda layer on functions using `arm64` without major issues.

However I understand the importance of having an official confirmation from our side, so we'll try to address this as soon as we can.

**Comment by dreamorosi** [comment]
Just to clarify the message above, what was included in the 1.14.0 tag are the integration tests that allow us to test our code on both `arm64` and `x86_64`.

As mentioned in the linked PR, we want to take some time to run tests over time before officially certifying that the Lambda Layers work with functions using that architecture.

Nevertheless, the passing tests are an indication that we are going in the right direction.
