### ISSUE TITLE
Feature request: less verbose Logger injectLambdaContext

### ISSUE THREAD

**Issue by m-radzikowski** [aws-powertools/powertools-lambda-typescript#1379]
### Use case

The `injectLambdaContext()` middleware is useful:

- it adds context properties,
- it logs the incoming event.

But the amount of properties added to each log is quite big:

```json
    "cold_start": true,
    "function_arn": "arn:aws:lambda:eu-west-1:123456789012:function:shopping-cart-api-lambda-prod-eu-west-1",
    "function_memory_size": 128,
    "function_request_id": "c6af9ac6-7b61-11e6-9a41-93e812345678",
    "function_name": "shopping-cart-api-lambda-prod-eu-west-1",
```

It's quite a lot and having all those parameters in every log message has 2 drawbacks:

- general readability - you need to skip through all of them to find the "message" you are most interested in
- this can be pricy at scale

The Request ID is for sure needed in every request to correlate it with others. But the rest - not so much.the 

### Solution/User Experience

It would be great to have those params logged only once, at start, not in every log. This could be enabled by a flag in `injectLambdaContext()`?

### Alternative solutions

```Markdown
Doing it manually, but we lose the simplicity of using Powertools then. Instead of calling `injectLambdaContext()`, we need to add two calls at the start of the handler:

- add chosen context params manually with `logger.appendKeys()`
- log event
```

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
Hi, thank you for taking the time to open this issue.

Generally speaking we recommend to have as much contextual data as possible in each log entry because oftentimes these entries are consumed outside of their log stream and so we cannot rely on order (i.e. when making queries via CloudWatch Logs Insights). This is why the default behavior for the Logger is to add all this information whenever the context is injected.

With that said, I acknowledge that not all customers might want/need/be allowed to have all this info in every single log.

For this reason we encourage users to extend the LogFormatter class used to emit the logs to align with their logging requirements. This is described in the ["Custom Log formatter (Bring Your Own Formatter)"](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/logger/#custom-log-formatter-bring-your-own-formatter) section of the docs.

Based on your specific requirement, you could extend the default formatter like this:

```ts
// file myLogFormatter.ts
import { LogFormatter } from '@aws-lambda-powertools/logger';
import {
  LogAttributes,
  UnformattedAttributes,
} from '@aws-lambda-powertools/logger/lib/types';

type MostlyLessVerboseLog = LogAttributes;

class MyMostlyLessVerboseLogFormatter extends LogFormatter {
  // Keep track of requestId
  private requestId?: string;

  // This method is called before emitting a log
  public formatAttributes(attributes: UnformattedAttributes): MostlyLessVerboseLog {
    // Check if this log is the first of a request or not.
    // We do this by comparing the request ID present in the context and the one we have stored.
    // If this is the first log being emitted for this requestId, we flip the variable to `true` and store the requestId value
    let isFirstLogOfRequest = false;
    if (attributes.lambdaContext?.awsRequestId) {
      isFirstLogOfRequest = this.requestId !== attributes.lambdaContext.awsRequestId;
      if (isFirstLogOfRequest) {
        this.requestId = attributes.lambdaContext.awsRequestId;
      }
    }

    // Construct default log structure that will appear in every log (you can customize key names etc.)
    const log: MostlyLessVerboseLog = {
      message: attributes.message,
      logLevel: attributes.logLevel,
      timestamp: this.formatTimestamp(attributes.timestamp),
      awsRequestId: attributes.lambdaContext?.awsRequestId,
      xRayTraceId: attributes.xRayTraceId,
      service: attributes.serviceName,
    };

    // If this is the first log of this request, attach the extra context info
    if (isFirstLogOfRequest) {
      return {
        ...log,
        cold_start: attributes.lambdaContext?.coldStart,
        function_arn: attributes.lambdaContext?.invokedFunctionArn,
        function_memory_size: attributes.lambdaContext?.memoryLimitInMB,
        function_name: attributes.lambdaContext?.functionName,
      }
    }

    // Otherwise just log the base values
    return log;
  }
}

export {
  MyMostlyLessVerboseLogFormatter
};
```

and then use it like this:

```ts
// file index.ts
import { Logger, injectLambdaContext } from '@aws-lambda-powertools/logger';
import { MyMostlyLessVerboseLogFormatter } from './myLogFormatter.ts';
import middy from '@middy/core';

const logger = new Logger({
  logFormatter: new MyMostlyLessVerboseLogFormatter(),
});

export const handler = middy(async () => {
  logger.info('Hello');
  logger.info('World');
})
  .use(injectLambdaContext(logger));
```

When running the code above you'll have logs that look like this (aka they have context info in the first log only):
![logs](https://user-images.githubusercontent.com/7353869/227262650-9a815cdc-2ef0-4344-b844-7a72061b492e.png)

Using the pattern above you can customize the behavior further and shuffle around / remove / add fields to your logs while still benefiting from the other features.

**Comment by PatrykMilewski** [comment]
Ready to use log formatter:

```typescript
import { LogFormatter, Logger, LogItem } from '@aws-lambda-powertools/logger';
import type { LogAttributes, UnformattedAttributes } from '@aws-lambda-powertools/logger/types';

class CustomLogFormatter extends LogFormatter {
  // This method is called before emitting a log
  public formatAttributes(attributes: UnformattedAttributes, additionalLogAttributes: LogAttributes): LogItem {
    const baseAttributes: LogAttributes = {
      message: attributes.message,
      service: attributes.serviceName,
      correlationId: attributes.correlationId,
      level: attributes.logLevel,
      timestamp: this.formatTimestamp(attributes.timestamp),
      xray_trace_id: attributes.xRayTraceId,
      requestId: attributes.lambdaContext?.awsRequestId,
    };

    const logItem = new LogItem({ attributes: baseAttributes });
    logItem.addAttributes(additionalLogAttributes);

    return logItem;
  }
}

export const logger = new Logger({
  logFormatter: new CustomLogFormatter(),
});
```

Example output:
```
{
    "service": "<removed>",
    "level": "DEBUG",
    "timestamp": "2025-05-07T12:19:16.311Z",
    "xray_trace_id": "<removed>",
    "requestId": "<removed>",
    "correlation_id": "<removed>",
    "event": { [...] }
}
```
