### ISSUE TITLE
Feature request: ability to set `maxAge` and `decrypt` via environment variables for Parameters

### ISSUE THREAD

**Issue by mikebroberts** [aws-powertools/powertools-lambda-typescript#1380]
### Use case

I typically want to always set "decrypt" to true when getting parameters (since that works just fine whether an underlying SSM param is encrypted or not, and I'm accessing infrequently enough that costs and rate limiting is not a concern), and further I'd like to have a much longer default TTL for caching parameters so that I don't have to configure on every request.

### Solution/User Experience

Be able to set env vars for default values for the parameters module, e.g. :

POWERTOOLS_PARAMETERS_TTL = 86400  (1 day)
POWERTOOLS_PARAMETERS_DECRYPT = true

(see also discussion in Discord at https://discordapp.com/channels/1006478942305263677/1088151329538580631/1088483265003925564)

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
cc @heitorlessa, @jeromevdl - you might want to consider this feature too (omitting .NET for now since they don't have the utility yet).

**Comment by heitorlessa** [comment]
Leave with us! @rubenfonseca @leandrodamascena If I don't create an issue in the Python repo, please do - let's implement this, should be quite fast to do it.

**Comment by dreamorosi** [comment]
Just to follow up on this: I have opened a PR with the new env variables. They should be available in the next beta release or the one right after.
