### ISSUE TITLE
Bug: Build of @aws-lambda-powertools/parameters fails as types/AppConfigProvider.ts uses import with absolute file name

### ISSUE THREAD

**Issue by karthikeyanjp** [aws-powertools/powertools-lambda-typescript#1385]
### Expected Behaviour

Refer [code](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/8a47e76dbb1221991086e1094c15585ff5467c69/packages/parameters/src/types/AppConfigProvider.ts#L6).

``` ts

import type {
  AppConfigDataClient,
  AppConfigDataClientConfig,
  StartConfigurationSessionCommandInput,
} from '@aws-sdk/client-appconfigdata';
import type { GetOptionsInterface } from 'types/BaseProvider';

```

Import for GetOptionsInterface should be from './BaseProvider'.

Since the import is using an incorrect path, build fails. See error below:

```
│ ../../node_modules/.pnpm/@aws-lambda-powertools+parameters@1.7.0-beta/node_modules/@aws-lambda-powertools/parameters/types/AppConfigProvider.d.ts:2:42 - e
│ 2 import type { GetOptionsInterface } from 'types/BaseProvider';
│                                            ~~~~~~~~~~~~~~~~~~~~
│ Found 1 error in ../../node_modules/.pnpm/@aws-lambda-powertools+parameters@1.7.0-beta/node_modules/@aws-lambda-powertools/parameters/types/AppConfigProvi
│  ELIFECYCLE  Command failed with exit code 2.
```

### Current Behaviour

`GetOptionsInterface` is imported from incorrect path.

``` ts

import type {
  AppConfigDataClient,
  AppConfigDataClientConfig,
  StartConfigurationSessionCommandInput,
} from '@aws-sdk/client-appconfigdata';
import type { GetOptionsInterface } from 'types/BaseProvider';

```

### Code snippet

`GetOptionsInterface` is imported from incorrect path.

``` ts

import type {
  AppConfigDataClient,
  AppConfigDataClientConfig,
  StartConfigurationSessionCommandInput,
} from '@aws-sdk/client-appconfigdata';
import type { GetOptionsInterface } from 'types/BaseProvider';

```

### Steps to Reproduce

pnpm run build

### Possible Solution

Import `GetOptionsInterface` from correct path.

``` ts

import type {
  AppConfigDataClient,
  AppConfigDataClientConfig,
  StartConfigurationSessionCommandInput,
} from '@aws-sdk/client-appconfigdata';
import type { GetOptionsInterface } from './BaseProvider';

```

### AWS Lambda Powertools for TypeScript version

latest

### AWS Lambda function runtime

18.x

### Packaging format used

npm

**Comment by dreamorosi** [comment]
Hi @karthikeyanjp thank you for spotting this and for taking the time to report it.

The report is valid and the import should be: `import type { GetOptionsInterface } from '../types/BaseProvider';` (relative).

Would you be interested in contributing a fix via PR? If not, we'll definitely address this before the next beta release.

**Comment by karthikeyanjp** [comment]
@dreamorosi sure, I will submit a PR for this.
