### ISSUE TITLE
Feature request: support `CRITICAL` log level

### ISSUE THREAD

**Issue by H1Gdev** [aws-powertools/powertools-lambda-typescript#1395]
### Use case

I would like to monitor `lambda function` logs by `level key`. (using `Amazon CloudWatch`)

In another `lambda function`(using Python), `ERROR` and `CRITICAL` are already used properly, so I would like to use them differently in new `lambda function`(using Node.js) under the same conditions.

`Node.js` and `Java` do not provide `critical` level.

Ref. #1392

### Solution/User Experience

- Add `CRITICAL`.
- Add `critical` method in `Logger` class.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
Hi @H1Gdev thank you for taking the time to open this feature request following [our previous discussion](https://github.com/awslabs/aws-lambda-powertools-typescript/discussions/1392).

For the benefit of future readers, I'll include here my initial response as for why Powertools for Python supports this log level while this library doesn't:
> Powertools for Python builds on top of Python's [`logging` module](https://docs.python.org/3/library/logging.html) that is part of the standard library. As such, that version of Powertools supports the [same levels](https://docs.python.org/3/library/logging.html#logging-levels) that the `logging` module supports:

| Level | Numeric Value |
|--------|--------|
| `CRITICAL` | 50 |
| `ERROR` | 40 |
| `WARNING` | 30 |
| `INFO` | 20 |
| `DEBUG` | 10 | 
| `NOTSET` | 0 | 

> Node.js on the other hand, deals with logs differently and doesn't have a strict level structure like Python does. The closest thing to Python's `logging` library in Node.js is the [`Console` object](https://nodejs.org/api/console.html#class-console).

> The `Console` object does have some methods like `info`, `debug`, `warn`, `error`, etc. but doesn't have a concept of levels, **and most importantly for this discussion**, doesn't have a method that maps to `CRITICAL`. In Node.js, using one method or the other only influences whether the log will be emitted to `stdout` or `stderr` with `warn` and `error` going to `stderr` and all others going to `stdout`.

> In Powertools for Typescript however the log level doesn't just influence the [which `Console` method will be used](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/logger/src/Logger.ts#L648-L650) to log, but it also influences the fact that logs [will contain a `level` key](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/logger/src/Logger.ts#L499) ([see docs](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/logger/#standard-structured-keys)).

----

While as mentioned the log level doesn't have a correspondent in Node.js, I see value in aligning the output of Logger between this library with the Python version. In this way, users who operate functions in both languages can use the same queries, dashboards, and alarms on these logs.

In our implementation, Logger will accept the `CRITICAL` log level which under the hood will map to `console.error` and emit to `stderr`. From the log and output perspective there will be no difference between calling `logger.error` and `logger.critical` except for the fact that the latter will contain `level: "CRITICAL"` as key.

I'll move this to the backlog to be implemented.
