### ISSUE TITLE
Maintenance: Pre-Launch Security Review

### ISSUE THREAD

**Issue by alan-churley** [aws-powertools/powertools-lambda-typescript#140]
Before the launch we need to get the repo approved and check by both AppSec and AOD/ TS Developers,

**Comment by saragerion** [comment]
Closing this issue as it doesn't apply

**Comment by willfarrell** [comment]
> Closing this issue as it doesn't apply
@saragerion Why? Is CodeQL SAST, or equivalent, already applied and is sufficient?

**Comment by saragerion** [comment]
Thanks for allowing me to clarify this.
Security is the top priority and we will address units of work around this area as soon as we have a more stable code version (actually pretty soon).
Units of work in this area may include actionable items emerged from internal AWS reviews as well as the utilisation of automated tooling (still to be defined). 
We will open new related issues with a smaller scope and a more accurate, actionable, detailed description when applicable.
