### ISSUE TITLE
Docs: Fix warning in metrics documentation

### ISSUE THREAD

**Issue by leandrodamascena** [aws-powertools/powertools-lambda-typescript#1422]
### What were you searching in the docs?

The rendering of this banner is wrong as the line below is missing a tab.

![image](https://user-images.githubusercontent.com/4295173/234930563-42f1ef0b-c27c-4cc8-9707-dcdbc6d0478e.png)

### Is this related to an existing documentation section?

https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/metrics/#manually

### How can we improve?

```Markdown
Fix the format. I'm sending the fix.
```

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by dreamorosi** [comment]
Thanks for the fix, appreciate it!
