### ISSUE TITLE
[Support Lambda Powertools]: Elva

### ISSUE THREAD

**Issue by TastefulElk** [aws-powertools/powertools-lambda-typescript#1426]
### Organization Name

Elva

### Your Name

Sebastian Bille

### Your current position

Founder & Developer

### (Optional) Company logo

https://drive.google.com/file/d/1bRNg6KMUvKT5Q505lONsrYV4MKawYcsd/view?usp=share_link

### Also using other Lambda Powertools languages?

- [ ] Python
- [ ] Java
- [X] .NET

**Comment by dreamorosi** [comment]
Thank you Sebastian for letting us feature Elva on our pages and obviously for using Powertools!
