### ISSUE TITLE
Feature request: Make max dimensions count configurable in Metrics

### ISSUE THREAD

**Issue by alan-churley** [aws-powertools/powertools-lambda-typescript#143]
Currently the Max dimensions has a hard coded limit of 9 dimensions, this matches the python functionality.

However it would be good if this could be customisable, with perhaps a default limit of 9, so that users can choose to override this if they wish,

Similar to how this is done in the logger: https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/logger/types/Logger.ts#L14

**Comment by TessavWalstijn** [comment]
Hey I'm interested in picking up this issue

**Comment by saragerion** [comment]
That's awesome @TessavWalstijn! 

Before you start working on the code, allow me one or two days to update this issue description to add more details. 
cc: @dreamorosi @heitorlessa
