### ISSUE TITLE
Docs: fix inappropriate hilighted lines

### ISSUE THREAD

**Issue by rinfield** [aws-powertools/powertools-lambda-typescript#1466]
### What were you searching in the docs?

Some highlighted lines in the sample code are inappropriate. Some are pointing to the wrong place, others to a line that does not exist.

The most obvious example is the "Example CloudWatch Logs excerpt" in Metric's "Adding metadata". It should be specified by highlighting the metadata on line 31.

### Is this related to an existing documentation section?

https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/metrics/#adding-metadata

### How can we improve?

Review and fix the highlighted lines in the code sample to ensure that they are correct.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by dreamorosi** [comment]
Hi @rinfield thank you for reporting this.

I will go through the docs and doublecheck the highlighted lines and report back here.
