### ISSUE TITLE
Docs: Add new primary documentation location (beta)

### ISSUE THREAD

**Issue by sthulb** [aws-powertools/powertools-lambda-typescript#1467]
### What were you searching in the docs?

N/A

### How can we improve?

```Markdown
N/A
```

### Got a suggestion in mind?

The documentation is currently hosted using GitHub Pages, we would like to move the docs to S3 hosting, allowing us to use our own custom domain name and infrastructure for the hosting.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by dreamorosi** [comment]
Thank you Simon, ping us if you have any question about the workflows.
