### ISSUE TITLE
Bug: Idempotency Package has No Exports

### ISSUE THREAD

**Issue by brianhyder** [aws-powertools/powertools-lambda-typescript#1479]
### Expected Behaviour

The Idempotency package exports the functions and classes necessary to utilize the idempotency package.

### Current Behaviour

The idempotency package does not seem to export any of the functions/classes as the other packages do.
 
If you look at the [package.json](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/idempotency/package.json) for the idempotency implementation, it specifies that `lib/index.js` is the main entry point.  However, that [file does not exist](https://github.com/awslabs/aws-lambda-powertools-typescript/tree/main/packages/idempotency/src).  When you look at the other packges (logging, [metrics](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/metrics/src/index.ts), etc) it has the same [package.json](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/metrics/package.json) configuration but the index file exists.

### Code snippet

See the links above.

### Steps to Reproduce

See the links above.

### Possible Solution

Add the index.ts file to the idempotency package and export the necessary types and functions.

### Powertools for AWS Lambda (TypeScript) version

main

### AWS Lambda function runtime

18.x

### Packaging format used

npm

**Comment by dreamorosi** [comment]
Hi @brianhyder thanks for opening the issue.

At the moment this is intentional as we hadn't gotten yet to the point of building the utility for npm.

We will prioritize this item as soon as #1474 is merged, which should happen sometime tomorrow or Monday at the latest.

**Comment by brianhyder** [comment]
Excellent.  I really appreciate the reply and workaround.

**Comment by dreamorosi** [comment]
Hi Brian, I have merged some changes that include a new structure for exports. The PR description has some examples.

You should be able to access all the modules and types. This is a new structure that we haven't used in other utilities, so if there's any issue module/type that you need to access and it's not exposed, please don't hesitate to let me know and I'll fix it.

Thank you again for opening the issue and for the patience!
