### ISSUE TITLE
Bug: Log Level SILENT must be set before instantiation

### ISSUE THREAD

**Issue by zirkelc** [aws-powertools/powertools-lambda-typescript#1503]
### Expected Behaviour

I expected the log level to be a toggle that is being evaluated at the time a message is being printed. That means if I set `process.env.LOG_LEVEL="SILENT"`,  the message **should not** be printed and if I reset the log level the message should be printed.

```ts
const logger = new Logger({ serviceName: "serverlessAirline" });
logger.info("INFO"); // should log 

process.env.LOG_LEVEL = "SILENT";
logger.info("SILENT"); // should not log
``` 

### Current Behaviour

The log level is evaluated at the time of instantiation. That means changing the log level after the logger was created, has no effect and will still print messages.

This prints:
```ts
const logger = new Logger({ serviceName: "serverlessAirline" });
logger.info("INFO"); // prints

process.env.LOG_LEVEL = "SILENT";
logger.info("SILENT"); //  prints
``` 

And this doesn't print:
```ts
process.env.LOG_LEVEL = "SILENT";
const logger = new Logger({ serviceName: "serverlessAirline" });
logger.info("INFO"); // doesn't print
logger.info("SILENT"); // doesn't print
```

### Code snippet

See sandbox: https://codesandbox.io/s/muddy-bush-j54nwp?file=/src/index.ts

### Steps to Reproduce

See sandbox: https://codesandbox.io/s/muddy-bush-j54nwp?file=/src/index.ts

### Possible Solution

The `process.env.LOG_LEVEL` variable should always be checked when a message is being printed. If the `process.env.LOG_LEVEL` differs from the constructor `logLevel`, the environment variable should have priority. 

Alternatively, the if the constructor was was called __without__ `logLevel`, then the log level from `process.env.LOG_LEVEL`, should always have priority. 

### Powertools for AWS Lambda (TypeScript) version

1.7

### AWS Lambda function runtime

18.x

### Packaging format used

npm

**Comment by dreamorosi** [comment]
Hi @zirkelc thank you for taking the time to open the issue.

The behavior you describe is intended. 

You have multiple ways of setting the e log level, both when instantiating the Logger and at runtime.

One of them is via environment variables, which together with the `logLevel` parameter passed to the constructor, is always evaluated upon instance creation and stored in the class.

If you want to change the log level after that, aka at runtime, then you can do so [using the `setLogLevel()`](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/logger/#log-levels) method. When you change the log level using the method, all logs emitted after that should comply with that level.

**Comment by zirkelc** [comment]
Hi @dreamorosi thanks for the quick response! 

I understand, I thought changing the environment variable `LOG_LEVEL` should have the same effect as changing the log level via the class method `setLogLevel()`.

In some case I don't have access to the `logger` instance, because the logger is nested in other functions which I don't have access to. In these cases it would be good to have a flag to temporarily switch the log level.

A similar discussion happened a few months ago: https://github.com/awslabs/aws-lambda-powertools-typescript/issues/1198
I think evaluating the `LOG_LEVEL` variable at log-time would allow to turn off the logs during tests without having the need to silence the test framework completely, like it is currently needed for Jest with `--silent`.

**Comment by dreamorosi** [comment]
I'm not sure I'm following, if you don't have access to the logger then how are you logging?

Regarding to that discussion, we decided to support local development via another environment variable called `POWERTOOLS_DEV`.

Overall I don't think evaluating the log level every time we need to print a log is a good idea for performance, and generally speaking I don't consider environment variables something that should change at runtime in most cases.

I think it'd help if you could share a few more details on the use case and what you're trying to do, maybe I can help find an alternative.
