### ISSUE TITLE
Maintenance: Docs doesn't upload versions.json when being updated

### ISSUE THREAD

**Issue by sthulb** [aws-powertools/powertools-lambda-typescript#1520]
### Expected Behaviour

When generating the docs and uploading to S3, the versions.json file should be updated

### Current Behaviour

The action responsible for docs, doesn't generate the versions.json file

### Code snippet

N/A

### Steps to Reproduce

On release, observe the lack of versions.json file being upload

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

18.x

### Packaging format used

Lambda Layers, npm

**Comment by dreamorosi** [comment]
My understanding is that this is managed by the `mike` command and that the file normally would be stored in the `gh-pages` branch and updated in memory by `mike` itself, before being committed.

I don't know if the utility is able to do the same with S3, if not we'll have to write an utility that gets the current file from S3, updates it, and uploads it again.

---

I'm changing the categorization of the issue to maintenance. Generally we try to keep feature requests and bugs only to Powertools utility related issues, all others are either maintenance (like this one) or documentation.
