### ISSUE TITLE
Bug: Prevent a single metric have more than 100 data points

### ISSUE THREAD

**Issue by leandrodamascena** [aws-powertools/powertools-lambda-typescript#1529]
### Expected Behaviour

Flush metric set when data point is reached to prevent potential data loss, where 100+ data points are added thus being ignored silently by CloudWatch EMF when processed in the background.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html#CloudWatch_Embedded_Metric_Format_Specification_structure_target

### Current Behaviour

More than 100 metric data points can be added.

### Code snippet

```typescript
import { Metrics, MetricUnits } from '@aws-lambda-powertools/metrics';

const metrics = new Metrics({
  namespace: 'serverlessAirline',
  serviceName: 'orders',
});

export const handler = async (
  _event: unknown,
  _context: unknown
): Promise<void> => {
  metrics.addMetric('performedActionA', MetricUnits.Count, 1);
  metrics.addMetric('performedActionA', MetricUnits.Count, 2);
 // add other 100 values to the same metric
};
```

### Steps to Reproduce

Run the code added in code snippet	

### Possible Solution

Serialize and flush metric data set when a single metric reaches 100 data points. Dimensions etc should be kept intact.

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

18.x

### Packaging format used

Lambda Layers, npm

**Comment by dreamorosi** [comment]
Hi @leandrodamascena thanks for reporting this.

I have added a (failing) test that looks like this:

```ts
test("it should publish metrics when the array of values reaches the maximum size", () => {
  // Prepare
  const metrics: Metrics = new Metrics({ namespace: TEST_NAMESPACE });
  const consoleSpy = jest.spyOn(console, "log");
  const metricName = "test-metric";

  // Act
  for (let i = 0; i <= MAX_METRICS_SIZE; i++) {
    metrics.addMetric(`${metricName}`, MetricUnits.Count, i);
  }
  metrics.publishStoredMetrics();

  // Assess
  // 2 calls to console.log: 1 for the first batch of metrics, 1 for the second batch (explicit call)
  expect(consoleSpy).toHaveBeenCalledTimes(2);
  const firstMetricsJson = JSON.parse(consoleSpy.mock.calls[0][0]) as EmfOutput;
  const secondMetricsJson = JSON.parse(consoleSpy.mock.calls[1][0]) as EmfOutput;

  expect(firstMetricsJson[metricName]).toHaveLength(MAX_METRICS_SIZE);
  expect(secondMetricsJson[metricName]).toHaveLength(1);
});
```

Based on my understanding of [this section](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html#CloudWatch_Embedded_Metric_Format_Specification_structure_target) of the EMF Specification, the values array should not exceed length 100: 
> Valid values of target members depend on what is referencing them. A metric target MUST be a numeric value or an array of numeric values. Numeric array metric targets MUST NOT have more than 100 members. A dimension target MUST have a string value.

As a result, Metrics should flush the stored metrics and handle the next ones transparently - which is not the case at the moment.

We'll work on a fix and include it in the next release.
