### ISSUE TITLE
Feature request: makeHandlerIdempotent Masks Internal Errors

### ISSUE THREAD

**Issue by brianhyder** [aws-powertools/powertools-lambda-typescript#1530]
### Use case

As an engineer implementing the idempotency package, I need to know what is causing the failures while testing the implementation.  I must be able to see, in output or attached to the error that is surfaced, to properly handle or mitigate the error.  It took additional time to line-by-line debug it.

Example: While testing, I had forgotten to give my lambda permissions to the dynamodb table.  The test failed with a generic error with message, `Failed to save in progress record to idempotency store`.

Example: While testing, my sso session had expired and my credentials were no longer valid.  My tests failed with a generic error with a message such as, `Failed to update success record to idempotency store`.

Place where this happens:
* [before](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/packages/idempotency/src/middleware/makeHandlerIdempotent.ts#L127)
* [after](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/packages/idempotency/src/middleware/makeHandlerIdempotent.ts#LL152C10-L152C62)
* [error](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/packages/idempotency/src/middleware/makeHandlerIdempotent.ts#L174)

### Solution/User Experience

Consider one or both of the following:
1. Log the error out to standard error
2. Attach the original error as an _inner_ error. 
```
const persistenceErr = new IdempotencyPersistenceLayerError(
  'Failed to save in progress record to idempotency store'
);
persistenceErr.inner = originalErr;
```
Alternatively, you just make each of the custom errors take an additional argument which is the original error.

### Alternative solutions

```Markdown
see above
```

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda-typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
Hi @brianhyder, thanks for opening the issue and presenting suggestions.

The use case is valid and we shouldn't be catching & masking the errors generated from your code.

We'll be discussing this later today & propose a solution in an upcoming PR.

**Comment by brianhyder** [comment]
Thank you!
