### ISSUE TITLE
Maintenance: Update docs base origin url

### ISSUE THREAD

**Issue by hjgraca** [aws-powertools/powertools-lambda-typescript#1550]
### Summary

Update base origin variable in mkdocs javascript

### Why is this needed?

Due to the move to the new domain `docs.powertools.aws.dev` we need to update the old entries that point to `awslabs.github.io`

### Solution

Change `awslabs.github.io` to `docs.powertools.aws.dev`

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda-typescript/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
Thank you @hjgraca for the issue!
