### ISSUE TITLE
[Support Lambda Powertools]: Certible

### ISSUE THREAD

**Issue by HannesOberreiter** [aws-powertools/powertools-lambda-typescript#1562]
### Organization Name

Certible

### Your Name

Hannes Oberreiter

### Your current position

FullStackDeveloper

### (Optional) Company logo

https://static.certible.com/logos/certible.svg

### (Optional) Use case

Currently mainly the `logger` to allow log level separation for stacks and easily add persistent key variables to the log.  

### Also using other Powertools for AWS Lambda languages?

- [ ] Python
- [ ] Java
- [ ] .NET

**Comment by am29d** [comment]
Thank you for the support Hannes, much appreciated!
