### ISSUE TITLE
Maintenance: update OIDC intermediary thumbprints

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1564]
### Summary

GitHub [announced yesterday](https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/) that they have made some changes to the Certificate Authority (CA) configs which affect OIDC connections. The changes impact all the workflow that use OIDC connectors to obtain temporary AWS credentials.

We need to update the config according to the advisory.

### Why is this needed?

So that we can continue using the workflows securely.

### Which area does this relate to?

Automation

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda-typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by am29d** [comment]
Done, layer and e2e test accounts have now new finger print. There is no need for changes in the repo.
