### ISSUE TITLE
Bug: Lambda Layer v14 empty

### ISSUE THREAD

**Issue by willbamford** [aws-powertools/powertools-lambda-typescript#1569]
### Expected Behaviour

v14 Lambda Layer should contain packages.

### Current Behaviour

v14 Lambda Layer is empty.

### Steps to Reproduce

Calling:
```
aws lambda get-layer-version-by-arn --arn arn:aws:lambda:us-east-1:094274105915:layer:AWSLambdaPowertoolsTypeScript:14 --region us-east-1
```

And then downloading the `Content.Location` results in empty zip:
```
nodejs
  node_modules
    <nothing-in-here>
```

Seems broken across regions.

But v13 is populated with packages i.e.
```
aws lambda get-layer-version-by-arn --arn arn:aws:lambda:us-east-1:094274105915:layer:AWSLambdaPowertoolsTypeScript:13 --region us-east-1
```

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

18.x

### Packaging format used

Lambda Layers

**Comment by dreamorosi** [comment]
Hi @willbamford thank you for reporting this, we'll be taking a look today and report back here.

**Comment by am29d** [comment]
I can confirm the folder is empty, I am looking into that.

**Comment by am29d** [comment]
Reopened the issue. I will first release a new layer version, once the new deployment confirms, I will close this issue.

**Comment by am29d** [comment]
Hey @willbamford , thanks again for reporting the bug quickly. The new version `15` is available in all supported regions. And sorry for the issues we might have caused with the empty layer release.
