### ISSUE TITLE
Docs: Suggestions for Idempotency

### ISSUE THREAD

**Issue by brnkrygs** [aws-powertools/powertools-lambda-typescript#1572]
### What were you searching in the docs?

I was working on setting up an environment to beta test the new idempotency package - specifically trying to understand how to implement the function wrapper. Feedback has been shared through other channels, but felt it appropriate to capture here as well.

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/typescript/latest/api/modules/_aws_lambda_powertools_idempotency.html#function-wrapper

### How can we improve?

```Markdown
First, thanks for working on this package! Excited to see it approaching launch.

* 2nd sentence of intro paragraph: “use it to wrapp a function”
* middy example doesn’t make sense, doesn’t use `processingFunction` anywhere
* under Usage, permissions aren’t listed (broken link), can’t find this anywhere actually
* need guidance on DynamoDB table structure
* if DynamoDB table isn't automatically created, remove statement saying it will be
* fix example import for `DynamoDBPersistenceLayer`
* example has `processingFunction` spelling wrong in one case
* example needs to actually _invoke_ `processingFunction`
* middy example uses APIGW example types, but has `SQSRecord` as `processingFunction` parameter
* on Interface `DynamoDBPersistenceOptionsWithClientInstance` page, awsSdkV3Client description references AppConfigProvider
```

### Got a suggestion in mind?

* suggest link to JMES docs (to be honest, I was surprise that JSONPath wasn't used. Isn't it more idiomatic? Maybe that's just me though).
* clarify how cascading behavior of AWS client generation works for DynamoDB Persistence Layer (using provided one over generated one)
* suggest a more thorough description of what `dataKeywordArgument` does, including fallback behavior if there isn’t a match, and how it does or does not interact with `eventKeyJmesPath`
* consider discussing how one could write unit tests to exercise wrapped functions

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by dreamorosi** [comment]
Hi @brnkrygs thank you for taking the time to go through the project and write down all the notes.

As we discussed earlier internally, I have already started working on some of the fixes and will continue doing so.

I'll open a PR soon!

**Comment by dreamorosi** [comment]
All the issues described except the dead URL to the main docs should have been fixed.

We'll add the docs in one of the next PRs.
