### ISSUE TITLE
Feature request: implement `SQSFifoPartialProcessor` class

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1587]
### Use Case

The Python version of Powertools for AWS features a class called `SqsFifoPartialBatchProcessor ` class, which extends the `BatchProcessor` class. This class is needed because the use case of processing a batch of messages from an SQS configured as FIFO requires special handling. In the event of a failure, the whole batch must be marked as failed to maintain the order of the messages.

### Solution/User Experience

Refer to the implementation [found here](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/utilities/batch/sqs_fifo_partial_processor.py#L15), and specifically to the `SqsFifoPartialBatchProcessor` class.

### Acceptance criteria

- The class covers all the features found in the reference implementation
- The class and its types are exported 
- Unit tests are implemented with 100% coverage
- Classes and methods are documented via docstrings, following project's conventions as much as possible

**Comment by erikayao93** [comment]
I will be working on this soon.
