### ISSUE TITLE
Feature request: support accessing Lambda context in record handler

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1607]
### Use Case

In the Python version of Powertools for AWS, when using Batch Processing and specifying a record handler customers can optionally configure the utility to pass the Lambda context to the record handler. This is useful in those cases in which the record handler needs to be aware of info from the context or needs to be able to [retrieve the amount of time](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-context.html) left before the function times out.

### Solution/User Experience

Refer to the implementation [described here](https://docs.powertools.aws.dev/lambda/python/latest/utilities/batch/#accessing-lambda-context).

In Python the feature is possible thanks to the existence of keyword arguments, customers can simply specify an argument named `lambda_context` in the record handler function and the Batch Processing utility will propagate the context from the function to it. In JS there's no notion of keyword arguments so we'll have to find an alternative solution. Proposals/ideas are welcome.

### Acceptance criteria

- Unit tests are implemented with 100% coverage
- Added code is documented via docstrings, following project's conventions as much as possible

**Comment by erikayao93** [comment]
Picking up implementation on this!
