### ISSUE TITLE
Maintenance: remove proxy-agent from dependencies

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#1610]
### Summary

We have `proxy-agent` in our `devDependencies` but it is not used anywhere. With the recent CVE on vm2 which is a transitive dependency of the `proxy-agent` I could not find any usage in our codebase. I suggest to remove the dependency. 

### Why is this needed?

Because there is a critical CVE https://github.com/advisories/GHSA-cchq-frgv-rjh5 and we don't use it.

### Which area does this relate to?

Other

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda-typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
If I remember correctly `http-proxy` was added around the time this script was also added: `packages/commons/tests/utils/cdk-cli.ts`.

If the e2e tests are still running then we're good!
