### ISSUE TITLE
Maintenance: revert changes to dependencies & fix e2e tests

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1614]
### Summary

In #1611, #1612, and #1613 we removed some dependencies from the `package-lock.json` and `package.json` files in an effort to remove deprecated dependencies. While removing them, the team assumed they weren't being used in the project, however this was a mistake as at least one of the dependencies (`http-proxy`) is used by an internal module of CDK, which is used to run our integration/e2e tests.

After merging the PR I ran our test suite, which resulted in failures across the board: https://github.com/aws-powertools/powertools-lambda-typescript/actions/runs/5558549980/jobs/10153776837

While we continue looking for alternatives (#1314), we need to restore the dependencies.

### Why is this needed?

So that we are able to continue running our integration tests while we look for an alternative to these dependencies.

### Which area does this relate to?

Tests

### Solution

Restore the content of the `package.json` & `package-lock.json` to the one found in [this commit](https://github.com/aws-powertools/powertools-lambda-typescript/commit/7cfac60bd5f597348c3dbb6a1aebdbf22a0fed3d).

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda-typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by am29d** [comment]
that’s odd, I ran the tests before the merge and they passed. Will run the r2-d2 tests next time before merge.
