### ISSUE TITLE
Maintenance: Docs Website is down (503)

### ISSUE THREAD

**Issue by leoselig** [aws-powertools/powertools-lambda-typescript#1634]
### Expected Behaviour

Tried to visit any of the links to the documentation website. Example: https://docs.powertools.aws.dev/lambda/typescript/latest/

### Current Behaviour

Receiving 503 from associated CloudFront distribution:

```
503 ERROR

The request could not be satisfied.

The CloudFront function associated with the CloudFront distribution is invalid or could not run. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner. 
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation. 
Generated by cloudfront (CloudFront)
Request ID: RMdNsjE8t1A_GEvBeSMf5VKzSHTO24YPMlZzwe_mgEc67LdR177PxA==
```

### Code snippet

(template doesn't fit my issue, apologies)

### Steps to Reproduce

1. Visit https://docs.powertools.aws.dev/lambda/typescript/latest/

### Possible Solution

–

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

18.x

### Packaging format used

npm

**Comment by dreamorosi** [comment]
Hi @leoselig thank you for opening the issue, we became aware of the issue a few minutes ago and are looking into it.

I'll report back here once we have more visibility on the issue and have a fix.

**Comment by dreamorosi** [comment]
I've changed the label & types of the issue as this doesn't constitute a bug in [our definition](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/MAINTAINERS.md#is-that-a-bug).

I'm going to close this as resolved.
