### ISSUE TITLE
[Support Lambda Powertools]: tecRacer GmbH & Co. KG

### ISSUE THREAD

**Issue by hfahlbusch** [aws-powertools/powertools-lambda-typescript#1650]
### Organization Name

tecRacer GmbH & Co. KG

### Your Name

Helge Fahlbusch

### Your current position

Software Quality Specialist

### (Optional) Company logo

https://www.tecracer.com/wp-content/uploads/2022/01/tR_RGB_White_b.svg

### Also using other Powertools for AWS Lambda languages?

- [ ] Python
- [ ] Java
- [ ] .NET

**Comment by dreamorosi** [comment]
Hi @hfahlbusch thank you so much for this issue and for supporting the project, we really appreciate it!

I'll add the name to the READMEs and docs in a PR later this week and report back here once it's published :)

**Comment by hfahlbusch** [comment]
Thanks @dreamorosi ! 
Glad to have a tool like powertools! We have started with the logging, also using the metrics and I guess we will have a look in the parameters part too.

**Comment by dreamorosi** [comment]
I have added the name & link to [the docs](https://docs.powertools.aws.dev/lambda/typescript/latest/#how-to-support-powertools-for-aws-lambda-typescript) (if not showing yet wait a few moments or clear your browser cache) as well as the readme files of the utilities.

The new version of the files will be published on npmjs.com on the next Powertools release.

Thank you again for supporting the project, it means a lot for us!
