### ISSUE TITLE
JSONObject should support narrowing to `[key: number]:JSONValue`

### ISSUE THREAD

**Issue by codyfrisch** [aws-powertools/powertools-lambda-typescript#1689]
### Use case

Behind the scenes, javascript converts numeric keys to strings. The pattern `object[1234]` is valid. However, JSONObject is defined as `[key: string]: JSONValue` and the result of getMultiple (dynamodb provider) cannot be cast into a type like `[key: number] : JSONValue` since `string` cannot be narrowed to `number`.

The type being used expects it to be a number, because that is how the parameter is accessed.

You can do `object[1234]` today without this change because TypeScript knows about the behavior of numbers being converted to strings. This is simply about narrowing the type to only allow numbers. 

### Solution/User Experience

Update JSONObject to the following type: `type JSONObject = { [key: string | number]: JSONValue; }`

This way a type can narrow `JSONObject` to `[key: number]:JSONValue`.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda-typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by codyfrisch** [comment]
I haven't actually had an issue using the Parameters utility, from a functionality standpoint, its working fantastic.

This is entirely a types issue.

The JSONObject is as follows:

`type JSONObject = {
   [key: string]: JSONValue;
}` today. 

my parameters though are `type MyParameters = { [key: number] : ParameterValue; }`

When I do a `getMultiple` for the parameter, the object returned is of `type JSONObject`. I need to cast this into the type `MyParameters`. Since my type uses `[key: number]` (as my keys are always numbers) this causes a typescript error: 

`Conversion of type 'string | number | boolean | JSONObject | JSONArray' to type 'MyParameters' may be a mistake because neither type sufficiently overlaps with the other.`

As soon as I change `MyParameters` to `[key: string]` this stops. Basically, my need is that I should be able to narrow the key of the parameter to a number (which JS converts to a string behind the scenes of course). This way type checking will help catch if I were to instead of a number try to get a parameter with a string like `stringParameterId`.

I'm not a typescript guru though so my supposition on how to correct it may be wrong. I am working around this by casting to unknown first, then MyParameters. But my instincts tell me that some improvements to the JSONObject type could eliminate this need.

This is mostly just a suggestion to investigate an improvement to the typing.

**Comment by am29d** [comment]
Hey @codyfrisch ,

I have double checked the option to use number as key, and you are correct. We could extend the key with `number`, so you can catch it for your return value. I have tested this options in multiple e2e tests and it works.

**Comment by KhurramJalil** [comment]
Hi @am29d!
I just stumbled upon this and didn't see anyone assigned so went ahead and made the required update.
Please review/approve and do the needful to merge the following PR into master.

https://github.com/aws-powertools/powertools-lambda-typescript/pull/1715

> Hey @codyfrisch ,
> 
> I have double checked the option to use number as key, and you are correct. We could extend the key with `number`, so you can catch it for your return value. I have tested this options in multiple e2e tests and it works.
> 
> Also feel free to submit a PR, if you'd like.

**Comment by dreamorosi** [comment]
Hi @KhurramJalil, thanks for the interest in contributing to the project!

I'll assign the issue to you and change its state to reflect that it's in progress.

This is a relatively small change so there's no issue, however for future reference, in the case of more significant contributions please review the [contributing guidelines](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/CONTRIBUTING.md#summary) and make sure the change is discussed before submitting a PR, we would hate it for you to dedicate a lot of time and effort on something, only to be stopped in the review step.

Let's continue the discussion on the PR.
