### ISSUE TITLE
Docs: remove `beta` warning from README files

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1690]
### What were you searching in the docs?

Now that the Bats Processing & Idempotency utilities are GA we should remove the beta warning from the README files ([example](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/packages/batch/README.md?plain=1#L4-L6)) like we did for the docs.

### How can we improve?

```Markdown
N/A
```

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by am29d** [comment]
There was some unexplained behaviour with the docs deployment yesterday. Although I have removed the warning and the workflow for doc deployment was successful, the old version was still present. 

@sthulb and I checked today in the morning and reran the exact same command and it updated synced the docs with main branch. We find an explanation, but we will monitor it to find the inconsistency.
