### ISSUE TITLE
Docs: Tracer examples for `addMetadata` and `addAnnotation` don't work

### ISSUE THREAD

**Issue by perpil** [aws-powertools/powertools-lambda-typescript#1699]
### What were you searching in the docs?

I was trying to add my own metadata to the xray traces.

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/typescript/latest/core/tracer/#annotations-metadata

### How can we improve?

These examples don't actually work, the result in errors like this:

`You cannot add metadata to the main segment in a Lambda execution environment`
`You cannot annotate the main segment in a Lambda execution environment`

Either document that you need to start new segment before you can use `addMetadata` and `addAnnotation` with an admonition or wrap these examples with code to start a new segment, switch to it, `addMetadata`/`addAnnotation` close the segment and switch back.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by dreamorosi** [comment]
Hi @perpil thanks for reporting this, I'm working on a PR to make some changes to these sections and address your issue.
