### ISSUE TITLE
Feature request: Add back Idempotent decorators

### ISSUE THREAD

**Issue by HaaLeo** [aws-powertools/powertools-lambda-typescript#1700]
### Use case

I want to annotate class methods with a decorator.
Example:
```ts
export class Foo {
  @MakeIdempotent(config)
  public submitPayment(): void {
    // Do something
  }
}
``` 

Since the package now is based on typescript 5.x (#1375) I'd assume this should not be a problem.

### Solution/User Experience

Add the decorators back in which have been removed with #1553

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda-typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by am29d** [comment]
Hey @HaaLeo again 🙂

thanks a lot for the feedback and raising these points. As you pointed out, we have waited for TypeScript 5.x migration so we know the decorator interface. Now we can add this feature, that will also be available in the layer 👍 . 

Best
Alex

**Comment by dreamorosi** [comment]
Hi @HaaLeo, we have merged the PR that adds the Idempotency utility to the Layer and we plan on making a release during the week.

We will need a bit more time to implement the decorators for the utility so it's likely going to come in a future release.
