### ISSUE TITLE
Feature request: add parameters and batch to layers

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#1711]
### Use case

After substantial refactoring of the layer and build scripts, we can now add batch and parameters utilities to the layer. 

### Solution/User Experience

Add the utilities to the bundle step and add test code to the lambda function to use the utilities

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda-typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
Change merged in #1712
