### ISSUE TITLE
Bug: cannot use captureAWSv3Client with the latest Tracer and AWS SDKs

### ISSUE THREAD

**Issue by danielsitnik** [aws-powertools/powertools-lambda-typescript#1763]
### Expected Behaviour

When using Tracer, I expect to be able to use the `captureAWSv3Client` function with any of the official SDKs.

### Current Behaviour

When trying to use `captureAWSv3Client` with `GlueClient` (or any other client), TypeScript complains with the following error:

<img width="761" alt="image" src="https://github.com/aws-powertools/powertools-lambda-typescript/assets/1395838/5bf88224-971f-4004-af5b-2167e8cda2c4">

I'm using TypeScript version `4.9.5`.
Tested on DynamoDBClient and GlueClient, both at version `3.431.0`

### Code snippet

```typescript
import {Tracer} from '@aws-lambda-powertools/tracer';
import {GlueClient} from '@aws-sdk/client-glue';

const tracer = new Tracer({serviceName: 'myService'});
tracer.captureAWSv3Client(new GlueClient({}));
```

### Steps to Reproduce

Just use the provided code snippet.

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

16.x

### Packaging format used

npm

**Comment by dreamorosi** [comment]
Hi @danielsitnik, thanks for taking the time to open this issue.

Based on the screenshot you have shared the type error appears to be coming from a file called `dependency-container.d.ts` at line 31, column 5. The project doesn't have any file with that name and you can verify this by searching the repo.

To try to isolate the issue, I have also tried to reproduce the error you describe using the versions you listed but was not able to. You haven't specified the version of Powertools Tracer you're using, so I have assumed the latest (`1.14.0`).

I have also created a sample repository with my setup, which you can find here: https://github.com/dreamorosi/repro-1763

After cloning that repository, please run `npm ci` to install the dependencies and then `npm run build` to compile it. In my case I was able to do so without error. Likewise, the IDE doesn't show any error.

If you can, please try to clone the repo I have shared and see if you see the error in that one as well.

**Comment by danielsitnik** [comment]
Ohhh my bad!
I didn't notice it was coming from `dependency-container.d.ts`, this is from [tsyringe](https://github.com/microsoft/tsyringe).

I have been using it with the AWS SDKs for over a year without any problems.
I guess the latest versions of the SDK changed something in the clients constructor that is causing this incompatibility now. 😞

Sorry, I'll take this issue over to the tsyringe team.
