### ISSUE TITLE
Feature request: implement built in schemas

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#1787]
### Use case

Using zod schema, implement a selection of the popular Lambda events, similar to [models from powertools python](https://github.com/aws-powertools/powertools-lambda-python/tree/develop/aws_lambda_powertools/utilities/parser/models). 

Use the [test events](https://github.com/aws-powertools/powertools-lambda-python/tree/develop/tests/events) from powertools python so we can test our schema against the same examples. 

This feature only provides the built in schemas which we will use later for envelope parsing in decorators and middleware. 

This should include:

* ALB
* API GW
* API GW v2
* CFN custom resource
* CloudWatch
* DynamoDB
* EventBridge
* Kafka
* Kinesis
* Kinesis Firehose
* Kinesis Firehose SQS
* Lambda function URL
* S3
* S3 event notification
* S3 object event
* SES
* SNS
* SQS
* VPC lattice
* VPC lattice v2

### Solution/User Experience

The schemas should be in a dedicated folder with no index export, so each schema can be imported individually. 

```ts
import { EventBridgeSchema } from '@aws-lambda-powertools/parser/schemas/eventbridge';
```

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
This is now released under [v2.1.0](https://github.com/aws-powertools/powertools-lambda-typescript/releases/tag/v2.1.0) version!
