### ISSUE TITLE
Feature request: implement schema envelopes

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#1791]
### Use case

Similar to the [python implementation](https://github.com/aws-powertools/powertools-lambda-python/tree/develop/aws_lambda_powertools/utilities/parser/envelopes) we want to have reusable envelopes that we can extend with custom schema. 

### Solution/User Experience

Envelopes encapsulate the provided custom model in a built-in schema. This means that they parse specific part of the event `detail` for EventBridge or `body` for SQS. 

```ts
const eventBridgeEnvelope = (<T extends ZodSchema>(data: unknown, schema: T) => {
  return schema.parse(EventBridgeSchema.parse(data).detail);
});
```

This will allow us to bring your own custom schema: 

```ts
const customSchema = z.object({
  foo: z.string()
})

type CustomSchema = z.infer<typeof customSchema>;

const customEventBridgeEvent: CustomSchema = eventBridgeEnvelope({foo: 'bar'}, customSchema);

```

While is a one line, it'd be great to provide a bit more debug logs around both calls. It's worth emphasise that envelopes do not return schemas, but the parsed object of the custom schema. 

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
This is now released under [v2.1.0](https://github.com/aws-powertools/powertools-lambda-typescript/releases/tag/v2.1.0) version!
