### ISSUE TITLE
Docs: write main docs for parser

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#1796]
### What were you searching in the docs?

The documentation should include a section dedicated to the upcoming parser utility.

### How can we improve?

```Markdown
N/A
```

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by dreamorosi** [comment]
This is now released under [v2.1.0](https://github.com/aws-powertools/powertools-lambda-typescript/releases/tag/v2.1.0) version!
