### ISSUE TITLE
Maintenance: Cyborg GitHub App having broken link

### ISSUE THREAD

**Issue by daschaa** [aws-powertools/powertools-lambda-typescript#1806]
### Expected Behaviour

The boring-cyborg GitHub app has a valid link to the contributing guide.

### Current Behaviour

The link provided by the boring cyborg app is not working

### Code snippet

-

### Steps to Reproduce

Create a new PR

### Possible Solution

Change the link in in the configuration

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

20.x

### Packaging format used

npm

**Comment by dreamorosi** [comment]
Hi @daschaa - thank you for opening the issue, and good spot.

I see you've already opened a PR to fix it, which is great, thank you!
