### ISSUE TITLE
Feature request: Utility to get Lambda version

### ISSUE THREAD

**Issue by perpil** [aws-powertools/powertools-lambda-typescript#1811]
### Use case

Publishing lambda version as a dimension is a best practice for comparing metrics between deployments.  In David Yanacek's re:invent talk on observability [COP343](https://youtu.be/MARiKxvrdmc?si=ymKO4axvB4EF4sqY&t=1579), he discusses using version to quickly detect problems with a deployment and rollback.  There are a couple of ways to do this, but one of the cleaner and simpler ways of doing this is to:

1. Use [Lambda Aliases](https://docs.aws.amazon.com/lambda/latest/dg/configuration-aliases.html) and point API Gateway at the Alias.
2. In your Lambda, parse version from the `AWS_LAMBDA_LOG_STREAM_NAME` environment variable
3. Emit version as a metric dimension

PowerTools could help with a utility function to get function version just like it has a utility function to extract xray trace id from the `_X_AMZN_TRACE_ID` environment variable.  It would make this more accessible because developers wouldn't need to keep writing this code themselves.

This isn't the most robust implementation but this is how I am extracting Lambda version from the log stream:

```javascript
const VERSION = /\[(.*?)\]/.exec(
  process.env.AWS_LAMBDA_LOG_STREAM_NAME || '[local]'
)[1];
```

**Note** If you don't use aliases, the version is set to `$LATEST` which isn't that useful, but it is still present in the log stream name.

### Solution/User Experience

1. Provide a utility function i.e. `getLambdaVersion()` to extract the lambda version from the log stream name.
2. Add environment variables like POWERTOOLS_EMIT_LAMBDA_VERSION_DIMENSION and POWERTOOLS_EMIT_LAMBDA_VERSION_METADATA to enable you to automatically add `version` dimension when you emit metrics and/or as metadata.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by ceberttylertech** [comment]
Is there a way to determine which issues have been approved by the lambda power tools maintainers to be actioned on? This sounds like a reasonably straightforward enhancement.

**Comment by am29d** [comment]
Hi @perpil , thanks for raising the request.

Having deployment information in the metrics indeed helps with faster auto rollbacks. You can already get this information from the Lambda `context` variable, here is an example from my test

```
functionVersion: '1',
  functionName: 'test',
  memoryLimitInMB: '128',
  logGroupName: '/aws/lambda/test',
  logStreamName: '2023/12/07/[1]e411d8bd60f1494f8cf14364b065c31a',
  clientContext: undefined,
  identity: undefined,
  invokedFunctionArn: 'arn:aws:lambda:eu-west-1:12345679012:function:test:v1_17_1',
```

As you can see you have `functionVersion` and with quick slice of `invokedFunctionArn` you can fetch the alias as a last part of the split. 

I do see the value to automatically get this information and inject into metrics and I'd like to hear more customer feedback and voice by adding 👍🏻 . There are some edge cases when customer don't use versions or have a custom log stream name, so we'd need to decide how to deal with them.  


@ceberttylertech we use labels as triage, confirmed, backlog to indicate the status of the issue. If you want to have on overview of the project you can see the public project board here: https://github.com/orgs/aws-powertools/projects/7/views/3. 

In addition, we have a [Roadmap](https://docs.powertools.aws.dev/lambda/typescript/latest/roadmap/) section in or documentation. 

If you feel there is missing information or we can add or improve communication, please let me know. We do our best to provide clarity and transparency for you.

**Comment by perpil** [comment]
TIL! I don't know how I missed that, it's available as an environment variable too: `AWS_LAMBDA_FUNCTION_VERSION` 
I checked the wayback machine, it's not new at all 😄.

>I do see the value to automatically get this information and inject into metrics and I'd like to hear more customer feedback and voice by adding 👍🏻. There are some edge cases when customer don't use versions or have a custom log stream name, so we'd need to decide how to deal with them.

If they are not using a version it would be set to $LATEST. Although I believe version is always part of logStreamName regardless of whether you have a custom stream, I don't think this matters now that we're aware of `AWS_LAMBDA_FUNCTION_VERSION`.

The utility function to extract version doesn't make as much sense now, but still might be nice to have a configuration option to automatically emit version as a dimension.  Since alias can change the version it is pointing to, it's less useful as a dimension and more useful as metadata.

**Comment by am29d** [comment]
Looking at the broader solution to pass deployment information to a metric, you could add software version to the environment variable which would allow a more robust metric for the alarms.

**Comment by perpil** [comment]
I'm not sure I follow, are you suggesting the broader solution would be I set a variable like `POWERTOOLS_SOFTWARE_VERSION_DIMENSION` to the hash of my code and Powertools would automatically add it as a dimension to all metrics?  If that's the case, maybe having an optional config entry in the metrics config to emit a version dimension that you can either specify the environment variable or set it to `true`.  If `true` it would use `AWS_LAMBDA_FUNCTION_VERSION`.  By default it would not be set.

**Comment by am29d** [comment]
Using Lambda version you already have a default metrics created by Lambda service in your CloudWatch that collects errors, so you can create alarms for that without using Powertools

In my previous comment I was rather exploring other ways to 1/ get app code identifier and 2/ publish a metric for an alarm. While we don't have an automatic functionality to capture that, we do have tools in place to achieve it in one way or another.

Assuming we have an environment variable for our function that would indicate the version of our app, let's call it APP_VERSION. We can inject this information into [default dimensions](https://docs.powertools.aws.dev/lambda/typescript/latest/core/metrics/#adding-default-dimensions):

```ts
import { Metrics, MetricUnits } from '@aws-lambda-powertools/metrics';

const APP_VERSION = process.env.APP_VERSION || '0.0.0';

const metrics = new Metrics({
  namespace: 'serverlessAirline',
  serviceName: 'orders',
  defaultDimensions: { environment: 'prod', appVersion: APP_VERSION },
});

export const handler = async (event) => {
  try { 
    // Your code   
  } catch (e) {
    metrics.addMetric('Error', MetricUnits.Count, 1);
    throw e;
  } finally {
    metrics.publishStoredMetrics();
  } 
};
```

This will collect error metrics for you including your app version. Based on that you can create alarm for a rollback. The DX could be improved so you don't have to capture error metrics manually, but we do rely on `publishStoredMetrics` called by the user (except for middy or decorator). 

Another approach would be to add  `persistentLogAttributes` to the logger. This will inject custom information into every log statement. As mentioned in the breakout session you have linked, you can create metrics from structured logs using [metrics filter](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/MonitoringLogData.html). I have never used it before and will give a deep dive later to create a working example with structured logs, metrics, alarms and rollbacks.

**Comment by dreamorosi** [comment]
As I understand from the discussion above, there's an existing alternative in the environment variables that can be used with default dimensions.

Closing the issue for now, but in case this is inaccurate please leave a comment, or open a new issue if the scope has changed.

Thanks again for using the project and being involved :)
