### ISSUE TITLE
Feature request: implement parser decorator

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#1816]
### Use case

Similar to middy middleware we want to use build-in schemas and envelopes to parse and extract events using decorators. 

### Solution/User Experience

Based on the RFC the decorator should take model and envelope as an param object:

```ts
const order = z.object({
  id: z.number(),
  description: z.string(),
});

type Order = z.infer<typeof order>;

class Lambda implements LambdaInterface {
  // Decorate your handler class method
  @logger.injectLambdaContext()
  @parser({eventBridgeEnvelope, order})
  public async handler(
    _event: OrderModel,
    _context: Context
  ): Promise<void> {
    logger.info(`Received order model ${_event}`);
  }
}
```

we should also be able to pass only the model, which can be a custom event or an extension of the built-in schema i.e. 

```ts
const order = z.object({
  id: z.number(),
  description: z.string(),
});

const customEBschema = EventBridgeSchema.extend({
  detail: order,
});
```

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
This is now released under [v2.1.0](https://github.com/aws-powertools/powertools-lambda-typescript/releases/tag/v2.1.0) version!
