### ISSUE TITLE
[Support Lambda Powertools]: AppYourself

### ISSUE THREAD

**Issue by kornicameister** [aws-powertools/powertools-lambda-typescript#1820]
### Organization Name

AppYourself

### Your Name

AppYourself

### Your current position

Senior backend developer

### (Optional) Company logo

https://appyourself.net/wp-content/uploads/2022/07/alpha-logo.svg

### (Optional) Use case

AppYourself provides a platform that allows customers to easily create and publish apps that boost their business.
Doing that is already hard enough but doing that without Powertools boosting development, observability and code-wise aspects of Lambda functions fueling all business logic would be even harder.

### Also using other Powertools for AWS Lambda languages?

- [ ] Python
- [ ] Java
- [ ] .NET

**Comment by dreamorosi** [comment]
Hi @kornicameister, thank you so much for opening the issue and adding AppYourself as a public reference to Powertools!

We'll be adding the name on the documentation shortly.
