### ISSUE TITLE
Feature request: Add Canada - Calgary region to the Lambda Layers Deployment

### ISSUE THREAD

**Issue by leandrodamascena** [aws-powertools/powertools-lambda-typescript#1828]
### Use case

AWS recently launched new region:

Canada (Calgary) - ca-west-1

https://aws.amazon.com/blogs/aws/the-aws-canada-west-calgary-region-is-now-available/

This region doesn't support arm64.

### Solution/User Experience

Deploy Lambda Layers to this new region.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
The Lambda Layer is available in this region as of version 1.8.0, which corresponds to version 28 of the Layer. For the full ARN please refer to the docs.
