### ISSUE TITLE
Feature request: add types for built-in schemas and envelopes 

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#1837]
### Use case

When using zod schema we can extract type from the schema: 

```typescript
import { z } from 'zod';

const orderSchema = z.object({
  id: z.number().positive(),
  description: z.string(),
  items: z.array(orderItemSchema),
});

type Order = z.infer<typeof orderSchema>; 
```

We have created built-in schemas and envelopes but we did not extracted this types into dedicated package. If users want to use the types from the schema they need to write `z.infer` statement themselves. We can improve the experience by creating this types. 

### Solution/User Experience

Write a types file with alle the schema and envelopes types using `z.infer`

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
This is now released under [v2.1.0](https://github.com/aws-powertools/powertools-lambda-typescript/releases/tag/v2.1.0) version!
