### ISSUE TITLE
Maintenance: fine tune Dependabot configuration

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#1858]
### Summary

We have added Dependabot recently with a broad configuration. We now need to fine tune the dependencies that require an exception or have a specific case, i.e. no upgrade, only major/minor versions. The knowledge about this dependencies was not documented previously. 

### Why is this needed?

This is needed to document dependency management exceptions, what is pinned what can be upgraded. This will also scope down dependabot for the project specific updates and upgrades.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by heitorlessa** [comment]
Quick example for groups to fine tune dependencies you don't want major versions, or want to explicitly ignore like middy.

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore

**Comment by dreamorosi** [comment]
On the top of my head, I think:
- middy should be locked to minor version in the current major only
- all AWS CDK related dependencies (including alpha packages and CLI) in testing, layers, examples/cdk, etc. should be grouped
- all AWS SDK related dependencies, together with the AWS SDK mock ones (in idempotency and parameters) should be grouped together

For all other dev dependencies, and specifically the ones in the main package.json file, we'll have to be careful especially in those cases where major versions have dropped support for Node.js versions that we still must support (Node.js 16 mainly).

Overall however, except for the CDK related ones, most issues version issues should be caught in the PR CI, so this is a good change.

**Comment by heitorlessa** [comment]
enjoy PTO Andrea!!
