### ISSUE TITLE
Maintenance: fix invalid Github Codespace config

### ISSUE THREAD

**Issue by Cupprum** [aws-powertools/powertools-lambda-typescript#1914]
### Expected Behaviour

When i create a new codespece from my forked repository i expect it to return a custom container used for development of this specific project with all predefined dependencies.

### Current Behaviour

The container creation fails:
`ERROR: failed to solve: dockerfile parse error on line 9: unknown instruction: &&`

### Code snippet

Create codespace

### Steps to Reproduce

Create codespace
See it fail

### Possible Solution

I am happy to contribute, i have time to debug this issue and propose a PR. I might need some guidance about the PR process.

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

20.x

### Packaging format used

Lambda Layers

**Comment by am29d** [comment]
Hey @Cupprum , thanks for raising the issue the line 9 is indeed weird. I will fix the docker image right away.
