### ISSUE TITLE
Maintenance: evaluate `biome` for linting and format 

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1973]
### Summary

As of now the project uses a combination of `eslint` and `prettier` to lint and format code.

This works well enough, however there are newer alternatives like [biome](https://biomejs.dev) that boast high compatibility with our current tools ([97%](https://console.algora.io/challenges/prettier)) and could allow us to handle both tasks with a single tool/dependency.

This issue tracks the efforts to test the tool on our repo, configure it in a way that causes the least amount of disruption, and potentially adopt it.

---

Edit:

To split the work and ease review, I'll break down the migration in a series of issues/PRs:
- #2790
- #2802
- #2797
- #2793
- #2794
- #2795
- #2799
- #2796
- #2803
- #2801
- #2798
- #2801
- #2792

### Why is this needed?

The main driver behind this issue is reducing maintainer fatigue. The combination of those two tools requires 9 dev dependencies which need to be kept up to date (Dependabot spam) and understood.

Additionally, there might be a chance to improve performance in our CI by both reducing the time for these operations (probably marginal at our repo size) as well as the time to set up the CI environment due to having less dependencies to fetch & install.

### Which area does this relate to?

Automation

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
After some initial tests, which were promising, I found at least one rule we use extensively that is not supported by biome: `typescript-eslint/explicit-function-return-type`.

I requested the feature, which was [added to the backlog](https://github.com/biomejs/biome/issues/2017), and I am now looking at options to help with prioritization.

**Comment by RayanMoarkech** [comment]
+1 for explicit-function-return-type
