### ISSUE TITLE
[Support Powertools for AWS Lambda (TypeScript)]: Alma Media

### ISSUE THREAD

**Issue by aripalo** [aws-powertools/powertools-lambda-typescript#2020]
### Organization Name

Alma Media

### Your Name

Ari Palo

### Your current position

Lead Technologist

### (Optional) Company logo

https://www.almamedia.fi/wp-content/themes/almamedia/dist/images/main-logo.svg

### (Optional) Use case

Alma Media has been heavily utilizing AWS Serverless technologies since 2016 with AWS Lambda at its core. Powertools have greatly simplified how our developers are able to instrument observability and implement best practices into the services they build. As of today (February 2024), over ~~70~~ 40 different projects – a number that keeps growing – depend on AWS Powertools.

(* corrected a wrong number of projects 😅 see https://github.com/aws-powertools/powertools-lambda-typescript/issues/2020#issuecomment-1927415415 )

### Also using other Powertools for AWS Lambda languages?

- [X] Python
- [ ] Java
- [ ] .NET

**Comment by am29d** [comment]
Hey @aripalo thank you so much for adding your support, it means a lot! 

I will add it to the docs right away!

**Comment by aripalo** [comment]
Happy to help spreading the word!

**Comment by aripalo** [comment]
Oops… I may have accidentally inflated those numbers 😅 I counted some of the lock-files referencing powertools into the mix, but the actual number is about 40! But still quite a lot.

**Comment by am29d** [comment]
> Oops… I accidentally inflated those numbers 😅 I counted some of the lock-files referencing powertools into the mix, but the actual number is about `40`! But still quite a lot.

This number is from the future 😎

**Comment by aripalo** [comment]
Yeah 😎 And to be honest, at this rate, not from too far future either. Pretty much all new serverless projects are using Powertools by default and I constantly see PRs adding Powertools to existing projects.
