### ISSUE TITLE
Bug: AWS AppConfigProvider error, unable to retrieve feature flags after some time

### ISSUE THREAD

**Issue by daniel-gasparik** [aws-powertools/powertools-lambda-typescript#2136]
### Expected Behaviour

 I think this should be handled by the lib internally and looking at its source code it does but the token is still invalid after some time.

### Current Behaviour

I am facing an issue with calling the AWS AppConfig provide to get some feature flags, according to the docs, the token expires after up to 24hrs. This requires me to restart the service each time it expires which is not ideal.  I m running this in an EC2 container utilising the Nestjs framework

### Code snippet

```typescript
import { AppConfigProvider } from '@aws-lambda-powertools/parameters/appconfig';
import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

import { Config } from 'src/config/types/interfaces';
import { FeatureFlagList } from './types/interfaces';

export const APP_CONFIG_MAX_AGE_SECONDS = 60 * 5; // 5 minutes

@Injectable()
export class FeatureFlagService {
  private readonly configProvider: AppConfigProvider;
  private readonly logger = new Logger(FeatureFlagService.name);

  constructor(private readonly configService: ConfigService<Config, true>) {
    this.configProvider = new AppConfigProvider({
      // clientConfig: { logger: this.logger },
      application: this.configService.get('aws.appConfig.appName', {
        infer: true,
      }),
      environment: this.configService.get('aws.appConfig.envName', {
        infer: true,
      }),
    });
  }


  public async getConfig(): Promise<FeatureFlagList> {
    let config: FeatureFlagList;
    try {
      config = (await this.configProvider.get(
        this.configService.get('aws.appConfig.profileName', { infer: true }),
        { maxAge: APP_CONFIG_MAX_AGE_SECONDS, transform: 'json' },
      )) as unknown as FeatureFlagList;
    } catch (error) {
      this.logger.error('featureFlagService.getConfig', { err: error });
      config = {
        chat: { enabled: false },
      };
    }

    return config;
  }
}


```

### Steps to Reproduce

1. Build base image with node:19.0.1
2. Run with node:19.0.1-alpine
3. Let it serve on EC2 task
4. After (not sure if exactly) 24 hours we get the token error

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

20.x

### Packaging format used

npm

### Execution logs

```Shell
Stacktrace error

{"level":"error","time":1708266970318,"pid":1,"hostname":"f281cd3e9f1e","err":{"type":"GetParameterError","message":"Token not valid","stack":"GetParameterError: Token not valid\n at AppConfigProvider.get (/usr/src/app/node_modules/.pnpm/@aws-lambda-powertools+parameters@1.17.0_@aws-sdk+client-appconfigdata@3.484.0/node_modules/@aws-lambda-powertools/parameters/lib/base/BaseProvider.js:92:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async FeatureFlagService.getConfig (/usr/src/app/dist/src/api/configuration/feature-flag.service.js:38:23)\n at async ConfigurationController.getFeatureFlags (/usr/src/app/dist/src/api/configuration/configuration.controller.js:26:50)","name":"GetParameterError"},"msg":"featureFlagService.getConfig"}
```
```

**Comment by dreamorosi** [comment]
Hi, thank you for opening this issue.

Could you please confirm which version of Powertools are you using? In the issue you've selected `latest` but the execution log you have shared below seems to show you're using version `1.17.0`.

In version 1.18.0 we have [released a fix](https://github.com/aws-powertools/powertools-lambda-typescript/releases/tag/v1.18.0) for this issue, so before trying to reproduce on our side I'd like to confirm your version.

If possible, could you please try to upgrade to version 1.18.0 or newer and check if you're still observing this behavior?
