### ISSUE TITLE
Bug: importing `Tracer` from powertools v2 causes `SyntaxError`

### ISSUE THREAD

**Issue by webdeveric** [aws-powertools/powertools-lambda-typescript#2163]
### Expected Behaviour

No error thrown

### Current Behaviour

When running my ESM Lambda's locally, just importing `Tracer` will cause the following error any time I hit one of my routes.

```
Runtime.UserCodeSyntaxError: SyntaxError: The requested module 'aws-xray-sdk-core' does not provide an export named 'Segment'
```

### Code snippet

It looks like the issue is how `Segment` and/or `Subsegment` are being imported from `aws-xray-sdk-core` in the transpiled js code.

```shell
node -e "import { Tracer } from '@aws-lambda-powertools/tracer';" --input-type=module 
```

### Steps to Reproduce

Create `tracer.mjs` and put this in it.

```js
import { Tracer } from '@aws-lambda-powertools/tracer';
```

Run `node tracer.mjs`

You should see something like this:

```shell
[...]node_modules/@aws-lambda-powertools/tracer/lib/esm/provider/ProviderService.js:1
import { captureAWS, captureAWSClient, captureAWSv3Client, captureAsyncFunc, captureFunc, captureHTTPsGlobal, getNamespace, getSegment, setSegment, Segment, setContextMissingStrategy, setDaemonAddress, setLogger, } from 'aws-xray-sdk-core';
                                                                                                                                                    ^^^^^^^
SyntaxError: Named export 'Segment' not found. The requested module 'aws-xray-sdk-core' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'aws-xray-sdk-core';
const { captureAWS, captureAWSClient, captureAWSv3Client, captureAsyncFunc, captureFunc, captureHTTPsGlobal, getNamespace, getSegment, setSegment, Segment, setContextMissingStrategy, setDaemonAddress, setLogger, } = pkg;
```

### Possible Solution

```js
import pkg from 'aws-xray-sdk-core';
const { Segment } = pkg;
```

### Powertools for AWS Lambda (TypeScript) version

2.0.1

### AWS Lambda function runtime

20.x

### Packaging format used

npm

**Comment by dreamorosi** [comment]
The PR with the fix is up and ready for review, within the next ~8hrs the next maintainer should come online and be able to review it.

Once that's done we'll be able to make a release with the fix. Thanks for your patience and apologies for the inconvenience.
