### ISSUE TITLE
Maintenance: add subpath exports to package.json

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#2177]
### Summary

We currently don't export subpaths for `envelopes`, `schemas` and `types` in our `package.json`, and we should add them, so customers can import them.

### Why is this needed?

So customers can granularly import schemas and envelopes following the same standard that we have introduced with in v2.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
This is now released under [v2.1.0](https://github.com/aws-powertools/powertools-lambda-typescript/releases/tag/v2.1.0) version!
