### ISSUE TITLE
Docs: Describe removing `ContextExamples` in the migration doc

### ISSUE THREAD

**Issue by yamatatsu** [aws-powertools/powertools-lambda-typescript#2195]
### What were you searching in the docs?

In v1, `@aws-lambda-powertools/commons` had `ContextExamples` that helped our test coding.
It was written in v1 docs. See https://docs.powertools.aws.dev/lambda/typescript/1.18.1/core/logger/#inject-lambda-context.

It seems to be moved to `packages/testing`.

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/typescript/2.0.1/upgrade/

### How can we improve?

```Markdown
This breaking change is better to be described in migration docs I think.
```

### Got a suggestion in mind?

Adding new row to the table;
```md
| **Common**            | Removed `ContextExamples` and `Events` that is objects used for testing.                                                       | Yes                  |
```

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by am29d** [comment]
Hey @yamatatsu 

thanks for opening the issue and すみません for removing the dependency you have used, we completely missed this point. 

We have moved the tests resources to internal package, so you'd need to create your own context object. This is nothing too complex and you can [copy it from our code](https://github.com/aws-powertools/powertools-lambda-typescript/blob/df9c7e27764744490fa4d1c2c453f3b4c4ed7d55/packages/testing/src/context.ts#L3). 

I will update the docs to reflect this change for the future, thanks again for letting us know.
