### ISSUE TITLE
Docs: Idempotency docs say only Middy v3.x is supported

### ISSUE THREAD

**Issue by buggy** [aws-powertools/powertools-lambda-typescript#2300]
### What were you searching in the docs?

I was reading the whole Powertools for AWS Lambda (Typescript) docs.

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/typescript/latest/utilities/idempotency/#makehandleridempotent-middy-middleware

### How can we improve?

```Markdown
Immediately below the heading "MakeHandlerIdempotent Middy middleware" there is a "A note about Middy" which says that only v3.x is support. Other parts of the documentation say v4.x
```

### Got a suggestion in mind?

Change v3.x to v4.x

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by am29d** [comment]
Hey @buggy , thanks for dropping the issue that we have missed during the upgrade to v2. Dropping the fix asap.

**Comment by am29d** [comment]
Found additional inconsistencies:

* https://github.com/aws-powertools/powertools-lambda-typescript/blob/bf0aa4b5dbe04c1187b413cd7e0cba33852ad81f/docs/index.md?plain=1#L267
* https://github.com/aws-powertools/powertools-lambda-typescript/blob/bf0aa4b5dbe04c1187b413cd7e0cba33852ad81f/docs/core/metrics.md?plain=1#L203
