### ISSUE TITLE
Maintenance: refactor `lint-staged` configuration

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#2312]
### Summary

We use [`lint-staged`](https://github.com/lint-staged/lint-staged) to lint and format changed files before they're committed. There are some improvements to the setup/configurations that can be made and this issue tracks them.

For example:
- Currently we specify a `lint-staged` section in each `package.json` file in the monorepo, this is redundant. We should move up all the configuration in the main `package.json` at the root of the project.
- Currently the `lint-staged` command calls a `lint-fix` command present in each package, however this command specifies a `.` argument, which causes all files to be processed rather than only the ones that changed and that are passed as `stdin` to the command

### Why is this needed?

So that the process runs only on files that actually changed and the configuration is centralized.

### Which area does this relate to?

Automation

### Solution

There are at least two concrete actions to be taken in this issue:
1. Gather all the `lint-staged` sections in all the `package.json` files ([example](https://github.com/aws-powertools/powertools-lambda-typescript/blob/8fed55b552e8ee098163bfcd7d89c535448fc1d0/packages/commons/package.json#L26-L29)) and move them to the main `package.json` file ([this one](https://github.com/aws-powertools/powertools-lambda-typescript/blob/8fed55b552e8ee098163bfcd7d89c535448fc1d0/package.json)) in an aggregated way
2. Replace the current command associated with the `*.{js,ts}` extension with just `eslint --fix`. This will work because `lint-staged` already passes the files that were changed as `stdin`

The change above, specifically number 1, will also have the effect of making the process run only once per commit rather than  once for each package having had changes (aka `O(1)` vs `O(n)`).

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by daschaa** [comment]
I took this issue 😇
