### ISSUE TITLE
Feature request: add custom ParseError object to wrap ZodErrors

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#2317]
### Use case

We throw generic `Error` when the body inside envelope is invalid or forward `ZodError` when there is an issue with a schema. We should convert the generic error to be more specific and also wrap any `ZodError`. This would allow us to control any changes from Zod library and potentially add more context

### Solution/User Experience

Create `ParseError` to throw either error specific to envelopes or schemas.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
This is now released under [v2.1.0](https://github.com/aws-powertools/powertools-lambda-typescript/releases/tag/v2.1.0) version!
