### ISSUE TITLE
Maintenance: add v2 layer to AWS Lambda console

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#2340]
### Summary

We need to add the new v2 layer to AWS Lambda console. 

### Why is this needed?

So customers can use the new v2 version layer in the console.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
The layers are available in the console:

![Screenshot 2024-05-14 at 16 41 57](https://github.com/aws-powertools/powertools-lambda-typescript/assets/7353869/1a8dbf73-b6ad-4b62-a81b-104fc2d3a21d)
