### ISSUE TITLE
Maintenance: adopt AppConfig L2 constructs in Parameters integration tests

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#2396]
### Summary

AWS CDK has added [L2 constructs for AWS AppConfig](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_appconfig-readme.html) that allow to create AppConfig resources more easily.

The AppConfig Provider part of the Parameters utility uses L1 constructs that are more verbose and require explicit management of dependencies between entities.

We should replace the existing construct with the newer.

### Why is this needed?

So that the integration tests for the Parameters utility can become a little less verbose and less brittle.

### Which area does this relate to?

Tests

### Solution

Replace the code [found here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/2a69d41157a3c51055f1e2a30a95650c4500d5d1/packages/parameters/tests/helpers/resources.ts#L243-L311) with the L2 constructs.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by daschaa** [comment]
I would like to take this issue ❤️
