### ISSUE TITLE
Maintenance: mark `captureAWS` and `captureAWSClient` methods as deprecated in Tracer

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#2397]
### Summary

In March 2024, AWS announced that AWS SDK for JavaScript v2 will reach end-of-support in September 8, 2025. Additionally, the SDK has added warning logs to communicate the deprecation and encourage a migration to the newer AWS SDK for JavaScript v3.

In response to this announcement we should mark the Tracer methods used to instrument clients for this version, so that 

### Why is this needed?

So that Powertools customers relying on this feature have ample time to migrate from the method to and use the alternative `captureAWSv3Client`.

### Which area does this relate to?

Tracer

### Solution

Add a `@deprecated` notice on the methods found .

For example:
```diff
/**
 * Patch all AWS SDK v2 clients and create traces when your application makes calls to AWS services.
 *
 * If you want to patch a specific client use {@link captureAWSClient} and if you are using AWS SDK v3 use {@link captureAWSv3Client} instead.
 *
 * @see https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-nodejs-awssdkclients.html
 *
 * @example
 * ```typescript
 * import { Tracer } from '@aws-lambda-powertools/tracer';
 *
 * const tracer = new Tracer({ serviceName: 'serverlessAirline' });
 * const AWS = tracer.captureAWS(require('aws-sdk'));
 *
 * export const handler = async (_event: unknown, _context: unknown) => {
 *   ...
 * }
 * ```
 *
+ * @deprecated Use {@link captureAWSv3Client} instead.
 *
 * @param aws - AWS SDK v2 import
 * @returns AWS - Instrumented AWS SDK
 */
 public captureAWS<T>(aws: T): T {
   if (!this.isTracingEnabled()) return aws;

   return this.provider.captureAWS(aws);
 }
```

Additionally, we should also do the same and mark the ones [here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/2a69d41157a3c51055f1e2a30a95650c4500d5d1/packages/tracer/src/provider/ProviderService.ts#L34-L36) and [here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/packages/tracer/src/provider/ProviderService.ts#L38-L40), like this:

```diff
 /**
 * Patch all AWS SDK v2 clients and create traces when your application makes calls to AWS services.
 *
+ * @deprecated
 *
 * @param awssdk - AWS SDK v2
 */
  public captureAWS<T>(awssdk: T): T {
   return captureAWS(awssdk);
 }
```

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by arnabrahman** [comment]
Sorry, I saw no assignees for this issue and just went ahead with the PR. @dreamorosi

**Comment by dreamorosi** [comment]
Hi @arnabrahman, nice to see you again! It's all good, thank you for taking this issue and submitting a PR!

Tomorrow morning I'll review it and get it merged 😊
