### ISSUE TITLE
Feature request: allow parser set event type of handler with middy

### ISSUE THREAD

**Issue by yamatatsu** [aws-powertools/powertools-lambda-typescript#2407]
### Use case

middy can pass event type like as [this](https://middy.js.org/docs/intro/typescript/). So we can pass inferred event type from zod schema to handler.

### Solution/User Experience

```ts
const detailSchema = z.object({
	date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
	message: z.string(),
});

export const handler = middy()
	// when using parser
	.use(parser({ schema: detailSchema, envelope: EventBridgeEnvelope }))
	// handler will get event type already inferred without type annotation.
	.handler(async (event) => {
		logger.inf(event.detail.message)
	});
```

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by am29d** [comment]
Hey @yamatatsu, thanks for raising the issue. In your example, I think you missed the types in the `middy()` call. Can you modify the solution code block to reflect that? In the meantime, I will investigate how we could add event types to middy call.
