### ISSUE TITLE
Maintenance: revamp issue & PR templates

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#2411]
### Summary

This issue captures two tasks that are somewhat related in that they impact how contributors and maintainers interact with the repository.

The current PR template has room for improvements. GitHub doesn't support forms for Pull Requests, so the editing experience is not great and the current template is overly verbose as evidenced by the fact that most of the time it doesn't get filled completely.

Finally, while the issue templates are in a good state, they could use some updates (see "Solution") section below.

### Why is this needed?

So that the issue and PR creation is more streamlined, while keeping the same level of info for maintainers.

### Which area does this relate to?

Governance

### Solution

Proposed PR template:

```markdown
## Summary

### Changes

> Please provide a summary of what's being changed

<!-- What is this PR solving? Write a clear description or reference the issue(s) it addresses. -->

> Please add the issue number below, if no issue is present the PR might get blocked and not be reviewed

**Issue number:** 

<!-------
Before creating the pull request, please make sure you do the following:

- Read the Contributing Guidelines at https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/CONTRIBUTING.md#sending-a-pull-request
- Check that there isn't already a PR that addresses the same issue. If you find a duplicate, please leave a comment under the existing PR so we can discuss how to move forward
- Check that the change meets the project's tenets https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets
- Add a PR title that follows the conventional commit semantics - https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/.github/semantic.yml#L2
- If relevant, add tests that prove that the change is effective and works
- Whenever relevant, make sure to comment functions/methods/types and make appropriate changes to the documentation
------->

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.
```

Regarding the issue templates, there's a number of changes that could be made. Some of these are:
- update the dropdown areas to include all current utilities and ones on roadmap
- check fields types so that they're rendered correctly, for example docs improvement [uses a markdown](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/.github/ISSUE_TEMPLATE/documentation_improvements.yml?plain=1#L30) type, while it should be a text 

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by am29d** [comment]
I agree on the issue and PR templates. I am wondering if we should extend the PR template changes across all languages, to have the same experience.

**Comment by dreamorosi** [comment]
I think we can bring it up to them, this has pretty much the same format as the Python repo except they have the issue number at the very top, and a couple of the bullet points are worded differently.
