### ISSUE TITLE
Maintenance: Update roadmap April

### ISSUE THREAD

**Issue by heitorlessa** [aws-powertools/powertools-lambda-typescript#2416]
### Summary

Update roadmap for April

### Why is this needed?

Roadmap is out of date

### Which area does this relate to?

Governance

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by heitorlessa** [comment]
@dreamorosi  @am29d - I've tried creating an automated report and noticed `feature-request` label used in other languages is named `type/feature-request` in TS -- can I get your help to rename it, please?

**Comment by dreamorosi** [comment]
Yes, all the labels we use are scoped, I set them up like this over a year ago to be a bit more informative, like:
- what's the type of issue: `feature-request`, `bug`, `internal`, etc.
- what's the area: `logger`, `tracer`, etc
- what's the status: `pending-release`, `complete`, etc.

I did this when we created the public project and I manually went through all the existing GH issues & PRs, including closed ones, to apply the new conventions.

Is there any chance that we can extend the report automation to take in account a map/dictionary that lets the repo set their own labels? The action would be centralized, but when running it can load a file at `.github/labels.yml` that contains a mapping.

What do you think?

If it's too much work, or we have a need to align the labels among projects (understandable), I'll set aside a couple of hours today and change all the labels back.
