### ISSUE TITLE
Bug: LambdaFunctionUrlSchema fails with CloudFront Origin Access Control (OAC)

### ISSUE THREAD

**Issue by aripalo** [aws-powertools/powertools-lambda-typescript#2427]
### Expected Behaviour

Using `.use(parser({ schema: LambdaFunctionUrlSchema }))` middleware should work with Lambda Function URLs protected by [the newly launched CloudFront OACs](https://aws.amazon.com/about-aws/whats-new/2024/04/amazon-cloudfront-oac-lambda-function-url-origins/).

### Current Behaviour

The parser throws an error:
```
Failed to parse schema. This error was caused by: [
  
{
    "code": "invalid_type",
    "expected": "string",
    "received": "null",
    "path": [
        "requestContext",
        "authorizer",
        "iam",
        "principalOrgId"
    ],
    "message": "Expected string, received null"
}
,
  
{
    "code": "invalid_type",
    "expected": "object",
    "received": "null",
    "path": [
        "requestContext",
        "authorizer",
        "iam",
        "cognitoIdentity"
    ],
    "message": "Expected object, received null"
}
```

This is because when CloudFront OAC is calling the Lambda Function URL, the [`principalOrgId`](https://github.com/aws-powertools/powertools-lambda-typescript/blob/744fad76bb7bad96799506981a63d3c59f5a93e2/packages/parser/src/schemas/apigwv2.ts#L16) and [`cognitoIdentity`](https://github.com/aws-powertools/powertools-lambda-typescript/blob/744fad76bb7bad96799506981a63d3c59f5a93e2/packages/parser/src/schemas/apigwv2.ts#L19C7-L23) are actual set to `null`:
```js
// some sensitive'ish values replaced with fictional values
"requestContext": {
            "accountId": "123456789012",
            "apiId": "abcd1",
            "authorizer": {
                "iam": {
                    "accessKey": "ASIA123EXAMPLE",
                    "accountId": "123456789012",
                    "callerId": "AROA123EXAMPLE:OriginAccessSession",
/* NOTICE NULL → */ "cognitoIdentity": null, 
/* NOTICE NULL → */ "principalOrgId": null,  
                    "userArn": "arn:aws:sts::123456789012:assumed-role/OriginAccessControlRole/OriginAccessSession",
                    "userId": "AROA123EXAMPLE:OriginAccessSession"
                }
            },
```

### Code snippet

`.use(parser({ schema: LambdaFunctionUrlSchema }))` with Lambda Function URL + CloudFront OAC

### Steps to Reproduce

Creating a full example is a bit too much work for right now, but you can take my minimal Lambda Function URL + CloudFront OAC example from https://github.com/aws/aws-cdk/issues/21771#issuecomment-2073425721 and replace the Lambda function with a TS one using `.use(parser({ schema: LambdaFunctionUrlSchema }))` middleware.

### Possible Solution

- Make `principalOrgId` nullable
- Make `cognitoIdentity` nullable

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

20.x

### Packaging format used

npm

**Comment by aripalo** [comment]
Temporary "user-land" workaround is to ignore the `requestContext` (assuming one doesn't care about its contents in Lambda FnUrl + OAC context):
```ts
const TempSchema = LambdaFunctionUrlSchema.merge(
  z.object({
    requestContext: z.unknown(),
  }),
);
```

**Comment by dreamorosi** [comment]
Hi @aripalo, thank you for trying the Parser utility and taking the time to open an issue, as well as providing a temporary workaround.

I'll add this to the backlog so we can take a look at fixing it.
