### ISSUE TITLE
Maintenance: adopt Dependabot multi-directory config

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#2454]
### Summary

GitHub [just announced](https://github.blog/changelog/2024-04-29-dependabot-multi-directory-configuration-public-beta-now-available/) a public beta for multi-directory configurations for Dependabot.

Today our Dependabot config has multiple entries for the same package manager, for example [here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/.github/dependabot.yml#L4) and [here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/.github/dependabot.yml#L16). 

This new setting allows us to specify multiple directories under the same config group.

### Why is this needed?

So that the Dependabot config is simplified.

### Which area does this relate to?

Automation

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by daschaa** [comment]
I would like to take this issue :)
