### ISSUE TITLE
Feature request: deploy Lambda layers in `ap-south-2` and `me-central-1` regions

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#2674]
### Use case

As per issue title, we should start publishing our Lambda layers to these two regions starting from the next release. This will allow us to have the layer showing up in the Lambda console UI as well as allow customers to use the Layer in them.

### Solution/User Experience

Following the process described [here](https://docs.powertools.aws.dev/lambda/typescript/latest/maintainers/#publish-lambda-layers-to-new-aws-regions), we should do the following actions:
- [x] enable `me-central-1` opt-in region in beta account
- [x] enable `me-central-1` opt-in region in prod account
- [x] bootstrap cdk in `me-central-1` in beta account
- [x] bootstrap cdk in `me-central-1` in prod account
- [x] bootstrap cdk in `ap-south-2` in beta account
- [x] bootstrap cdk in `ap-south-2` in prod account
- [x] add regions in `.github/workflows/reusable_deploy_layer_stack.yml` list
- [x] add regions in `docs/index.md` table
- [ ] run [`layer-balancer`](https://github.com/aws-powertools/powertools-lambda-python/tree/develop/layer/scripts/layer-balancer) in `ap-south-2` prod account
- [ ] run [`layer-balancer`](https://github.com/aws-powertools/powertools-lambda-python/tree/develop/layer/scripts/layer-balancer) in `me-central-1` prod account

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
@am29d - I need your help with this one. I am not sure how to enable the opt-in region in the two accounts. Also if you could help me with aligning the layer versions I'd appreciate it.

I have already bootstrapped in the enabled region and made the changes to the files in the repo, PR is here #2675

**Comment by am29d** [comment]
Will be back tomorrow and we can go thorough it 🫡

**Comment by am29d** [comment]
Access for `me-central-1` requested, waiting for update.

**Comment by dreamorosi** [comment]
I have bootstrapped the accounts but still need to run the script to align the versions. Please before running it let's talk offline.

**Comment by dreamorosi** [comment]
Putting this on hold until the next iteration (next week).

**Comment by dreamorosi** [comment]
Reopening this as we'll release the layers in these regions in a future iteration.
