### ISSUE TITLE
Bug: idempotent decorator in combination does not maintain class scope

### ISSUE THREAD

**Issue by HaaLeo** [aws-powertools/powertools-lambda-typescript#2692]
### Expected Behavior

This is probably a follow up to #1481
When the `@idempotent` decorator is used with other powertools decorators such as the `@tracer.captureLambdaHandler()` decorator the lambda function executes without an error with all the features of the decorators.

### Current Behavior

This is probably a follow up to #1481
When the `@idempotent` decorator is used with other powertools decorators such as the `@tracer.captureLambdaHandler()` decorator the lambda function breaks

### Code snippet

```typescript
import type { EventBridgeEvent, EventBridgeHandler } from 'aws-lambda';
import { IdempotencyConfig, idempotent } from '@aws-lambda-powertools/idempotency';
import { DynamoDBPersistenceLayer } from '@aws-lambda-powertools/idempotency/dynamodb';
import { Tracer } from '@aws-lambda-powertools/tracer';

const tracer = new Tracer({ serviceName: 'foobarservice' });
const persistenceStore = new DynamoDBPersistenceLayer({
    tableName: 'foo-table',
    keyAttr: 'partitionKey',
    sortKeyAttr: 'sk',
    inProgressExpiryAttr: 'inProgressExpiration',
    staticPkValue: 'Idempotency#pk'
});
const config = new IdempotencyConfig({ expiresAfterSeconds: 60, eventKeyJmesPath: 'detail.deduplicationId' });

export class RequestStatusChangedListener {
    private readonly logger = new MyCustomLogger();

    @tracer.captureLambdaHandler()
    @idempotent({ persistenceStore, config })
    public async handler(event: EventBridgeEvent<string, unknown>): Promise<string> {
        this.logger.debug(`Received event="${JSON.stringify(event)}".`);

        return 'success';
    }
}

const listener = new RequestStatusChangedListener();
export const handler: EventBridgeHandler<string, unknown, string> = listener.handler.bind(listener);
```

### Steps to Reproduce

1. Deploy the code snippet
2. Add some dummy custom logger
3. Invoke the lambda function

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

20.x

### Packaging format used

npm

### Execution logs

```Shell
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read properties of undefined (reading 'debug')",
    "stack": [
        "TypeError: Cannot read properties of undefined (reading 'debug')",
        "    at qg.handler (file:///var/task/index.mjs:125:1450)",
        "    at qg.getFunctionResult (file:///var/task/index.mjs:111:22338)",
        "    at qg.handle (file:///var/task/index.mjs:111:22683)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at async file:///var/task/index.mjs:111:39254"
    ]
}
```

**Comment by HaaLeo** [comment]
Update: Switching the order of the decorators did not change the behavior.

**Comment by dreamorosi** [comment]
Hi @HaaLeo - thanks for opening this issue.

I'm looking into this and will report back here.

**Comment by dreamorosi** [comment]
I am able to reproduce the issue, and at first glance it does seem to be related to the issue you linked.

After testing however, it doesn't appear to be related to the interaction with other decorators. If I remove the Tracer decorator altogether, the handler is still not able to access the logger property.

Will continue to look into it.

**Comment by dreamorosi** [comment]
Hi @HaaLeo - you were right on the root cause of the issue and we were not preserving the scope of the decorated method.

I have just put up a PR to address the bug. I have tested a build that includes the fix with the code snippet you shared and it seems to work.
