### ISSUE TITLE
Bug: Lambda layer not found in particular region (`eu-west-1`)

### ISSUE THREAD

**Issue by H1Gdev** [aws-powertools/powertools-lambda-typescript#2697]
### Expected Behavior

`AWSLambdaPowertoolsTypeScript` Lambda layers can be added correctly in `eu-west-1`.

For reference, it exists in `eu-west-2`, `us-east-1` and `ap-northeast-1`.

### Current Behavior

```
Failed to load layer version details: The resource you requested does not exist.
Layer version arn:aws:lambda:eu-west-1:094274105915:layer:AWSLambdaPowertoolsTypeScript:12 does not exist.
```

### Code snippet

```yml
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:094274105915:layer:AWSLambdaPowertoolsTypeScript:12
```

### Steps to Reproduce

```shell
cd sam-app
sam build
sam deploy
```

### Powertools for AWS Lambda (TypeScript) version

1.8.0

### AWS Lambda function runtime

18.x

### Packaging format used

Lambda Layers

### Execution logs

```Shell
Failed to load layer version details: The resource you requested does not exist.
```

**Comment by dreamorosi** [comment]
Hi @H1Gdev,

We are investigating this issue in the Ireland region as we speak (all other regions are unaffected). We'll come back to you as soon as we have confirmation from the Lambda team.

Until we conclude our investigation, we've created a new v1 Layer with the exact same versions, i.e. in your case it'd be `arn:aws:lambda:eu-west-1:094274105915:layer:AWSLambdaPowertoolsTypeScriptV1:12`.

**Comment by dreamorosi** [comment]
Hi @H1Gdev, thank you for also opening a Premium Support Case about this.

We’ve informed Support that these layers were accidentally deleted in Ireland and have been recovered since yesterday.
