### ISSUE TITLE
Feature request: export LoggerInterface in `@aws-lambda-powertools/logger/types`

### ISSUE THREAD

**Issue by sandrokeil** [aws-powertools/powertools-lambda-typescript#2828]
### Expected Behavior

The `LoggerInterface` should be able to be imported, so I can decorate the logger with my own implementation.

```typescript
import { LoggerInterface } from '@aws-lambda-powertools/logger/types';
```

### Current Behavior

The current export of logger types is missing the `LoggerInterface` from `Logger.d.ts`. See https://github.com/aws-powertools/powertools-lambda-typescript/blob/72803e2f99509bca41db1ee0f0523abd93150f48/packages/logger/src/types/index.ts#L9-L18 

### Code snippet

```typescript
import { LoggerInterface } from '@aws-lambda-powertools/logger/types';
```

### Steps to Reproduce

1. install powertools
2. try to import the `LoggerInterface`
3. TS2305 (no exported member) error should occur

### Possible Solution

Export also `LoggerInterface` here https://github.com/aws-powertools/powertools-lambda-typescript/blob/72803e2f99509bca41db1ee0f0523abd93150f48/packages/logger/src/types/index.ts#L09-L18

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

20.x

### Packaging format used

npm

**Comment by dreamorosi** [comment]
Hi @sandrokeil - thank you for opening the issue.

Could you please share a bit more about the use case for having the `LoggerInterface` exposed?

**Comment by sandrokeil** [comment]
@dreamorosi I want to create a logger class which implements the `LoggerInterface`. For this I want to use the [decorator design pattern](https://en.wikipedia.org/wiki/Decorator_pattern). I want to add the functionality of a so called *FingersCrossed* logger. If the `LoggerInterface` is exposed, I can implement any new functionality to the logging methods and don't need to change my code because I can reference the interface instead of the concrete implementation.

Any concerns about to export the `LoggerInterface`?

[FingersCrosserLogger](https://github.com/Seldaek/monolog/blob/main/doc/02-handlers-formatters-processors.md#wrappers--special-handlers)
> A very interesting wrapper. It takes a handler (in my case the *powertools logger*) as a parameter and will accumulate log records of all levels until a record exceeds the defined severity level. At which point it delivers all records, including those of lower severity, to the handler it wraps. This means that until an error actually happens you will not see anything in your logs, but when it happens you will have the full information, including debug and info records. This provides you with all the information you need, but only when you need it.

**Comment by dreamorosi** [comment]
Hey, thanks for the additional info.

I don't have any major concern with exposing the interface, I'm only curious to learn how you'd use it.

I remember removing it from the exported types because I though having the actual class would be enough to extend the behavior, for example:

```ts
import { Logger } from "@aws-lambda-powertools/logger"

class MyLogger extends Logger {}
```

By using the interface with `implements` you'd have to replace the entirety of the Logger:

```ts
import type { LoggerInterface } from "@aws-lambda-powertools/logger/types"

class MyLogger implements LoggerInterface {}
```

I would really appreciate if you could share a concrete code example, even if it's pseudo code

**Comment by dreamorosi** [comment]
Either way - based on [our definition of bug](https://docs.powertools.aws.dev/lambda/typescript/latest/maintainers/#is-that-a-bug) this should be classified as a feature request, since it doesn't have an impact on the runtime behavior of the tool.

I'm going to change the type to `Feature request` and label as improvement.

**Comment by sandrokeil** [comment]
A public `LoggerInterface` would give the user more extensibility of the logger right? Yes, I have to implement all the methods from the `LoggerInterface` but it's just a pass through, except for the logging error level methods. Even a more smaller `LoggerInterface` with only the methods `debug`, `info`, `warn`, `error` and `critical` would be interesting and another interface for the others methods. But from my side the `LoggerInterface` can stay like it is.

IMHO: I would mark the `Logger` class as *final* and if a user needs other / enchanced functionality, they can just implement the `LoggerInterface` in their own class. So the pseudo code example below is a wrapper class which adds some functionality without overrding methods of the concrete implementation.

```typescript
import type { LoggerInterface } from "@aws-lambda-powertools/logger/types"

export class MyEnchancedLogger implements LoggerInterface {
   constructor (
        private readonly logger: LoggerInterface
   ) {}

   private handle(...) {
      // more or less same logic like in PHPs FingersCrossed Logger
   }

   debug(input, ...extraInput): void {
       this.handle(input, extraInput);  
   }
   // same implementation for the other logging error level methods

  addContext(context): void {
    this.logger.addContext(context)
  }
  // same implementation for the rest of the LoggerInterface methods
}
```

**Comment by dreamorosi** [comment]
I see, thank you for taking the time to explain and share an example.

With this in mind, I think it can make sense to export the interface again.

I'm going to move onto your PR and leave any further comments there.
