### ISSUE TITLE
Feature request: provide scoped subpath exports for schemas & envelopes

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#2829]
### Use case

The Parser utility has a number of built-in schemas and envelopes that customers can use in their functions. Currently, all of these [except two](https://github.com/aws-powertools/powertools-lambda-typescript/blob/72803e2f99509bca41db1ee0f0523abd93150f48/packages/parser/package.json#L46-L53) are exposed via a barrel file `@aws-lambda-powertools/parser/schemas`.

We should work towards exporting each category of schemas and envelopes on a per-service basis via dedicated exports.

### Solution/User Experience

Customers should be able to import any given schema or envelope using a targeted export, for example, all the API Gateway-related schemas should be available under the `@aws-lambda-powertools/parser/schemas/api-gateway` export and all the S3 ones under `@aws-lambda-powertools/parser/schemas/s3`, the same applies to envelopes which would have, for example, SQS envelopes under `@aws-lambda-powertools/parser/envelopes/sqs`.

With this change, customers would be able to have a slimmer bundle since they'd be importing only the schemas/envelopes of the category they're actually using instead of all of them.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by daschaa** [comment]
I would like to take this issue :) One question tho: Should the barrel export stay for backwards compatibility? So that it doesn't break existing code?

**Comment by dreamorosi** [comment]
Thank you @daschaa, assigning this to you!

> Should the barrel export stay for backwards compatibility (and the explicit exports are added on top)? So that it doesn't break existing code?

Yes, we will leave it both for backwards compatibility but also for convenience for those who can't/don't want to use subpath exports.

**Comment by am29d** [comment]
While we are talking about exports, this is a good opportunity to close #2811 , should we do both with one PR?

**Comment by dreamorosi** [comment]
> should we do both with one PR?

I would do them separately (easier to identify issues and revert if needed), but ideally would do #2811 first so we can include the new schemas from that PR in the exports from this one as well.
