### ISSUE TITLE
Bug: LogFormatter Timezone

### ISSUE THREAD

**Issue by springer5296** [aws-powertools/powertools-lambda-typescript#2833]
### Expected Behavior

`this.envVarsService?.getTimezone()` should return a valid timezone if it is configured.

### Current Behavior

`this.envVarsService?.getTimezone()` is returning the path to the timezone on my machine (:/etc/localtime).

### Code snippet

```
formatTimestamp(now) {
        const defaultTimezone = 'UTC';
        /**
         * If a specific timezone is configured and it's not the default `UTC`,
         * format the timestamp with the appropriate timezone offset.
         **/
        const configuredTimezone = this.envVarsService?.getTimezone(); //this returns ":/etc/localtime"
        if (configuredTimezone && !configuredTimezone.includes(defaultTimezone))
            return this.#generateISOTimestampWithOffset(now, configuredTimezone);
        return now.toISOString();
    }
```

### Steps to Reproduce

Use @aws-lambda-powertools/logger locally

### Powertools for AWS Lambda (TypeScript) version

2.5.0

### AWS Lambda function runtime

20.x

### Packaging format used

npm

**Comment by dreamorosi** [comment]
Hi @springer5296, thank you for opening this issue.

Without using Powertools, what's the value of the `TZ` environment variable?

For example, if you run this code below, what's the output?

```js
console.log(process.env.TZ);
```

We support only values that appear in the `TZ` column of the [IANA time zone database](https://data.iana.org/time-zones/tzdb-2021a/zone1970.tab) because that's the convention that the AWS Lambda service uses.

**Comment by springer5296** [comment]
Thanks for the quick response @dreamorosi! It does seem like TZ is being set to that value for some reason. I will do some digging to determine how we can get this set to a proper value in our repo.

**Comment by dreamorosi** [comment]
From what I read online, it seems that this should be the system-wide setting which is a symlink.  I am not sure Node.js is able to or can be configured to follow the link and convert it to the expected format.

If this is a test environment (but likely even if it isn't) I think the easiest way would be to set the desired timezone as environment variable in your code/entry points (`process.env.TZ = 'Europe/Madrid'`) or when you launch your code (i.e. `TZ=Europe/Madrid node foo.js`).

I hope it helps!
