### ISSUE TITLE
[Support Lambda Powertools]: WeSchool

### ISSUE THREAD

**Issue by sav-valerio** [aws-powertools/powertools-lambda-typescript#2850]
### Organization Name

WeSchool

### Your Name

Saverio Valerio

### Your current position

DevOps

### (Optional) Company logo

https://static.weschool.com/logo.png

### (Optional) Use case

At [WeSchool](https://www.weschool.com/) our mission is to reinvent learning platforms and empower instructors & learners with a more inclusive, collaborative and engaging approach.

In 2023 we started to really take advantage of Serverless Computing and AWS Lambda for augmenting the feature set of our services.

We've been using pretty much the whole Powertools suite since then: mainly Logger, Metrics, Parameters and Tracer, but we will probably also have a look at the newer ones.

This really helped us starting to adopt quickly Lambda and focus on the business logic, instead of writing over and over again (or copying around between projects) utils.

### Also using other Powertools for AWS Lambda languages?

- [ ] Python
- [ ] Java
- [ ] .NET

**Comment by dreamorosi** [comment]
Hi @sav-valerio, thank you so much for opening this issue, and happy to hear that Powertools for AWS is helping WeSchool in their journey.

I'll add the company name to the pages on Monday first thing.

Thank you again!
