### ISSUE TITLE
[Support Powertools for AWS Lambda]: LocalStack

### ISSUE THREAD

**Issue by whummer** [aws-powertools/powertools-lambda-typescript#2862]
### Organization Name

LocalStack

### Your Name

Waldemar Hummer

### Your current position

CTO

### (Optional) Company logo

https://awsmp-logos.s3.amazonaws.com/d23d1bcc-cfe5-4301-893b-8f30025074e4/f5a016996213129265ed0eb248157749.png

### (Optional) Use case

We are using Powertools internally at LocalStack for our own cloud platform running on AWS (for logging/tracing, among other features). 

We also see an increasing number of our users who are using the LocalStack AWS emulator in conjunction with Powertools, i.e., running Lambda functions on the local machine and then debug the state locally. (e.g., here are a [few items in our issue tracker](https://github.com/search?q=repo%3Alocalstack%2Flocalstack+powertools&type=issues)). 

We have recently also started building out a couple of sample apps to illustrate Powerapps running on LocalStack, e.g., [here](https://github.com/remotesynth/powertools-typescript-demos).

Thanks and kudos for building this awesome tool - keep up the great work! 🚀 

### Also using other Powertools for AWS Lambda languages?

- [X] Python
- [ ] Java
- [ ] .NET

**Comment by dreamorosi** [comment]
Thank you Waldemar for deciding to publicly have LocalStack support Powertools for AWS Lambda 🎉 

I know @am29d is already in touch with your team, and we both look forward to explore collaboration opportunities.
