### ISSUE TITLE
Bug: IdempotencyPersistenceLayerError cause undefined

### ISSUE THREAD

**Issue by jorgecamilowu** [aws-powertools/powertools-lambda-typescript#2915]
### Expected Behavior

When looking at the logs, the `cause` attribute of `IdempotencyPersistenceLayerError` should include what actually went wrong.

[Discord discussion link](https://discord.com/channels/1006478942305263677/1271492195123466323)

### Current Behavior

The `cause` attribute of `IdempotencyPersistenceLayerError` is undefined

### Code snippet

```TypeScript
const persistenceStore = new DynamoDBPersistenceLayer({
  tableName: "Token.1234",
});

export const handler = makeIdempotent(handlerFunction, {
  persistenceStore,
});
```

### Steps to Reproduce

1. Pass an invalid table name to `DynamoDBPersistenceLayer` such as `"Token.1234"`
2. Trigger the lambda
3. See `IdempotencyPersistenceLayerError` error in Cloudwatch logs missing the `cause` attribute
![image](https://github.com/user-attachments/assets/ff80b92b-a6fb-47bf-823f-1da1db1974de)

### Powertools for AWS Lambda (TypeScript) version

2.7.0

### AWS Lambda function runtime

20.x

### Packaging format used

npm

### Execution logs

```Shell
2024-08-12T06:04:28.165Z	1ecc73f4-1b73-4bf0-bf92-d8fd26a123d6	ERROR	Invoke Error 	{
    "errorType": "IdempotencyPersistenceLayerError",
    "errorMessage": "Failed to save in progress record to idempotency store",
    "name": "IdempotencyPersistenceLayerError",
    "stack": [
        "IdempotencyPersistenceLayerError: Failed to save in progress record to idempotency store",
        "    at #saveInProgressOrReturnExistingResult (/var/task/index.js:1459894:13)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at async IdempotencyHandler.handle (/var/task/index.js:1459814:42)"
    ]
}
```

**Comment by dreamorosi** [comment]
Hi @jorgecamilowu, thank you for taking the time to open this issue, and for finding the bug in the first place.

I have started working on a PR that should address the issue.
