### ISSUE TITLE
Maintenance: fix `typedoc-plugin-zod` usage

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#2923]
### Summary

Currently we are using a Typedoc plugin called `typedoc-plugin-zod` which is expected to prettify the Zod schemas in our TypeDoc API docs.

This is working well enough, however when building the docs the plugin is causing thousands of warnings:

![image](https://github.com/user-attachments/assets/dd5b28b5-7d94-4f52-900d-40cdb26ee0b5)

I was able to confirm that the plugin is the source of the warnings because commenting it out in the main `typedoc.json` config makes all the warnings immediately disappear.

We should investigate if this is: 1/ a bug with the plugin, 2/ a misconfiguration on our part, or 3/ a misuse of our typedoc annotations that causes the warnings.

### Why is this needed?

So that we don't have thousands of warnings when generating the API docs.

### Which area does this relate to?

Parser

### Solution

In case of 2/ or 3/, we should fix it, in case of 1/ ideally we should open an issue on the plugin's repo to get it fixed. If none of the above is a viable option, we should look at alternatives or removing the plugin entirely.

The good thing is that the plugin is from the same author as Typedoc itself, so unless it's an issue with Zod itself I'm confident there will be a solution.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by am29d** [comment]
I was also super annoyed by the spam in the logs, hard to see other warnings and errors. I will investigate.

**Comment by dreamorosi** [comment]
Typedoc released a new version of their package as well as the Zod plugin. The new version was merged in #2949 and I was able to confirm that the warning logs are gone.

Thank you @am29d for opening the issue upstream and getting this fixed!
