### ISSUE TITLE
Bug: Fetch traces only capture the hostname of the request URL

### ISSUE THREAD

**Issue by gruntster** [aws-powertools/powertools-lambda-typescript#2954]
### Expected Behavior

The request URL captured by the trace of a Fetch request should be the URL of the request.

### Current Behavior

The request URL captured by the trace of a Fetch request is only the requested hostname.

### Code snippet

```typescript
await fetch("https://aws.amazon.com/free?test=1");
```

### Steps to Reproduce

1. Set `AWS_XRAY_DEBUG_MODE` environment variable to `true` of an instrumented Lambda function.
2. Perform requests using `fetch` and `node:https`
```typescript
await fetch("https://aws.amazon.com/free?test=1");
await axios.get("https://aws.amazon.com/free?test=1");
```
3. Compare output of subsegments.

_fetch emits incorrect request URL:_
```json
        {
          "id": "45b22f447784c44f",
          "name": "aws.amazon.com",
          "start_time": 1724108234.18,
          "namespace": "remote",
          "http": {
            "request": {
              "url": "aws.amazon.com",
              "method": "GET"
            },
            "response": {
              "status": 301,
              "content_length": 0
            }
          },
          "end_time": 1724108234.849
        }
```
_node:https emits correct request URL:_
```json
        {
          "id": "e861c05fa31a14ab",
          "name": "aws.amazon.com",
          "start_time": 1724108234.856,
          "namespace": "remote",
          "http": {
            "request": {
              "url": "https://aws.amazon.com/free",
              "method": "GET"
            },
            "response": {
              "status": 301,
              "content_length": 0
            }
          },
          "end_time": 1724108235.218
        }
```

### Possible Solution

Modify the `onRequestStart` function of the Tracer's `ProviderService` to generate a URL rather than use the hostname.

For example, [modify](https://github.com/aws-powertools/powertools-lambda-typescript/blob/v2.7.0/packages/tracer/src/provider/ProviderService.ts#L111-L124) to the following:

```typescript
  const origin = getOriginURL(request.origin + request.path);
...
  (subsegment as HttpSubsegment).http = {
    request: {
      url: `${origin.protocol}//${origin.hostname}${origin.pathname}`,
      method,
    },
  };
...
```

### Powertools for AWS Lambda (TypeScript) version

2.7.0

### AWS Lambda function runtime

20.x

### Packaging format used

npm

**Comment by dreamorosi** [comment]
Hi @gruntster, thank you for taking the time to report the issue.

I looked into it and I am able to reproduce the behavior you described. When making requests with `fetch`, the trace data is indeed missing the `path`/`pathname`.

I'll be working on a fix before this week's release.
