### ISSUE TITLE
[I Made This]: EventBridge: working around API Destination 5s maximum client timeout constraint, using Lambda PowerTools idempotency

### ISSUE THREAD

**Issue by psantus** [aws-powertools/powertools-lambda-typescript#2975]
### Link to your material

https://dev.to/aws-builders/eventbridge-working-around-api-destination-5s-maximum-client-timeout-constraint-using-lambda-powertools-idempotency-1cb3

### Description

This article discusses how to use Idempotency feature to work around EventBridge API Destinations' built-in maximum client execution timeout (5s) and allow long-running queries, while still benefitting from automated retry and DLQ, and preventing concurrent calls.

### Preferred contact

https://www.linkedin.com/in/paulsantus/

### (Optional) Additional notes

I'm honoured Leandro Damascena suggested we add this blog post to the official documentation!

### Acknowledgment

- [X] I understand this content may be removed from Powertools for AWS Lambda (TypeScript) documentation if it doesn't conform with the [Code of Conduct](https://aws.github.io/code-of-conduct)

**Comment by dreamorosi** [comment]
Hi @psantus, so sorry for the long delay on this. I dropped the ball.

I have opened a PR to get this added and it should get published in the next couple days at most.
