### ISSUE TITLE
Maintenance: add typedoc-plugin-missing-exports plugin to remove missing exports warnings

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#2993]
### Summary

While cleaning up the api docs in one of the issues of #2381 the typedoc complains about resources that are references but not exported. While we can add them to exports to fix it, I found a better solution to add these missing resources to the doc, without exposing them. 

https://github.com/Gerrit0/typedoc-plugin-missing-exports

Also saw, just now that we have this plugin already installed in the package.json, but we did not add it typedoc configuration.

This plugin collects all the missing exports we reference but still don't want to export. 

### Why is this needed?

So we don't have to export types, classes and functions that are internal just to have them in the API docs.

### Which area does this relate to?

Other

### Solution

Add https://github.com/Gerrit0/typedoc-plugin-missing-exports plugin your package script `npm run docs-generateApiDoc`. In addition, I would also revert the changes we have made in the recent PRs to fix the warnings.

Alternatively we can mute those warnings, but the information about the internal interfaces, classes and functions will not be available in the API docs, which I would prefer to have. 

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
Good find, I agree we should enable it.

It must have been unintentionally dropped when we did the v2 merge (probably my bad).
