### ISSUE TITLE
Feature request: metrics rename purgeStoredMetrics to publishStoredMetrics

### ISSUE THREAD

**Issue by flochaz** [aws-powertools/powertools-lambda-typescript#301]
## Description of the feature request

**Problem statement**

`purgeStoredMetrics` can be confusing and be understood as dropping metrics.

**Summary of the feature**

Propose by @ijemmy to change it to `publishStoredMetrics` (https://github.com/awslabs/aws-lambda-powertools-typescript/pull/285#discussion_r767706914).

### Related issues, RFCs

https://github.com/awslabs/aws-lambda-powertools-typescript/pull/285#discussion_r767706914

**Comment by ijemmy** [comment]
PR #377 has solved this.
