### ISSUE TITLE
Feature request: Option to setLogger for metrics as it is done with tracer

### ISSUE THREAD

**Issue by jorgevrgs** [aws-powertools/powertools-lambda-typescript#3099]
### Use case

Currently, `tracer.provider.setLogger(logger)` allows the customization of the logger. However, in the Metrics class there is not an option to do the same.

### Solution/User Experience

Instead of only using `this.setConsole()`  [here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/381c9c91b9a96bb1b3554d04ad7bfc3baeaf422b/packages/metrics/src/Metrics.ts#L702) as a private method, it is possible to update the `MetricsOptions` and receive a logger there.

### Alternative solutions

```Markdown
- Update `MetricsOptions` to receive a custom logger
- Expose `setConsole` method as public and receive a param `logger: Logger` of the same type of `tracer.provider.setLogger`.
```

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
Hi, thank you for opening this issue.

We already have an issue to track this at #2126, and a PR open to implement this at #3057.

**Comment by jorgevrgs** [comment]
Thank you so much for replying. I guess I used the wrong terms when I was looking for an existing topic about the same issue 🙂.

**Comment by dreamorosi** [comment]
No worries, it's not easy to keep track of existing issues and the title of that one wasn't super clear.

I'm going to close this in favor of #2126, which should also be closed soon.
