### ISSUE TITLE
Feature request: include parser feature in lambda layer

### ISSUE THREAD

**Issue by scratchclaggy** [aws-powertools/powertools-lambda-typescript#3100]
### Use case

I want to use the new parser feature in my lambdas but need to ship it with my code as it is not available in the lambda layer currently.

### Solution/User Experience

We simply need to include the feature when building / publishing the lambda layers.

### Alternative solutions

```Markdown
Keep it out of the layer but update documentation:

It may be that this feature is not used frequently, in which case it makes sense to leave it out of the layers to minimize the layer size. In this case though, it should be noted in the docs that the parser feature is not included in the layer like the other features are.

Ship multiple layers:

If layer size is of concern, there may be a case for shipping a layer that includes the SDKs and the logger / metrics / tracer features, and then shipping individual layers for each of the other features that are used less frequently.
```

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by scratchclaggy** [comment]
Note that this was also discussed [in the Discord community](https://discord.com/channels/1006478942305263677/1286603199075061801).

**Comment by dreamorosi** [comment]
Hi @scratchclaggy, thank you for opening the issue.

I'll assign the issue to you and will continue the discussion in the PR.

Thank you again!
