### ISSUE TITLE
[Support Lambda Powertools]: Flyweight

### ISSUE THREAD

**Issue by zirkelc** [aws-powertools/powertools-lambda-typescript#3151]
### Organization Name

[Flyweight](https://flyweight.io/)

### Your Name

Chris Cook

### Your current position

Founder

### Also using other Powertools for AWS Lambda languages?

- [X] Python
- [ ] Java
- [ ] .NET

**Comment by dreamorosi** [comment]
Hi @zirkelc, thank you again for adding Flyweight as customer reference to Powertools for AWS.

I'll be adding the company name & link to our docs & website in a PR within the day.
