### ISSUE TITLE
Feature request: Export APIGatewayV2RequestAuthorizer & APIGatewayV2RequestContext schemas

### ISSUE THREAD

**Issue by codyfrisch** [aws-powertools/powertools-lambda-typescript#3182]
### Use case

I need to parse the actual structure of an APIGatewayProxyEventV2Schema's requestContext.authorizer.lambda key (for both typing and validation reasons)

### Solution/User Experience

Export the APIGatewayV2RequestAuthorizer & APIGatewayV2RequestContext schemas so that APIGatewayV2RequestAuthorizer can be extended with a custom schema for the lambda authorizer, and in turn extend APIGatewayV2RequestContext with that schema (and in turn extend APIGatewayProxyEventV2Schema).

### Acknowledgment

- [x] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [x] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
Hi @codyfrisch, thanks for opening this issue.

I think it makes sense to export them, I'm adding this to the backlog.

If you'd like to open a PR to get it done, I'd be happy to help you merge it. Otherwise we'll get to it before next release in ~2 weeks.

**Comment by codyfrisch** [comment]
> If you'd like to open a PR to get it done, I'd be happy to help you merge it. Otherwise we'll get to it before next release in ~2 weeks.

I'll let you do it. (I'll start contributing eventually). In the meantime, I created duplicates to keep me going until this is released.
