### ISSUE TITLE
Docs: fix env variable name in `logEventIfEnabled()` docstring

### ISSUE THREAD

**Issue by hibanka** [aws-powertools/powertools-lambda-typescript#3196]
### Expected Behavior

During development I discovered that the `logger.logEventIfEnabled()` method has an incorrect environment variable in [description](https://github.com/aws-powertools/powertools-lambda-typescript/blob/7e07ce9cbd44d2074bc737990c3e03606c33a14f/packages/logger/src/Logger.ts#L435) and [example](https://github.com/aws-powertools/powertools-lambda-typescript/blob/7e07ce9cbd44d2074bc737990c3e03606c33a14f/packages/logger/src/Logger.ts#L439).

Should be `POWERTOOLS_LOGGER_LOG_EVENT` instead of `POWERTOOLS_LOG_EVENT` according to the official documentation.

![Image](https://github.com/user-attachments/assets/bd922ef3-4543-42ec-a3e8-8d093d2b5ec9)

### Current Behavior

Not needed

### Code snippet

Not needed

### Steps to Reproduce

Not needed

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

20.x

### Packaging format used

npm

**Comment by dreamorosi** [comment]
Hi, thank you for opening this issue.

You are right, the description of the method is incorrect and the environment variable is wrong. The correct name is the one you mentioned, and that is also specified [here](https://docs.powertools.aws.dev/lambda/typescript/latest/#environment-variables) and [here](https://docs.powertools.aws.dev/lambda/typescript/latest/core/logger/#log-incoming-event) in the docs.

Given that this is just a documentation issue it doesn't constitute a runtime bug (see [our definition of bug](https://docs.powertools.aws.dev/lambda/typescript/latest/maintainers/#is-that-a-bug)). I'm renaming and changing the category of the issue to a documentation improvement to reflect that.

We'll get this fixed before the next release. If you or anyone reading is interested in opening a PR, feel free to leave a comment below so we can assign the issue to you.

**Comment by kevinpeno** [comment]
Fixed in #3197 hopefully!
