### ISSUE TITLE
Maintenance: Parser inferred result always set event to array type

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#3226]
### Summary

When using the Middy.js middleware for parser, customers can specify envelopes and schemas for the middleware to use to parse the event. To ease usage for customers, we introduced types that are supposed to infer the `event` type based on the arguments passed to the middleware.

Currently when using envelopes, the type of the `event` is always assumed to be an array when it should not be the case.

For example, this is correct:

```ts
import middy from '@middy/core';
import { parser } from '@aws-lambda-powertools/parser/middleware';
import { SqsEnvelope } from '@aws-lambda-powertools/parser/envelopes';
import { z } from 'zod';

export const handler = middy(async () => {
  return {
    statusCode: 200,
    body: JSON.stringify('Hello, World!'),
  };
}).use(parser({ schema: z.any(), envelope: SqsEnvelope }));
```

![Image](https://github.com/user-attachments/assets/40988889-f64f-4b93-ac6f-41a4c2c76c00)

but this is not:

```ts
import middy from '@middy/core';
import { parser } from '@aws-lambda-powertools/parser/middleware';
import { EventBridgeEnvelope } from '@aws-lambda-powertools/parser/envelopes';
import { z } from 'zod';

export const handler = middy(async () => {
  return {
    statusCode: 200,
    body: JSON.stringify('Hello, World!'),
  };
}).use(parser({ schema: z.any(), envelope: EventBridgeEnvelope }));
```

![Image](https://github.com/user-attachments/assets/b62bdc22-1958-4bab-855c-6bd126b62d36)

In the second case, EventBridge's `detail-type` field is an object and not an array, but the [types here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/a3dd654d8b0e7e054300940586d73b3b23c14b6d/packages/parser/src/types/parser.ts#L53-L60) think it's always an array.

### Why is this needed?

So that the types when using the Middy.js middleware are correct.

### Which area does this relate to?

Parser

### Acknowledgment

- [x] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by am29d** [comment]
This is strange. While WebStorm shows me the correct (non array) inferred type for both `EventBridgeEnvelope` and `SqsEnvelope`, VSCode shows an array of the custom schema also for both envelopes. I have also tested Zed, it has the same behaviour as VSCode (but faster 😄 ).
