### ISSUE TITLE
Docs: Typo in tracer documentation

### ISSUE THREAD

**Issue by psperber** [aws-powertools/powertools-lambda-typescript#3254]
### What were you searching in the docs?

In [this](https://docs.powertools.aws.dev/lambda/typescript/latest/core/tracer/#tracing-http-requests) section the parameter `captureHTTPsRequests` has a `S` instead of a `s`.

### How can we improve?

Change the letter to `s`

### Acknowledgment

- [x] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by dreamorosi** [comment]
Hi @psperber, thank you for opening the issue - there is indeed a typo.

I see you've opened a PR, I'll merge it right away.

Thank you!
