### ISSUE TITLE
Feature request: Export APIGatewayRequestAuthorizerEventV2 types (etc.)

### ISSUE THREAD

**Issue by codyfrisch** [aws-powertools/powertools-lambda-typescript#3270]
### Use case

All built-in schemas should be exported, as well as their type. Seems the authorizer event types were not exported when the schemas were created.

### Solution/User Experience

Create and export the APIGatewayRequestAuthorizerEvent (and EventV2) types. These appear to have been missed in #2624 

### Acknowledgment

- [x] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by codyfrisch** [comment]
Nope those are different schemas in #3182 (the ones used in the APIGatewayProxyEventV2). These are the types for the schemas in #2624, they appear to have been missed when that was merged.

**Comment by dreamorosi** [comment]
You are right, my bad.

The linked PR (#3271) addresses both this and the other issue exporting both schemas and types.
