### ISSUE TITLE
Feature request: ability to silence / skip publishing metrics via env variable

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#3329]
### Discussed in https://github.com/aws-powertools/powertools-lambda-typescript/discussions/3315

<div type='discussions-op-text'>

<sup>Originally posted by **zirkelc** November 14, 2024</sup>
Hi,

I wanted to know if it is possible to _silence metrics_ based on an environment variable in the same way it is possible to [silence logs](https://docs.powertools.aws.dev/lambda/typescript/main/core/logger/#silencing-logs).

Basically, I want to omit publishing metrics if the environment **is not** production. Ideally, that should be controllable with an env var.</div>

### Solution/User Experience

- by default, Metrics is enabled (current behavior)
- if the `POWERTOOLS_METRICS_DISABLED` env variable is present and [truthy](https://github.com/aws-powertools/powertools-lambda-typescript/blob/5350afed92d02b7b8d47f387705f70c59deeeb65/packages/commons/src/config/EnvironmentVariablesService.ts#L90-L94) when the `Metrics` class is instantiated, then it becomes disabled
- if dev mode is enabled by means of `POWERTOOLS_DEV` which can be checked with [this method](https://github.com/aws-powertools/powertools-lambda-typescript/blob/5350afed92d02b7b8d47f387705f70c59deeeb65/packages/commons/src/config/EnvironmentVariablesService.ts#L81-L83), when the `Metrics` class is instantiated, then it also becomes disabled
- If `POWERTOOLS_METRICS_DISABLED` is set to `false`, and dev mode is enabled, then `POWERTOOLS_METRICS_DISABLED` takes precedence and the utility stays enabled.

### Alternative solutions

N/A

### Acknowledgment

- [x] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [x] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by zirkelc** [comment]
I will work on this!
