### ISSUE TITLE
Feature Request: add support for Middy.js 6.x

### ISSUE THREAD

**Issue by anthony-nhs** [aws-powertools/powertools-lambda-typescript#3367]
### Expected Behavior

You can install v6.x of @middy/core and @aws-lambda-powertools/logger

### Current Behavior

When installing v6.x of @middy/core you get this error 

```
 npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @aws-lambda-powertools/logger@2.11.0
npm ERR! Found: @middy/core@6.0.0
npm ERR! node_modules/@middy/core
npm ERR!   @middy/core@"^6.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @middy/core@"4.x || 5.x" from @aws-lambda-powertools/logger@2.11.0
npm ERR! node_modules/@aws-lambda-powertools/logger
npm ERR!   @aws-lambda-powertools/logger@"^2.11.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @middy/core@5.5.1
npm ERR! node_modules/@middy/core
npm ERR!   peerOptional @middy/core@"4.x || 5.x" from @aws-lambda-powertools/logger@2.11.0
npm ERR!   node_modules/@aws-lambda-powertools/logger
npm ERR!     @aws-lambda-powertools/logger@"^2.11.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Code snippet

in package.json

```
  "dependencies": {
    "@aws-lambda-powertools/logger": "^2.11.0",
    "@middy/core": "^6.0.0",
```

### Steps to Reproduce

Install @middy/core v6 and @aws-lambda-powertools/logger

### Possible Solution

change peerDepenedencies in @aws-lambda-powertools/logger to include v6 of @middy/core

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

22.x

### Packaging format used

npm

### Execution logs

```Shell

```

**Comment by dreamorosi** [comment]
Hi, thank you for opening this issue.

This is intentional, and also not a bug.

Powertools for AWS is officially compatible only with v4.x and v5.x as of now, as stated in our [docs](https://docs.powertools.aws.dev/lambda/typescript/latest/core/logger/#middy-middleware). Middy.js v6.x was released recently and we haven't yet added automated tests to ensure it's compatible, this is why the peer dependency version range doesn't include the new version.

I'm going to convert this to a feature request and put it in the backlog.

**Comment by anthony-nhs** [comment]
Thanks for the update. I have created a PR that runs test for middy 4, 5, 6 but I appreciate that you might want further tests or investigations on it
https://github.com/aws-powertools/powertools-lambda-typescript/pull/3368

**Comment by WtfJoke** [comment]
@dreamorosi out of curiosity, when is the next release planned with this change 🙃 ?

**Comment by dreamorosi** [comment]
Hey @WtfJoke, sorry for the delay.

The team has been busy for re:Invent and we skipped a release week last week.

I am planning on making a release early next week on Monday/Tuesday at the latest.

Thank you for your patience, and sorry for the inconvenience.

**Comment by WtfJoke** [comment]
No worries! Take your time for the release. Thank you for the fast answer.

**Comment by WtfJoke** [comment]
@dreamorosi and team, thank you for the release 🙌♥️
