### ISSUE TITLE
Feature request: change visibility from `private` to `protected` to allow overrides

### ISSUE THREAD

**Issue by zirkelc** [aws-powertools/powertools-lambda-typescript#3376]
### Use case

As discussed before, I would like to suggest to change the visibility of certain methods of `Logger` from `private` to `protected` to allow overrides by subclassing `Logger`. A use case for such an override would be the buffering of log messages (see #3178). 

If approved, I'm happy to submit a PR.

### Solution/User Experience

The following methods could be made `protected`:
https://github.com/aws-powertools/powertools-lambda-typescript/blob/0dc4de15e0ecb4d39585bd094a2d958be2d06bb2/packages/logger/src/Logger.ts#L703-L707

https://github.com/aws-powertools/powertools-lambda-typescript/blob/0dc4de15e0ecb4d39585bd094a2d958be2d06bb2/packages/logger/src/Logger.ts#L838

https://github.com/aws-powertools/powertools-lambda-typescript/blob/0dc4de15e0ecb4d39585bd094a2d958be2d06bb2/packages/logger/src/Logger.ts#L865-L869

### Alternative solutions

```Markdown

```

### Acknowledgment

- [x] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
Hi @zirkelc, the proposal makes sense.

We discussed this in #3178, so feel free to open a PR to make these changes and I'll help you get it merged before the next release!
