### ISSUE TITLE
Docs: cdk examples + e2e tests 

### ISSUE THREAD

**Issue by saragerion** [aws-powertools/powertools-lambda-typescript#353]
## Description of the feature request
Similarly to what is done for Tracer and Metrics utilities, it would be helpful for developers to add these functionalities.

**Problem statement**

**Summary of the feature**

- Add logger related examples in root folder
- Add e2e tests in the package folder/scope

**Code examples**
N/A

**Benefits for you and the wider AWS community**
Better understand how to use the library, better testing coverage

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### Related issues, RFCs
N/A

**Comment by ijemmy** [comment]
We have e2e tests for logger now (PR #529)

@saragerion I understand that we have already had logger example in `examples/cdk` ([here](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/18228d52bd20a9aa40e64e88fa7b6dea67d8266c/examples/cdk/src/example-function.MyFunction.ts#L10)). 

Or do you mean moving the examples from `packages/logger/examples` to `examples/cdk`? In that case, is this duplicated with #332 (which is on-hold for customer's feedback).
