### ISSUE TITLE
Maintenance: Make `@middy/core` a `devDependency`

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#373]
## Description of the feature request

**Problem statement**

Middy (`@middy/core`) is currently used in the middlewares implementations only for types (as brought up by @saragerion [here](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/370#discussion_r776722962)). 

We should move it as `devDependency` to avoid bundling it to Customers who might not be using it.

- [ ] Move `@middy/core` to `devDependencies` for all packages
- [ ] Update notices in utilities docs to specify that customers who want to use the middleware must install it

**Summary of the feature**

N/A

**Code examples**

N/A

**Benefits for you and the wider AWS community**

Avoid including unnecessary dependencies for those who don't use middy middlewares.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### Related issues, RFCs

[#370](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/370)

**Comment by michaelbrewer** [comment]
Thanks @dreamorosi  for adding this.
