### ISSUE TITLE
Docs: add CDK, Terraform, Serverless Framework, Terraform, Amplify examples

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#385]
## Description of the improvement

**Summary of the proposal**

Currently the docs include an example on how to deploy the utility only using SAM but we could provide examples also for other frameworks (CDK, Terraform, Serverless Framework, Terraform, Amplify) as no everyone uses SAM.

Proposed by @ijemmy 

**How, where did you look for information**

Homepage & Utility-specific pages

**Missing or unclear documentation**

How to deploy a Lambda Fn that uses Powertools

**Improvement**

Similar to what done in this section of the Python's docs:
https://awslabs.github.io/aws-lambda-powertools-python/latest/#lambda-layer

### Related existing documentation

N/A

### Related issues, RFCs

Note for implementor: please check discussion in #520 . The discussion there is related to this issue implementation.

**Summary of change requested in #520**
1. Separate Lambda (application) code and infrastructure code from each other. 
2. Make the Lambda code reusable for other tools. We don't want to manage a duplicated Lambda function code per framework. We should have one set of Lambda code that is deployable with different tools.
3. The goal of example is to have deployable example so users can experiment with it easily. While we may include best practices where possible, it doesn't supersede this original goal.
4. Avoid keeping transpiled JS in Git repo at all cost. 

As the code structure can be controversial, please put a proposal and ping one of the maintainers before creating PR to avoid rework.

**Comment by michaelbrewer** [comment]
@dreamorosi - maybe at least the most common ones for Typescript today? I assume internally you have some stats on this

**Comment by saragerion** [comment]
Maybe for guidance on the deployment we should simply refer to our `examples` folder. 
Either way, not a must have for the GA milestone.

**Comment by dreamorosi** [comment]
Since we have launched Lambda Layers the documentation now has examples of how to use the layers with all the frameworks mentioned above.

I will close this umbrella issue, however I'm in favor of adding additional examples under the `examples/*` folder if there's customer demand. In that case we'll discuss it in dedicated issues.
