### ISSUE TITLE
Docs: Cookiecutter project template with TypeScript Powertools setup (with SAM) 

### ISSUE THREAD

**Issue by ijemmy** [aws-powertools/powertools-lambda-typescript#391]
## Description of the feature request

**Problem statement**
Setting up in TypeScript development environment is difficult and require a lot of manual steps. For users who want to test PowerTool without integrating it into an existing TypeScript project, it could take a very long time (hours, or even days to get config right).

**Summary of the feature**
We provide a Cookiecutter template with TypeScript PowerTool already setup. It has API + 3 functions that uses all 3 core features

Each function will use the following options:
1. Manually 
2. Middy Middleware
3. Decorator

**Code examples**
`sam init --location gh:aws-samples/cookiecutter-aws-sam-typescript-with-powertools`

[Ref documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-init.html)

**Benefits for you and the wider AWS community**
1. Ease of learning for new users. They can test it in actual live environment (required for feature like Tracer) instead of just looking at the code.
2. Ease of starting a new project. This increases adoption speed.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### Related issues, RFCs
N/A

**Comment by michaelbrewer** [comment]
@dreamorosi sam now supports Typescript. So it might be a good time to add this :)

**Comment by dreamorosi** [comment]
> @dreamorosi sam now supports Typescript. So it might be a good time to add this :) 

See https://github.com/aws/aws-sam-cli-app-templates/pull/193

To manage expectations: this is still in a preliminary phase as TS was just added to SAM and there's a few things we want to settle on our side before merging that PR, but we're on it.

**Comment by VRMink** [comment]
> 

@michaelbrewer, do you have a link describing typescript support in SAM?
As this issue suggest, I have just spent 2 days trying to get SAM to play nice with TypeScript, I came here to see how you guys had managed to do it, and to adopt your Powertool.

Looking forward to seeing this solution come alive, till then I will be using JS

**Comment by michaelbrewer** [comment]
@VRMink https://aws.amazon.com/blogs/compute/building-typescript-projects-with-aws-sam-cli/

**Comment by dreamorosi** [comment]
Hello @VRMink we are also working on adding SAM examples to this repo, you can track progress under [this PR](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/674).

**Comment by dreamorosi** [comment]
Hi @VRMink, we have added an example that uses SAM & TypeScript to this repo, you can find it under [`examples/sam`](https://github.com/awslabs/aws-lambda-powertools-typescript/tree/main/examples/sam).

A cookiecutter template for SAM it's also on its way https://github.com/aws/aws-sam-cli-app-templates/pull/193.
