### ISSUE TITLE
Docs: unable to clone & install for development

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#415]
## Bug description

Reported by @michaelbrewer on the [Slack Dev channel](https://awsdevelopers.slack.com/archives/C01A6KK4UFK/p1641407918190900).

<img width="1194" alt="screen_shot_2022-01-05_at_10 45 22_am" src="https://user-images.githubusercontent.com/7353869/148271990-4cc926e9-e609-443d-bf9b-344608400cad.png">

Unable to install package after clean clone of repo, see screenshot above.

### Expected Behavior

Be able to `git clone ...` & `npm install`.

### Current Behavior

Throws an error for missing import of `@aws-lambda-powertools/commons` (see screenshot).

### Possible Solution

N/A

### Steps to Reproduce

1. `git clone`
2. `npm i`

### Environment

* **Powertools version used**: 0.2.0
* **Packaging format (Layers, npm)**: npm
* **AWS Lambda function runtime:** N/A - local development
* **Debugging logs:**

```sh
npm --version
8.3.0
```

```sh
node --version
17.3.0
```

Running on Apple Silicon

### Related issues, RFCs

N/A

**Comment by michaelbrewer** [comment]
Following Makefile works for me now when i run `make dev`

```Makefile
dev:
	cd packages/commons; npm ci
	cd packages/logger; npm ci
	cd packages/metrics; npm ci
	cd packages/tracing; npm ci
	npm ci
	npm run init-environment
```

**Comment by michaelbrewer** [comment]
- https://github.com/awslabs/aws-lambda-powertools-typescript/pull/417

A fix is up, to confirm it works just run:

```
git clean -fdx
npm ci
npm run init-environment
npm run test
```

**Comment by simonireilly** [comment]
Looks like the packages don't know how to build their references.

```json
// tsconfig.json
  "references"
```
Use this to declare a list of modules this package depends on.

When running `tsc --build` it will build its references first, then import them.

When using vscode it does this in a background thread continuously to maintain accurate intellisense.

I can put a PR in for this, as it's probably the long term fix, over maintaining a topographical build command.

**Comment by michaelbrewer** [comment]
@simonireilly  - cool. i just wanted a fix to allow for people to work from the project :)

**Comment by simonireilly** [comment]
> @simonireilly - cool. i just wanted a fix to allow for people to work from the project :)

Totally, user experience and pragmatism first 🙏

**Comment by michaelbrewer** [comment]
@simonireilly  - i updated the PR to make the project references work
- https://github.com/awslabs/aws-lambda-powertools-typescript/pull/417


@dreamorosi PR is ready to review
