### ISSUE TITLE
Feature request: reduce npm_modules size 

### ISSUE THREAD

**Issue by saragerion** [aws-powertools/powertools-lambda-typescript#419]
## Bug description
The current bundle size of the Logger library is unnecessarily big. This has an impact on the performance of the Lambda functions (cold starts included).

### Expected Behavior

The node_modules folder has a reasonable size.

### Current Behavior

The node_modules folder is 139M.

### Possible Solution

One of the biggest reasons is the lodash library that is currently a prod dependency, which is unnecessary.
It would also be good to double check whether we publish the NPM packages installing only the prod dependencies and not the dev dependencies.

### Steps to Reproduce

Install the library in your local env, and check the node_modules folder size:

```
du -sh *
139M	node_modules
436K	package-lock.json
4.0K	package.json
```

### Environment

* **Powertools version used**: latest
* **Packaging format (Layers, npm)**: NPM
* **AWS Lambda function runtime:** all
* **Debugging logs:** N/A

### Related issues, RFCs

N/A

**Comment by saragerion** [comment]
Thanks @michaelbrewer for the heads-up!

**Comment by michaelbrewer** [comment]
of coz we should see what size the packaged lambda is and how small we can make it.

**Comment by dreamorosi** [comment]
Good point, we initially removed the whole `lodash` in favor of smaller packages [as mentioned here](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/139#issuecomment-888284501), but somehow it got reintroduced, I think around the time when we had multiple `eslint` configs.

**Comment by michaelbrewer** [comment]
@saragerion there is also a lot of test resources in "commons" that we already have in shared. About 208k worth.

**Comment by michaelbrewer** [comment]
I know this issue closed, but i assume for the production release there is plans to see how to minimize the size of the node_modules?  Like how the aws-sdk-v3 is very lightweight: https://aws.amazon.com/blogs/developer/how-we-halved-the-publish-size-of-modular-aws-sdk-for-javascript-clients/

And for non-typescript users? should @types/aws-lambda always be included?

And maybe tips for the lambda layer:
- https://github.com/ModClean/modclean
- https://github.com/tj/node-prune
- https://tsh.io/blog/reduce-node-modules-for-better-performance/
