### ISSUE TITLE
Bug: Remove dependency to fsevents

### ISSUE THREAD

**Issue by timohirt** [aws-powertools/powertools-lambda-typescript#421]
## Bug description

When I add the powertools to my project, it adds dependency to `fsevents`. On my Mac, running `npm install` defines the platform `darwin` for `fsevents`. The CI build run in CodeBuild and Linux. The build fails because the platfrom doesn't match.

```


npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
--
51 | npm ERR! notsup Valid OS:    darwin
52 | npm ERR! notsup Valid Arch:  undefined
53 | npm ERR! notsup Actual OS:   linux
54 | npm ERR! notsup Actual Arch: x64
```

I want to develop on my Mac and still be able to use Linux in CI.

### Expected Behavior

Npm should install all dependencies on both platforms.

### Current Behavior

See above. `fsevent` seems to use features of a specific operating system. Thus, I can't develop on my machine while using Linux in CI.

### Steps to Reproduce

1. npm install powertools on mac
2. add `package.json` and `package-lock.json`, commit and push
3. checkout code on a Linux machine
4. rum `npm ci`

### Environment

* **Powertools version used**: 0.2.0
* **Packaging format (Layers, npm)**: npm
* **AWS Lambda function runtime:** 
* **Debugging logs:**

**Comment by dreamorosi** [comment]
Hello thank you @timohirt for opening the issue. We'll have to look into it more closely and get back to you.

**Comment by dreamorosi** [comment]
Hello @timohirt I've been looking at this and I'm unable to reproduce. Could you please confirm that this is still an issue using the latest version on `main` and using `node@14.x` together with `npm@8.x` as described in the `CONTRIBUTING` document?

We are also using linux in our CI/CD and it seems to not be an issue.

**Comment by timohirt** [comment]
Hello @dreamorosi! It works for me now. Thanks!
