### ISSUE TITLE
Maintenance: Write and run tests against examples as part of the CI process

### ISSUE THREAD

**Issue by flochaz** [aws-powertools/powertools-lambda-typescript#425]
## Description of the feature request

**Problem statement**
Examples are for now only ran manually through manual CDK deploy and manual deployed resource check.

**Summary of the feature**
1. Add E2E tests (following what is done in each packages e2e tests to automate cdk stack deployment).
2. Add a step in CI to run them as part of merge to main.

### Related issues, RFCs

Avoid issue like #423 and #424 

Blocked by: https://github.com/aws/aws-cdk/issues/18211

**Comment by dreamorosi** [comment]
If we do this we'll need to downgrade the examples to cdk version `1.x` right?

**Comment by flochaz** [comment]
yep probably :( that is the reason why I didn't tackled this yet ...

**Comment by flochaz** [comment]
[Current workflow](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/workflows/run-e2e-tests.yml#L48) is giving enough confidence by relying on typescript build to test example don't get broken by new release pkg.
