### ISSUE TITLE
Maintenance: simplify local development setup

### ISSUE THREAD

**Issue by saragerion** [aws-powertools/powertools-lambda-typescript#426]
## Description of the feature request

Right now developers who want to contribute to the repository need to run a number of commands to get the project up and running. 
We should simplify this situation by creating a number of scripts that can setup the local environment with all the necessary tasks "with just one command" run in your terminal, and that's it.
I believe the Python repo has already something similar.

**Problem statement**

The lack of such solution is currently making the onboarding process of new contributors rather painful for folks who are new to the repository and especially new to the TypeScript and Node.js ecosystem.

**Summary of the feature**

Create a script that does all the necessary installations and lerna bootstrap.

**Code examples**

N/A

**Benefits for you and the wider AWS community**

Easier onboarding of new contributors.

**Describe alternatives you've considered**

Makefile
Bash scripts

**Additional context**

N/A

### Related issues, RFCs

#115 
#422

**Comment by michaelbrewer** [comment]
A makefile can have a low onboarding ie: `make dev pr` would install all dev dependencies (which could include dev tools or check requirements and install pre-commit hooks) and prepare for a pull request.

Otherwise something like this would be handy using `yarn` too.
