### ISSUE TITLE
Docs: CDK examples (metrics & tracer) have outdated references

### ISSUE THREAD

**Issue by mhboon** [aws-powertools/powertools-lambda-typescript#435]
## Bug description

In example-function.MyFunction and example-function.MyFunctionWithDecorator
line 9: const metrics = new Metrics({ namespace: namespace, service: serviceName });
service should be serviceName

In example-function.MyFunctionWithDecorator
typo in line 14 @tracer.captureLambdaHanlder() should be @tracer.captureLambdaHandler()

### Expected Behavior
Try out the examples

### Current Behavior
problems in IDE

### Possible Solution
correct the lines; see summary

### Steps to Reproduce
See summary

1.
2.
3.
4.

### Environment

* **Powertools version used**: 0.02
* **Packaging format (Layers, npm)**:
* **AWS Lambda function runtime:** N/A
* **Debugging logs:**

**Comment by saragerion** [comment]
Thanks for opening the issue, well spotted.

**Comment by dreamorosi** [comment]
@mhboon thanks a lot, we are planning on running tests on our CI for these examples to try to avoid this type of errors in the future, see also #425.
