### ISSUE TITLE
Maintenance: lerna version is bumping dependencies as well

### ISSUE THREAD

**Issue by flochaz** [aws-powertools/powertools-lambda-typescript#468]
## Bug description

On `lerna version`  (https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/workflows/on-release-prod.yml#L44) lerna bump all packages to new version in `package.json` and `package-lock.json`  but bump as well `@aws-lambda-powertools/commons` in our module package (https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/metrics/package.json#L87) event with put strict version due this https://github.com/lerna/lerna/issues/2326 .

### Expected Behavior

I would expect lerna to not touch my dependencies or at least update package-lock.json properly ....

### Current Behavior

lerna bump dependencies as well

### Possible Solution

Not sure yet

### Steps to Reproduce

run ` npx lerna version --conventional-commits --conventional-graduate --force-publish=* --yes --no-git-tag-version --no-push` 

`npm run lerna-ci` will fail

### Environment

* **Powertools version used**: 0.3.0
* **Packaging format (Layers, npm)**: -
* **AWS Lambda function runtime:** -
* **Debugging logs:** 
```
➜  aws-lambda-powertools-typescript git:(main) npm run lerna-ci

> aws-lambda-powertools-typescript@0.0.1 lerna-ci
> lerna exec -- npm ci

lerna notice cli v4.0.0
lerna info Executing command in 4 packages: "npm ci"
npm WARN prepare removing existing node_modules/ before installation

> @aws-lambda-powertools/commons@0.3.0 prepare /Users/chazalf/amazon/PowerTool/aws-lambda-powertools-typescript/packages/commons
> npm run build


> @aws-lambda-powertools/commons@0.3.0 build /Users/chazalf/amazon/PowerTool/aws-lambda-powertools-typescript/packages/commons
> tsc

added 574 packages in 13.871s
npm WARN prepare removing existing node_modules/ before installation
npm WARN prepare removing existing node_modules/ before installation
npm WARN prepare removing existing node_modules/ before installation
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```

**Comment by dreamorosi** [comment]
Can we close this after #470 has been merged?
