### ISSUE TITLE
Maintenance: move redundant code and functionalities in shared commons package

### ISSUE THREAD

**Issue by saragerion** [aws-powertools/powertools-lambda-typescript#484]
## Description of the feature request
The execution of this issue should be divided into 3 steps:

1. Vet the business logic of Logger, Tracer and Metrics utilities to identify code de-duplication opportunities. Opportunities found so far: cold-start business logic, fetching of environment variables. 
2. Add that logic in commons.
3. Remove duplicated logic from the single utilities, in favour of the logic from the commons package.

**Problem statement**

Right now there is a number of functionalities that are repeated throughout the 3 different utilities, all with their own business logic and separated unit tests. 
This is not optimal because:
- The same feature should have the same behaviour across all utilities
- This unnecessarily increases the cost of maintenance
- Code duplication inflates the libraries's size unnecessarily, with impact over the Lambda package size and consequently cold-starts 

**Summary of the feature**

See above.

**Code examples**

**Benefits for you and the wider AWS community**

**Describe alternatives you've considered**

**Additional context**

See here:
https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/logger/src/config/EnvironmentVariablesService.ts
https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/logger/src/Logger.ts#L92

### Related issues, RFCs

#165

N/A

**Comment by dreamorosi** [comment]
An internal RFC for centralising the cold start logic in the `commons` package has been created & reviewed by the team. Will be working on a PR in the coming days.

**Comment by dreamorosi** [comment]
First batch of changes regarding the cold start heuristic have been implemented in `commons` and released in `v0.6.0`, adoption in other utilities will be released with `v0.7.0` in the coming days.

**Comment by ijemmy** [comment]
We'll focus on moving the EnvironmentVariable helper class and close this ticket for Production Release.

**Comment by saragerion** [comment]
Update about this issue: we addressed successfully the cold start logic separation. 
We will think about better separations of concerns and abstractions when we will address this issue after GA:
https://github.com/awslabs/aws-lambda-powertools-typescript/issues/846
If necessary we will open another more scoped issue when we will address this unit of work.
Closing this one.

**Comment by dreamorosi** [comment]
This issue was a dependency of #165.

For the time being I have added #165 in the issue text of #846 as it has a fair bit of context & research on how the environment variables are being used. 

@saragerion With that said I would consider deprioritising that issue (currently is labeled as medium) or closing it entirely in favor of #846 similar to what done in this one.
