### ISSUE TITLE
Maintenance: release process not updating package-lock.json for examples after bumping deps

### ISSUE THREAD

**Issue by flochaz** [aws-powertools/powertools-lambda-typescript#494]
## Bug description

package.json not matching package-lock.json after bump

### Expected Behavior

lerna version should bump package.json and package-lock.json

### Current Behavior

Build failing https://github.com/awslabs/aws-lambda-powertools-typescript/runs/4895012434?check_suite_focus=true

### Steps to Reproduce

1.
2.
3.
4.

### Environment

* **Powertools version used**:
* **Packaging format (Layers, npm)**:
* **AWS Lambda function runtime:**
* **Debugging logs:**

**Comment by dreamorosi** [comment]
@flochaz is this still happening? Just wanted to make sure the issue is not stale.
