### ISSUE TITLE
Maintenance: make e2e test stack name unique

### ISSUE THREAD

**Issue by flochaz** [aws-powertools/powertools-lambda-typescript#497]
## Description of the feature request

**Problem statement**
As of today Stack names in e2e tests are static (see https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/metrics/tests/e2e/decorator.test.ts#L23 for instance) which prevent us from running multiple instances of e2e against different branches.

**Summary of the feature**
Add a random unique id, a branch name or a commit id to stack name in all e2e.

**Code examples**
```typescript
const stack = new Stack(integTestApp, `MetricsE2EDecoratorStack-${process.env.GITHUB_REF_NAME ? process.env.GITHUB_REF_NAME : 'unknown'}`);
```

List of available env var in github action: https://docs.github.com/en/actions/learn-github-actions/environment-variables

**Benefits for you and the wider AWS community**
Validate PR quickly

**Comment by ijemmy** [comment]
@flochaz  I'm going to refactor metrics & tracer e2e tests to be like logger (using uuid). I can take over this if you're ok.
