### ISSUE TITLE
Bug: package-lock.json might have been generated with node@16 breaking node@14 user build

### ISSUE THREAD

**Issue by flochaz** [aws-powertools/powertools-lambda-typescript#502]
## Bug description

See https://github.com/awslabs/aws-lambda-powertools-typescript/pull/326#issuecomment-1018930741

### Expected Behavior

TBD

### Current Behavior

TBD

### Possible Solution

TBD

### Steps to Reproduce

TBD

### Environment

* **Powertools version used**: 0.4.0
* **Packaging format (Layers, npm)**: npm
* **Debugging logs:** TBD

### Related issues, RFCs

#326 
https://github.com/awslabs/aws-lambda-powertools-typescript/pull/501

**Comment by dreamorosi** [comment]
Were you able to reproduce? Same user who reported [opened a PR](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/501) which then he closed after installing `npm@8.x` like the contributions docs say.

**Comment by flochaz** [comment]
Nope, indeed. closing.
