### ISSUE TITLE
Docs: code examples for logger and metrics have compile errors.

### ISSUE THREAD

**Issue by michaelbrewer** [aws-powertools/powertools-lambda-typescript#510]
## Bug description

Provided code examples have compile errors. And the to the Tracer from the readme is broken 

### Expected Behavior

Code examples should compile

### Current Behavior

Code examples don't all compile

### Possible Solution

Fix code examples

### Steps to Reproduce

1. Click on Tracer link goes to 404
2. metrics / logger examples have compile errors in webstorm and vscode

```shell
cd packages/metrics
npx tsc examples/*.ts
```

### Environment

* **Powertools version used**: main
* **Packaging format (Layers, npm)**:
* **AWS Lambda function runtime:**
* **Debugging logs:**

**Comment by flochaz** [comment]
Indeed, thx for reporting this, we were planning to potentially remove them since they are duplication of unit tests and global examples.

**Comment by michaelbrewer** [comment]
Ok. then there is also uploading the Readme, of whether or not to point out these examples or not. 

Example projects are really handy if they work :)

**Comment by michaelbrewer** [comment]
The `Tracer` example also goes to a 404:

<img width="178" alt="Screen Shot 2022-01-25 at 12 36 26 PM" src="https://user-images.githubusercontent.com/5442469/151055738-7884248a-3bc9-4a38-86a2-55b46a09e1b2.png">

**Comment by flochaz** [comment]
> Example projects are really handy if they work :)

The issue with current per package examples as they are today is that they can't really be copied and paste since their imports point to local implementation (for instance: `import { Logger } from '../src';`) so we were tempted to go more for what is in root `examples` folder to have only "compilable"/"deployable" examples and remove the packages' level one.

**Comment by flochaz** [comment]
> The `Tracer` example also goes to a 404:
> 
> <img alt="Screen Shot 2022-01-25 at 12 36 26 PM" width="178" src="https://user-images.githubusercontent.com/5442469/151055738-7884248a-3bc9-4a38-86a2-55b46a09e1b2.png">

Indeed that bad ...

**Comment by michaelbrewer** [comment]
Either way the immediate fix is in my PR.
