### ISSUE TITLE
Feature request: minimize size of  the production lambda-layer or published npm package

### ISSUE THREAD

**Issue by michaelbrewer** [aws-powertools/powertools-lambda-typescript#517]
## Description of the feature request

Try to keep the production deployed `node_modules`, without loss of functionality 

Related issue: https://github.com/awslabs/aws-lambda-powertools-typescript/issues/419#issuecomment-1022404877

**Problem statement**

Keeping the published npm package as lean as possible will benefit all users in terms of cold start.

**Summary of the feature**

- strip unneeded files (tests, .d.ts)
  - this is not needed for runtime
- strip unneeded dependencies or non-aws managed/secured (eg: `@types/aws-lambda` and `lodash.clonedeep` ?)
  - This is a security risk
  - It bloats the library when not needed (eg: for `createChild` we can also use `setOptions(` from the original or v8 built in deserialize / serialize)
  - some upstream bugs needs to be fixed (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/51120)
  - It is often easier to add a dependency than remove
  - it is harder for people to vendor powertools features
  - or not even referenced within the project `types/aws-lambda`.
- minify if not already

**Code examples**

NA

**Benefits for you and the wider AWS community**

Faster execution, deployments (especially if there are published lambda layers).

**Describe alternatives you've considered**

Using modclean, minify-all and node-prune and documentation on recommendations to reduce cold starts

**Additional context**

- https://github.com/ModClean/modclean
- https://github.com/tj/node-prune
- https://tsh.io/blog/reduce-node-modules-for-better-performance/
- https://aws.amazon.com/blogs/developer/how-we-halved-the-publish-size-of-modular-aws-sdk-for-javascript-clients/

### Related issues, RFCs

- https://github.com/awslabs/aws-lambda-powertools-typescript/issues/419

**Comment by saragerion** [comment]
Thanks for creating this issue. 
Good news are that this unit of work is already on our radar and we are looking at several ways in which we can iteratively reduce the size while also keep the size under control in the future. Possible iterations on this effort include some of the tips you mention, and also tree shaking and safety nets in our CI/CD pipeline.

Our team will definitely work on this, but we need to prfioritize other issues for now.

**Comment by michaelbrewer** [comment]
i am sure it makes sense once their is stability in the apis, integration and unit testing :). I am sure the community would really appreciate this level of effort. :) 

Another useful thing to consider is building some benchmarking to track for regressions.

**Comment by saragerion** [comment]
> Another useful thing to consider is building some benchmarking to track for regressions.

100%. Related comment: https://github.com/awslabs/aws-lambda-powertools-typescript/issues/398#issuecomment-1022101795
