### ISSUE TITLE
Maintenance: e2e test invocation always forces cold starts

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#590]
## Bug description

The [current implementation of the helper function that invokes functions](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/logger/tests/helpers/e2eUtils.ts#L73-L91) deployed as part of the e2e test of the logger calls the functions in parallel. This has the potentially unintended effect of always forcing cold starts in the functions. This happens because  the Lambda service receives two concurrent invocation requests and as such it has to spin up two execution environments to handle them.

Some of the test cases, [like this one](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/logger/tests/e2e/basicFeatures.middy.test.ts#L101-L113), that intend to assert that the correct cold start value is included in the log entries are affected as result and can never pass.

### Expected Behavior

Test case to pass if tested code is correct.

### Current Behavior

Test case always fails.

### Possible Solution

Two possible solutions:

### Option A

Change the helper function to **always** invoke functions in sequence rather than in parallel, like so **(this implementation makes the test pass with the changes in #550)**:
```ts
export const invokeFunction = async (functionName: string, times: number = 1): Promise<InvocationLogs[]> => {
  const invocationLogs: InvocationLogs[] = [];
    
  for (let i = 0; i < times; i++) {
    const response = await lambdaClient
      .invoke({
        FunctionName: functionName,
        LogType: 'Tail', // Wait until execution completes and return all logs
      })
      .promise();
    if (response?.LogResult) {
      invocationLogs.push(new InvocationLogs(response?.LogResult));
    } else {
      throw new Error('No LogResult field returned in the response of Lambda invocation. This should not happen.');
    }
  }

  return invocationLogs; 
};
```

### Option B

Change the helper function to accept a third param `parallel` (defaults to `true`) and let the caller decide (pseudo-code example):
```ts
export const invokeFunction = async (functionName: string, times: number = 1, parallel: boolean = true): Promise<InvocationLogs[]> => {
  const invocationLogs: InvocationLogs[] = [];
  const promises = [];
   
  if (parallel) {
    // ... logic that invokes functions in parallel
  } else {
    // ... logic that invokes functions sequentially
  }

  return invocationLogs; 
};
```

The benefit of this second option is that since most test cases don't care about the mode of invocation they could have slightly faster execution time (since they'd be invoked in parallel).
The downside of this option is that there's now additional cognitive load for maintainers since this introduces two branches in the code and in case of failure we'd have to first check which mode was used.

### Steps to Reproduce

1. Enable tracing in the `e2eUtils.ts` file for the functions part of the test
2. Run e2e tests for logger
3. Observe results traces generated (attached below)
![Screenshot 2022-02-24 at 13 26 06](https://user-images.githubusercontent.com/7353869/155526460-ed8907b6-9264-424f-bfb9-0015f15117ad.png)
4. See that first execution trace has an Initialisation phase in the X-Ray generated traces (these are generated by Lambda & X-Ray, Powertools Tracer is not being used)
![Screenshot 2022-02-24 at 13 26 17](https://user-images.githubusercontent.com/7353869/155526504-4a4d5503-4bd4-463d-a4ab-d1f304e6a17c.png)
5. See second execution trace and observe that this also has an Initialisation phase6. 
![Screenshot 2022-02-24 at 13 26 27](https://user-images.githubusercontent.com/7353869/155526699-78283410-49d6-4793-b0d4-351289d37ae0.png)

### Environment

* **Powertools version used**: N/A
* **Packaging format (Layers, npm)**: N/A
* **AWS Lambda function runtime:** all
* **Debugging logs:** N/A

### Related issues, RFCs

[#550](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/550)

**Comment by awsdb** [comment]
Happy to help with this one!

**Comment by ijemmy** [comment]
I'm also supportive of option B. 

In Logger, we have a sample rate testing. In this case, I did it in parallel as I have to run Lambda 20+ times.
