### ISSUE TITLE
Bug: Importing Common Index in Logger Folder raises Module Error

### ISSUE THREAD

**Issue by Muthuveerappanv** [aws-powertools/powertools-lambda-typescript#664]
## Bug description

1. `npm production` package of `powetools-logger' is breaking in 0.0.7, due to importing commons package in [Logger.ts](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/v0.7.0/packages/logger/src/Logger.ts#L2)
2. Error due to the `tests` export that are part of the [commons/index](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/commons/src/index.ts#L3-L4)

### Expected Behavior

0.0.7 version to work fine without `module error` when `tests` folder are removed at the time of pruning for production-ready build
(Or if the package `tests` being exported out of commons is needed, please rename the folder as pruning utilities like [node-prune](https://github.com/tj/node-prune) are trimming off `tests`)

### Current Behavior
No Module Found Error when using Powertools Logger package 
```
stack": [
        "Runtime.ImportModuleError: Error: Cannot find module './tests/resources/contexts'",
        "Require stack:",
        "- /var/task/node_modules/@aws-lambda-powertools/commons/lib/index.js",
        "- /var/task/node_modules/@aws-lambda-powertools/logger/lib/Logger.js",
        "- /var/task/node_modules/@aws-lambda-powertools/logger/lib/index.js",
```

### Possible Solution
1. Do not export `tests`
2. Or if the package `tests` needs to be exported, please rename the folder as pruning utilities like [node-prune](https://github.com/tj/node-prune) are trimming off `tests`)

### Steps to Reproduce

1. `npm install` project with `"@aws-lambda-powertools/logger": "^0.7.0"`
2. `node-prune` using https://github.com/tj/node-prune

### Environment

* **Powertools version used**: 0.0.7
* **Packaging format (Layers, npm)**: npm
* **AWS Lambda function runtime:** : nodejs 14.x
* **Debugging logs:**
![Screen Shot 2022-03-14 at 11 50 46 AM](https://user-images.githubusercontent.com/33663725/158213339-ce5e814d-b1b0-49db-988f-ff85f576ea8c.png)

**Comment by dreamorosi** [comment]
Hi @Muthuveerappanv

first of all, thanks a lot for reporting the issue and also apologies for the delay in acknowledging it from our side. We have been busy at polishing the utilities to prepare for the launch.

I have looked at the issue reported and I was able to reproduce it.

I'll leave here a link to a repo where I was able to reproduce and document the steps for the person who will resolve the issue: https://github.com/dreamorosi/test-664

**Comment by Muthuveerappanv** [comment]
> Hi @Muthuveerappanv
> 
> first of all, thanks a lot for reporting the issue and also apologies for the delay in acknowledging it from our side. We have been busy at polishing the utilities to prepare for the launch.
> 
> I have looked at the issue reported and I was able to reproduce it.
> 
> I'll leave here a link to a repo where I was able to reproduce and document the steps for the person who will resolve the issue: https://github.com/dreamorosi/test-664

I created a [PR](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/881) to import Utility components from `/lib` instead of top level pacakge. Let me know if this will do.
