### ISSUE TITLE
Maintenance: ignore available updates for CDK v2 and reduce frequency of new PRs

### ISSUE THREAD

**Issue by saragerion** [aws-powertools/powertools-lambda-typescript#672]
## Description of the feature request

Context - Dependabot
We use dependabot for version updates:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

Our current dependabot configuration can be found here:
https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/dependabot.yml
Our team merges or rejects PRs automatically opened by the dependabot around once a week (usually on Fridays). 

We need to update our current dependabot configuration to reduce the number of PRs open at once, especially the ones we don't need. 

**Problem statement**

Problem 1:
As stated in our [Contributing guidelines](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/CONTRIBUTING.md), we use [AWS CDK v1](https://docs.aws.amazon.com/cdk/v1/guide/getting_started.html) library and not v2 due to [this limitation](https://github.com/aws/aws-cdk/issues/18211).

Right now we receive a lot of PRs requests opened by the dependabot, to update CDK dependencies to the v2 versions. This adds a lot of noise and requires the continuous action of closing/ignoring those PRs.

Problem: 2
Since we merge dependabot PRs once a week but the dependabot PRs are created daily, this results in a lot of PRs being opened every day that add a lot of noise and pollution to our PR list.

**Summary of the feature**

[] Reduce the frequency of PRs from daily to weekly (ideally on a thursday)
[] Ignore version updates for dependecies related to CDK v2.

**Code examples**

Github docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore

**Benefits for you and the wider AWS community**

Maintainers more focused and less distracted. 

**Describe alternatives you've considered**

N/A

**Additional context**

N?A

### Related issues, RFCs

https://github.com/aws/aws-cdk/issues/18211

**Comment by dreamorosi** [comment]
Just an additional nuance to complement the CDK topic: we are using CDK v1 in the integration tests of the utilities (i.e. under `packages/logger/tests/e2e/`), this is rolled up into the `package.json` & `package-lock.json` in the root of the project ([here](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/package.json#L50-L53)).

We are instead using CDK v2 the examples (under `examples/cdk`), this dependency is instead tracked in `examples/cdk/package.json` (since the examples are not part of the npm workspace.

**Comment by dreamorosi** [comment]
First part of this issue has already been addressed in #676 so we are not using CDK v1 anymore in this repo.
