### ISSUE TITLE
Maintenance: publish to github pages failed step 

### ISSUE THREAD

**Issue by saragerion** [aws-powertools/powertools-lambda-typescript#673]
## Bug description

This morning the API spec page was returning 404:
https://awslabs.github.io/aws-lambda-powertools-typescript/latest/api/

I noticed that this job, triggered by release v0.7.1, failed: https://github.com/awslabs/aws-lambda-powertools-typescript/runs/5586151464?check_suite_focus=true

After re-running the failed job, the job completed successfully and the API docs page was restored:
https://github.com/awslabs/aws-lambda-powertools-typescript/runs/5598299456?check_suite_focus=true

### Expected Behavior

The API docs page is deployed correctly.
https://awslabs.github.io/aws-lambda-powertools-typescript/latest/api/

### Current Behavior

A release workflow resulted in the API docs returning 404.

### Possible Solution

To be scoped. 

### Steps to Reproduce

This was triggered from the release process, see links provided above.

### Environment

* **Powertools version used**: v0.7.1
* **Packaging format (Layers, npm)**: NPM 8
* **AWS Lambda function runtime:** N/A
* **Debugging logs:** See links

### Related issues, RFCs

N/A

**Comment by dreamorosi** [comment]
Closing this issue for now as we have updated our documentation publishing process in https://github.com/awslabs/aws-lambda-powertools-typescript/pull/1023, https://github.com/awslabs/aws-lambda-powertools-typescript/issues/1053, and https://github.com/awslabs/aws-lambda-powertools-typescript/pull/1054.

If the issue reappears let's open a new issue.
