### ISSUE TITLE
Docs: How to pass log extra input without type errors

### ISSUE THREAD

**Issue by AlessandroVol23** [aws-powertools/powertools-lambda-typescript#750]
## Bug description

I want to log extra data, so I pass it to the logger. For example:

```ts
  const params: SendMessageRequest = {
    MessageBody: JSON.stringify(message),
    QueueUrl: queueUrl,
    MessageGroupId: '1'
  };


  logger.info('Send sqs message with params: ', { params });
```

The line with the `logger` has the following type error:

```
Argument of type '[{ params: SendMessageRequest; }]' is not assignable to parameter of type 'LogItemExtraInput'.
  Type '[{ params: SendMessageRequest; }]' is not assignable to type '[string | Error]'.
    Type '{ params: SQS.SendMessageRequest; }' is not assignable to type 'string | Error'.
      Object literal may only specify known properties, and 'params' does not exist in type 'Error'.
```

**I get why this error is coming but what is the expected way of doing that?** 

Logging extra input that is not of type error or string.

### Expected Behavior

No type error if it is another type than error or string since it can be easily logged.

### Current Behavior

Type error instead of no type error

### Steps to Reproduce

```ts
import { Logger } from '@aws-lambda-powertools/logger';
const logger = new Logger({ serviceName: 'UserRequestHandler' });

  const params: SendMessageRequest = {
    MessageBody: JSON.stringify(message),
    QueueUrl: queueUrl,
    MessageGroupId: '1'
  };


  logger.info('Send sqs message with params: ', { params });
```

### Environment

* **Powertools version used**: 0.7.2
* **Packaging format (Layers, npm)**: npm 
* **AWS Lambda function runtime:** nodejs 14
* **Debugging logs:**

**Comment by dreamorosi** [comment]
Hello @AlessandroVol23 thanks for your interest in Powertools!

In order to log extra data, and specifically an object, you can use this syntax:
```ts
// ... Imports & handler function

const params = {
    MessageBody: JSON.stringify({ message: 'Hello World!' }),
    QueueUrl: 'someurl',
    MessageGroupId: '1'
};


logger.info('Send sqs message with params: ', { data: params });
```
The above results in these CloudWatch logs:
```sh
START RequestId: 3dd91105-aa76-4ed6-a104-70905c90bd12 Version: $LATEST
2022-04-10T15:24:18.651Z	3dd91105-aa76-4ed6-a104-70905c90bd12	INFO	{"level":"INFO","message":"Send sqs message with params: ","service":"serverlessAirline","timestamp":"2022-04-10T15:24:18.633Z","data":{"MessageBody":"{\"message\":\"Hello World!\"}","QueueUrl":"someurl","MessageGroupId":"1"}}
END RequestId: 3dd91105-aa76-4ed6-a104-70905c90bd12
REPORT RequestId: 3dd91105-aa76-4ed6-a104-70905c90bd12	Duration: 59.44 ms	Billed Duration: 60 ms	Memory Size: 128 MB	Max Memory Used: 57 MB	Init Duration: 198.80 ms	
XRAY TraceId: 1-6252f6a2-742200dd28a2770010511135	SegmentId: 3a0b0093756e7943	Sampled: true	
```

You can find more examples of how to append data to your logs in [this section of the documentation](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/logger/#appending-additional-log-keys-and-values-to-a-single-log-item), the one you're looking for is at line 18 of the example in that section.

**Comment by AlessandroVol23** [comment]
Ah I just used it wrong. Thanks for the clarification! 😃
