### ISSUE TITLE
Maintenance: have descriptive logs in the integration tests

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#825]
## Description of the feature request

**Problem statement**
Now that we are running more integration tests (multiple runtimes for each utility) and in parallel it would be beneficial to have logs that explicitly indicate which utility they belong to. This would help troubleshoot faster in case of issues.

**Summary of the feature**
Currently this is how the log prefix are:
![image](https://user-images.githubusercontent.com/7353869/165973199-70315f69-f7b4-453f-8667-4fed7e2aff1a.png)

Ideally we could have something like:
```
[logger:e2e:nodejs14x]
[tracer:e2e:nodejs14x]
[metrics:e2e:nodejs12x]
```

**Code examples**
N/A

**Benefits for you and the wider AWS community**
N/A - this change concerns mainly maintainers.

**Describe alternatives you've considered**
None / scroll through the logs 

**Additional context**
N/A

### Related issues, RFCs

N/A

**Comment by ijemmy** [comment]
GitHub matrix strategy may be a better approach. It will fix this issue and be more efficient. I'm looking into that.
