### ISSUE TITLE
Feature request: AWS Lambda Layers support

### ISSUE THREAD

**Issue by saragerion** [aws-powertools/powertools-lambda-typescript#826]
## Description of the feature request

**Problem statement**

Currently AWS Lambda Powertools for Python supports usage via a Lambda Layer. The TypeScript Powertools do not. 

**Summary of the feature**

[Lambda Layer](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html) is a .zip file archive that can contain additional code, pre-packaged dependencies, data, or configuration files. Layers promote code sharing and separation of responsibilities so that you can iterate faster on writing business logic.

This issue would include Lambda Powertools Lambda Layer using [AWS Lambda Console](https://docs.aws.amazon.com/lambda/latest/dg/invocation-layers.html#invocation-layers-using), or your preferred deployment framework.

When using Layers, you can add Lambda Powertools as a dev dependency (or as part of your virtual env) to not impact the development process.

Additionally, Lambda Layers allow us to understand who uses this library in a non-intrusive way. This helps us justify and gain future investments for other Lambda Powertools languages.

**Code examples**

https://awslabs.github.io/aws-lambda-powertools-python/latest/#install

**Benefits for you and the wider AWS community**

A different way to install and leverage the library.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### Related issues, RFCs

N/A

**Comment by orozcoadrian** [comment]
Lambda layers can be architecture-specific, if they contain native code. Assuming there's no native code in this library, it will be compatible with both `x86` and `arm64`. It'd be nice to make that explicit in the documentation.

Reference:
https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-to-arm-based-aws-graviton2-processors/#:~:text=Functions%20without%20architecture%2Dspecific%20dependencies%20or%20binaries

For illustration, here's a lambda layer that only works with `x86`, but there's no mention of it in the docs: https://serverlessrepo.aws.amazon.com/applications/us-east-1/145266761615/image-magick-lambda-layer

**Comment by idm-ryou** [comment]
Thank you for your great work. 
It would be helpful to have a table on the website that maps the npm package version to the Lambda Layer version.

**Comment by dreamorosi** [comment]
> Thank you for your great work.
> It would be helpful to have a table in the documentation that maps the npm package version to the Lambda Layer version.

Hi @idm-ryou, thanks for the feedback. While looking at the docs you should be able to see the package version at the top of the page:
![image](https://user-images.githubusercontent.com/7353869/196406585-4aa093cf-e534-4e38-939b-16ae80465117.png)
All the contents of the docs, including layer version, refer to that version.

At the moment however, we have an issue in our release process that makes it so that library version & layer version shown in the docs are out of sync. For instance, at the moment our v1.3.0 documentation is showing Layer version 2 while it should show version 3.

We are tracking work to fix the issue here #1124

**Comment by dreamorosi** [comment]
Released in v1.3.0
