### ISSUE TITLE
Maintenance: rename Tracer's folder to "packages/tracer"

### ISSUE THREAD

**Issue by saragerion** [aws-powertools/powertools-lambda-typescript#829]
## Bug description

More of a chore than a bug but the Tracer utility is called "Tracer" everywhere except than in the name of its containing folder.
This inconsistency causes annoyance and confusion, especially dealing with Github Actions. 

### Expected Behavior

Rename the current folder of the Tracer utility from:
`packages/tracing`
to 
`packages/tracer`

### Current Behavior

N/A

### Possible Solution
N/A

### Steps to Reproduce

N/A

### Environment

* **Powertools version used**: all
* **Packaging format (Layers, npm)**: NPM
* **AWS Lambda function runtime:** N/A
* **Debugging logs:** N/A

### Related issues, RFCs

N/A

**Comment by dreamorosi** [comment]
You have no idea how many times I got this wrong lol

Just for documentation purposes, I want to link the issue where we decided this naming convention #26
