### ISSUE TITLE
Feature request: single meta-package

### ISSUE THREAD

**Issue by m-radzikowski** [aws-powertools/powertools-lambda-typescript#879]
## Description of the feature request

**Problem statement**

With the powertools being published as separate, modular packages, you need to install multiple `@aws-lambda-powertools/*` packages. Modularization is great for both development and keeping the dependencies small. But if you want to use several utilities from the powertools, it becomes annoying to install them separately and bump versions of all of them when there is a new release.

**Summary of the feature**

Create and publish a meta-package that includes all of the utilities. It can be a package that has dependencies on all other packages. Then you can install just a single package and have all the powertools available.

If you use esbuild, webpack, or similar bundler with tree-shaking, this will not affect the output bundle size, as unused dependencies will be omitted. However, when not using such bundler, it will be a better option to install separate packages and pick only what you need.

**Code examples**

Usage can be as simple as:

```
npm install aws-lambda-powertools
```

**Benefits for you and the wider AWS community**

Similar to AWS CDK v2, it's easier to use the package with just a single dependency.

**Describe alternatives you've considered**

Installing all packages individually. The drawbacks are:

- more packages to maintain in package.json
- more packages to update the version

**Additional context**

### Related issues, RFCs

[#125](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/125)

**Comment by saragerion** [comment]
Thanks for your proposal. I actually thought about it too. From a developer perspective, it would definitely simplify the installation and usage process.
To manage expectations: we will discuss this and, if moved forward, this will be implemented after the GA milestone.
