### ISSUE TITLE
Bug: Logger doesn't log to vscode debug terminal

### ISSUE THREAD

**Issue by Stefan-WW** [aws-powertools/powertools-lambda-typescript#926]
Hello,

While development, i run my code locally in vscode.
But the lambda-powertools-logger doesn't log to the vscode debug terminal.

The following Code shows the Problem.

`            

            const logger = new Logger({ serviceName: 'MyService', logLevel: 'DEBUG' });
            logger.debug('debug');
            logger.warn('warn');
            logger.error('error');
            logger.info('info');
            console.log('real logging');
            console.warn('real warning');
            console.info('real info');`

If i use console.log etc the Loggings are shown in the vscode debug terminal. 
But the logger from the powertools are not shown.

if i would add a small hack above: 
`            
//@ts-ignore
logger.console = console;
`

Then the loggings are shown in the debug terminal.

### Expected Behavior

The Logs which are written, should be also shown in the vscode debug terminal.

### Environment

* **Powertools version used**: 0.9.1
* **Packaging format (Layers, npm)**: npm
* **AWS Lambda function runtime:** nodejs

**Comment by dreamorosi** [comment]
@StefanVolkmer-WW thanks for opening the issue.

Could you please share your `.vscode/launch.json` or alternative clarify how you are executing the function? Would like to try to reproduce the issue.

**Comment by StefanV85** [comment]
Hello @dreamorosi 
The Launch Config is the following: 
`
{
    "version": "0.2.0",
    "configurations": [
          {
            "type": "node",
            "request": "launch",
            "name": "launch",
            "program": "${workspaceRoot}/index.js",
            "preLaunchTask": "TypeScript->JavaScript"
        }
    ]
}
`

You can reproduce it with a Standard Config.
I created a Hello World Project: 
https://github.com/StefanV85/LambdaPowerToolsLoggerExample

Just Clone the Repository, 
run npm install 
Run the Launch Config.
