### ISSUE TITLE
Maintenance: package size report failing

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#991]
## Bug description

The newly merged "Package size report" step in our CI/CD is currently failing for all executions, [see example here](https://github.com/awslabs/aws-lambda-powertools-typescript/runs/6975736080?check_suite_focus=true).

### Expected Behavior

Step should be succeeding and report the size.

### Current Behavior

It fails

### Possible Solution

N/A

### Steps to Reproduce

N/A

### Environment

* **Powertools version used**:
* **Packaging format (Layers, npm)**:
* **AWS Lambda function runtime:**
* **Debugging logs:**

### Related issues, RFCs

#878

**Comment by flochaz** [comment]
Dependabot only have Read-only permission (https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/) . Need to investigate what is the best to give only permission to comment (and read https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

**Comment by dreamorosi** [comment]
Okay, so this issue would happen only for dependant's PRs?

For PR that come from real users would it work fine? And what about from forks?

**Comment by flochaz** [comment]
PR from fork won't work neither. 
Changing to `pull_request_target` with an explicit PR checkout would most likely work but is opening vulnerability (https://securitylab.github.com/research/github-actions-preventing-pwn-requests/). Risk can be mitigated with what we already have (need of approval before workflow run for forked PR) or add label check (see https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ for more details on that).

But the recommended approach would be to split in 2 flows : one to build and capture all the actions outputs in a dedicated workflow triggered `on pull_request` and have a chain workflow to add comment with write permission ...

**Comment by dreamorosi** [comment]
Oh I see what you mean, check [this PR that I was working a year ago](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/169/files) that used [data artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) from one workflow and then used them to do something.

Thanks for looking into this!

**Comment by flochaz** [comment]
> Oh I see what you mean, check [this PR that I was working a year ago](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/169/files) that used [data artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) from one workflow and then used them to do something.
> 
> Thanks for looking into this!

But I need to change the way the action work, will propose a fix asap

**Comment by dreamorosi** [comment]
yes sorry, didn't mean to say it was a solution, I was just sharing in case it was helpful

**Comment by dreamorosi** [comment]
Wanted to leave here some info to keep the issue up to date with the current state of events:
- We have disabled Dependabot automatic PRs for regular updates in #992 - this means the number of Dependabot PRs will considerable decrease and be limited to security-related updates
- For any kind of Dependabot PR I have found out that manually re-running the actions (i.e. after they have failed) removes the issue ([example](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/2619900509))
- Considering the previous two points we currently think it's acceptable to have to manually re-run these actions given the low and sporadic amount of PRs coming from the bot
- Alternatives such as [GitHub Actions Job Summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/), paired with a threshold of the % increase that would make the action fail altogether could potentially remove the permission issue around comments

**Comment by dreamorosi** [comment]
Released as a part of v1.1.0
